### ISSUE TITLE
Unable to choose between 3D and non-3D variants of a movie

### ISSUE THREAD

**Issue by tonyarnold** [iBaa/PlexConnect#170]
I have both 2D and 3D versions of some of my films in Plex, but I can't find any way to select which PlexConnect will choose to play. Am I missing something, or is this something yet to be added?

**Comment by RageInvader** [comment]
You could put all your 3D movies in a separate library. I have three libraries. 3D Movies, Movies, and TV Shows. Keeps all the 3D Movies separate.

**Comment by moodyblue** [comment]
Pls use separate libraries for 3D

https://support.plex.tv/articles/200381043-multi-version-movies/
