### ISSUE TITLE
Transcoding: Hight CPU Usage

### ISSUE THREAD

**Issue by swams** [iBaa/PlexConnect#180]
Have you changed how Plexconnect transcod because now it is using much more CPU power than before. my CPU is almost at 80% used by "Plex New Transcoder".

My config is Mac mini Mid 2011 intel core i5 / 8gb of RAM / AMD Radeon 6630M 256MB / SSD 128GB / Mavericks (clean install). Furthermore I conducted several test on different config and met the same issue. 
If I use only PMS the CPU power remains quite low

**Comment by RageInvader** [comment]
I noticed in 'ATVSettings.cfg' its defaulted to "transcoderaction = Transcode" rather than auto.

**Comment by iBaa** [comment]
From ATVSettings.py:
```
    'transcoderaction'  :('Auto', 'DirectPlay', 'Transcode'), \
```
First position is the default, the later other valid options. My system defaults to Auto...
What system are you using? Where is your installation from? Did you delete your ATVSettings.cfg and have PlexConnect generate a fresh one?
