### ISSUE TITLE
Add TV Show Air Date

### ISSUE THREAD

**Issue by jeffkibuule** [iBaa/PlexConnect#187]
Is it possible to add the TV Show air date to the season list of episodes like Apple does? Presumably Plex already has this date stored in it's database that can be accessed with an API call.

And I guess if that starts working, we can get fancier with it saying "Yesterday" instead of 11/16 if the current date is 11/17. Just a suggestion. Thank you!

**Comment by moodyblue** [comment]
Thanks for the suggestion. If you are still interested on the matter pls submit a feature request to Plex Media Server, where I think that this functionality belongs.
