### ISSUE TITLE
Doesn't work with Python 2.6

### ISSUE THREAD

**Issue by vendruscolo** [iBaa/PlexConnect#202]
Hello everybody!

I'm on Snow Leopard (which comes with Python 2.6) and Plex Connect doesn't work with this version of Python.
(It runs "fine", but Trailers.app on the AppleTV can't load data. After a minute it times out and says "Can't load Trailers.app" or something similar. Plex Connect logs that it serves "application.js" and stops there).

I installed Python 2.7 with its official installer (got from python.org/download) and now it works.

I edited the startup script to execute `/usr/local/bin/python PlexConnect.py`, because the installer installs Python 2.7 in `/usr/local`, and I didn't like changing root's `PATH` env (you know, `launchd`).

So, what I'm suggesting here is to update the README saying that Python 2.6 is not supported, and to change the startup script to detect Python's version and/or if there are multiple versions installed, in order to point to the right version.

What do you think?

**Comment by wahlmanj** [comment]
I made a app that will update your python to 2.7.9 systemwide. You can also do this manually if you desire to do it manually open the app in automator and use what you need. This allows the default PlexConnect.bash to function properly on 10.6.x OS X.

https://github.com/wahlmanj/git/raw/master/Python%20updater.zip

**Comment by moodyblue** [comment]
Old thread. Closing.
