### ISSUE TITLE
multi file playback

### ISSUE THREAD

**Issue by patrickkettner** [iBaa/PlexConnect#246]
I know that the playback of multiple files (pressing play on a season or a show would play all episodes, etc) is already [planned for the 0.4 release](https://github.com/iBaa/PlexConnect/wiki/Roadmap), but I was wondering if one of the developers could share some ideas for how this would be implemented. I would love to help, but I am lost as to where to start.

[also see forum discussion](https://forums.plex.tv/index.php/topic/78995-playback-help-in-apple-tv3-plex/?p=508845)

**Comment by moodyblue** [comment]
Is this still an issue ? Or is it already corrected ?

**Comment by moodyblue** [comment]
Closed due to inactivity.
