### ISSUE TITLE
PlexConnect will not run as a launctl daemon on 10.6.8 Build 10K549 - AppleScript workaround

### ISSUE THREAD

**Issue by wejones** [iBaa/PlexConnect#250]
Have had trouble installing PlexConnect to LaunchDaemons on my system. The install scripts run without error as far as I can see (though I haven't tried enabling any advanced logging). Bash script seems to run on start up, and launchctl reports the plexconnect daemon as running, and it seems to respond to reload commands. netstat reports that my system is listening on ports 80 and 443. My AppleTV, however, won't see my Plex server when I try to run PlexConnect as a launch daemon.

PlexConnect runs like a champ when I invoke it from the command line, though. Every time.

I have even tried editing the bash script to explicitly run python v.2.7 from /usr/local/bin/python as discussed in Issue 202, since I'm on Snow Leopard and Python 2.7 had to be installed by hand. Seemed like that might be worth a try.

One detail I should mention. This machine runs ElGato's EyeTV software. Sharing is turned off in EyeTV's preferences, but I have not tested how PlexConnect functions with EyeTV removed, because I am not willing to sacrifice my ability to record live TV. While I acknowledge that EyeTV may play a role in keeping the PlexConnect launchctl daemon from running properly, I'd like to emphasize PlexConnect runs properly when invoked from command line by hand.

It's really important to me to have PlexConnect run on start up, so I've settled on a workaround for the moment. I have written an Applescript that will invoke PlexConnect.py as a superuser, and saved that script as an application which I have added to my account's login items in System Preferences. This accomplishes my goal of launching PlexConnect on machine start up, since this media center Mac Mini logs in automatically. There is a drawback to my workaround. The admin account password is passed in the clear in the Terminal when invoked by my script. This is not a show-stopper for me since this machine is only used for media services (not online banking), it is physically secure, and firewalled. I also like that my script leaves the terminal window open so I can stop PlexConnect using Ctrl-C, and relaunch the server easily from the shell buffer.

I am pasting in my AppleScript here in case it is useful to anyone else. Please feel free to improve it and re-share. 

Save the script as an Application from within AppleScript Editor (after subbing in your admin account's password) and then you can add the resulting application as a login item.

I call this AppleScript application PlexConnect Launcher.

```
tell application "Terminal"
    activate
    delay 10
    set shell to do script "echo <INSERT ADMIN PASSWORD> | sudo -S /usr/local/bin/python /Applications/PlexConnect-master/PlexConnect.py" in window 1
end tell
```

**Comment by wahlmanj** [comment]
I made a app that will update your python to 2.7.9 systemwide. You can also do this manually if you desire to do it manually open the app in automator and use what you need. This allows the default PlexConnect.bash to function properly on 10.6.x OS X.

https://github.com/wahlmanj/git/raw/master/Python%20updater.zip

**Comment by IMNotMax** [comment]
Good job, it works perfectly !
Thanx !
