### ISSUE TITLE
ATV 6.0.2: Trailers is unavailable. Try again later.

### ISSUE THREAD

**Issue by zeke** [iBaa/PlexConnect#252]
I found a few related issues but they're closed or related to earler ATV versions:
- https://github.com/iBaa/PlexConnect/issues/110
- https://github.com/iBaa/PlexConnect/issues/28

I also saw this:

> We only want issues to be opened on Github if someone is prepared to contribute code improvements.

I'm ready and willing to send a pull request to update docs or whatever, once I get this running.

Here's my setup:
- Apple TV Sofware 6.0.2 (6646.81.1)
- OS X Mavericks
- DHCP reservations configured
- SSL certs generated
- Running Plex Media Server at `http://127.0.0.1:32400`
- Running `sudo ./PlexConnect.py`

I'm seeing traffic in the PlexConnect logs:

```
20:49:00 DNSServer: DNS request received!
20:49:00 DNSServer: Source: ('10.0.0.2', 56362)
20:49:00 DNSServer: Domain: trailers.apple.com
20:49:00 DNSServer: ***intercept request
20:49:00 DNSServer: -> DNS response: 10.0.0.4
20:51:00 DNSServer: DNS request received!
20:51:00 DNSServer: Source: ('10.0.0.2', 56647)
20:51:00 DNSServer: Domain: bookkeeper.itunes.apple.com
20:51:00 DNSServer: ***forward request
20:51:00 DNSServer: -> DNS response from higher level
20:51:00 DNSServer: DNS request received!
20:51:00 DNSServer: Source: ('10.0.0.2', 63306)
20:51:00 DNSServer: Domain: upp.itunes.apple.com
20:51:00 DNSServer: ***forward request
20:51:00 DNSServer: -> DNS response from higher level
```

Yet when I open the Trailers app I see a black screen with the following words:

> Trailers is unavailable. Try again later.

I tried unplugging the Apple TV as well as restarting the server. At one point I also saw this message with a spinner below it but it never finished:

> Accessing Trailers

Any tips appreciated.

**Comment by tkluysk** [comment]
This fixed it for me (as of step 5):
https://miapple.me/plexconnect-installling-certificates-on-apple-tv-without-usb/
