### ISSUE TITLE
Suggestion: Cinema Trailers Support

### ISSUE THREAD

**Issue by jjsipahigil** [iBaa/PlexConnect#268]
I would like to suggest the implementation of Plex's new trailer option where you can choose to have the server play 0-5 trailers before an unwatched movie. It looks like this has to be enabled on every "supported device" individually and I was hoping PlexConnect could also provide that functionality eventually.

It seems (and seemed to me, at first) to be kind of a silly feature, but the more I think about it, the more appealing it becomes. It's definitely just eye candy, but it adds to the home-theater-ness of having a media server.

I don't know much about development (especially in Python), but if there is anything I could do to help, I would be happy to contribute.

**Comment by moodyblue** [comment]
Closed due to inactivity.
