### ISSUE TITLE
ERROR 404: Not found http://trailers.apple.com/trailers.cer

### ISSUE THREAD

**Issue by bethnull** [iBaa/PlexConnect#277]
Hi everybody!

Has someone noticed that the certificate is no longer available? Or maybe I'm missing something??.

I had my setup working fine last week and now that I've moved to a new house the appletv is not able to add the profile nor the certificate. So I was thinking in installing the certificate via the usb method, however I'm not able to download the certificate.

Any idea or suggestion? 

Thanks in advance.

**Comment by indapublic** [comment]
I have same issue, I guees. http://trailers.apple.com/trailers.cer returns 404, so "adding profile" on ATV is freezing. Tried "MyPlexIP/trailers.cer" - not working also

**Comment by roidy** [comment]
First, have you generated the certificate files and place them in the correct directory, by following the appropriate Windows or Mac guide:-

Mac:- https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Mac-Certificates
Win:- https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Windows-Certificates

Second, PlexConnect needs to be running when you try to upload the certificate on the aTV, If you're still having problems please post all the information required from this link:-

https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue

Without more information it's impossible to know why it's not working.
