### ISSUE TITLE
Plexconnect process hangs and has to be re-started manually

### ISSUE THREAD

**Issue by hamishtaplin** [iBaa/PlexConnect#278]
Every so often Plexconnect will just hang and ATV get's stuck on 'Trailers is unavailable'. Running this:

`sudo launchctl unload /Library/LaunchDaemons/com.plex.plexconnect.bash.plist` 

doesn't solve it and I have to find the Python processes and kill them manually before restarting the server with:

`sudo launchctl load /Library/LaunchDaemons/com.plex.plexconnect.bash.plist`

The logs don't show anything at all, it just stops working.

This is running on OS X 10.8.5

**Comment by unity** [comment]
Experiencing the same issue here, even with a master branch from Jan. 11 - I resorted to using `screen` instead of a service so I could go, kill it and restart it... Hoping this'll get fixed.

**Comment by wahlmanj** [comment]
Are your PlexConnect Mac hosts wifi or Ethernet?

**Comment by jehanalvani** [comment]
I've had the same experience with both.

**Comment by unity** [comment]
Mac is wired, hosts the PMS too, and when the process hangs, only a `kill -KILL` will kill it.

**Comment by hamishtaplin** [comment]
Is there any further info I can give regarding this. It drives my family mad as it happens almost every day and I'm the only one who knows how to fix it!

**Comment by Rycochet** [comment]
I *think* I've had this happen on a QNAP occasionally - if so then it seems related to attempting to get a listing (or similar) from Plex itself that takes too long (ie the By Folder list in either TV or Movies - I've got a huge library), and hitting the menu button before it finishes displaying. Can't get it to happen very often, but this is almost always the way it goes.

Updated my Plex server itself (to 0.9.11.16 from a somewhat older version) a couple of days ago - listings have sped up and not seen it get stuck since.

**Comment by aegzorz** [comment]
I'm experiencing the same issue on my setup. Using the mac as a dns server instead of using the built-in dns. Once or twice a day it hangs like this, and I believe it all started after updating the apple tv to iOS 7.

PMS and PlexConnect running on a 10.6.8 mac mini.

**Comment by aegzorz** [comment]
I've sampled the process when it hangs:
https://gist.github.com/aegzorz/30ec69478ea59b3e3fc3

Looks like it's deadlocked or something. Not sure how to debug more thoroughly, any help would be much appreciated!

**Comment by ptz0n** [comment]
I seem to have the same issue with my (OS X) server. How can I contribute? Logs/traces?

**Comment by sbussetti** [comment]
Same issue here... consistently.  Is there a verbosity level setting for the logs?  Any way to enable debug logging?

**Comment by arijbrown** [comment]
I have the same symptoms (same error, same frequency) but I'm running PlexConnect on Windows.  Restarting the service fixes the problem, but sometimes I have to do it multiple times a day.  I'd love some help on how to troubleshoot.

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
