### ISSUE TITLE
Plex API URL exception needs a bit more detail

### ISSUE THREAD

**Issue by joshka** [iBaa/PlexConnect#283]
Hi,

I don't have an AppleTv to test the following suggestions, but I think they'd help future problem diagnosis of a similar form.

A user raised a problem at https://forums.plex.tv/index.php/topic/31308-new-plug-in-soundcloud/page-3#entry762561 but the PlexConnect log doesn't contain quite enough info by default to diagnose further.

In https://github.com/iBaa/PlexConnect/blob/master/PlexAPI.py#L355 When you catch a URLError exception, if it has a code, it most likely also has a reason, so the elif should I think be an if (at least according to my reading of https://docs.python.org/2/library/urllib2.html#urllib2.URLError and https://docs.python.org/2/library/urllib2.html#urllib2.HTTPError).

Secondly, if an error occurs it's important to log the url that caused it, currently this is logged at level 1 instead of level 0. Logging this info in the exception handler block even if it repeats the info logging would have assisted in diagnosing the issue mentioned above a little easier (without having to get the user to bump the log level up)

**Comment by moodyblue** [comment]
Thanks for your suggestion. As @iBaa did not implement it, and I think that now it's too late to do it, I'm going to close it.
