### ISSUE TITLE
FLAC media type not displaying track length while playing, progress bar not working

### ISSUE THREAD

**Issue by MartyAtkins** [iBaa/PlexConnect#298]
FLAC music tracks show the track length (duration) in the album list view. However, when a single track is selected to start play, the track being played with cover art shows all zeroes for the track length. Because of this, the progress bar doesn't function properly.

This doesn't appear to happen with other file types (wmas, mp3s). This also doesn't happen with any other Plex Media Player (web app, iOS apps).

The FLAC files, as well as other file types (wmas, mp3s) audible play just fine in PlexConnect. This is purely a display issue.

I've confirmed that these FLAC files do indeed have length populated in their metadata as can be viewed in the Windows Explorer file properties > details view. These files were created with dbpoweramp, a very reputable cd ripper.

Plex Media Server and PlexConnect is running on a Windows Enterprise box. PlexConnect (version .4) is running as a Windows Service.

**Comment by moodyblue** [comment]
Still an issue ?

**Comment by moodyblue** [comment]
Closed due to inactivity.

**Comment by ElleshaHackett** [comment]
This is still an issue. Can we fix this somehow?

**Comment by moodyblue** [comment]
Dup of #538
