### ISSUE TITLE
Using PlexConnect with Apache Reverse Proxy and virtual hosts give exception in PlexConnect

### ISSUE THREAD

**Issue by maronsen** [iBaa/PlexConnect#307]
It is functioning like it should but would be nice to get this fixed.
Have tried without reverse proxy and with reverse proxy and its only when on reverse proxy this exception happens.

**Comment by maronsen** [comment]
Hi, i have tried to find out where error/HTTP_NOT_FOUND.html.var was comming from and it looks like it is comming from my xampp apache reverse proxy here is the logs from it, hope you se something i dont because i have tried putting in httpd.conf
SetEnv force-proxy-request-1.0
SetEnv proxy-nokeepalive 1
SetEnv proxy-initial-not-pooled 1
 
[Tue Jan 13 23:06:23.368872 2015] [proxy_http:error] [pid 1608:tid 1724] (20014)Internal error: [client 192.168.1.110:55637] AH01102: error reading status line from remote server 192.168.1.50:8080
[Tue Jan 13 23:06:23.368872 2015] [proxy:error] [pid 1608:tid 1724] [client 192.168.1.110:55637] AH00898: Error reading from remote server returned by /error/HTTP_NOT_FOUND.html.var

ip 192.168.1.110 is the apple tv and 192.168.1.50 is the server running reverse proxy and plexconnect.

**Comment by maronsen** [comment]
Ok, its  been a while but i have fixed the issue i was having, it had to do with apache proxy configuration.
I disabled the apache web server from decoding the request sent to it from atv, and just passed it on to PlexConnect.

**Comment by maronsen** [comment]
resolved #307

**Comment by maronsen** [comment]
close #307

**Comment by iBaa** [comment]
Thanks for coming back and closing the issue. :-D
