### ISSUE TITLE
No subtitle formatting.

### ISSUE THREAD

**Issue by Baswazz** [iBaa/PlexConnect#312]
I don't see any formatting (italics) with .srt subtitles.
I don't have this problem with other plex clients like Chromecast, Rasplex or Plexbmc.
Is it possible to fix this?

srt example:
175
00:21:53,522 --> 00:21:56,566
<i>Maar goed, de droom gaat verder.</i>

**Comment by iBaa** [comment]
You got to check with Apple... I haven't found a way to switch the text overlay to italics, though you should see normal & bold.
I don't know about the other clients - do they subtitles on their own? If you are fine with PMS burning the subtitle into the video stream (aka full blown transcode) you can always switch the subtitle setting to "iOS, PMS", basically disabling the PlexConnect internal renderer.
