### ISSUE TITLE
Suggestion: Disable remote PMS to show up in shared libraries 

### ISSUE THREAD

**Issue by TribuneX** [iBaa/PlexConnect#315]
Could you add a setting to keep the shared library section from showing remote PMS? 
My situation:
I have one PMS at home and one at a remote location. Unfortunately neither of them has enough upload speed for a sufficient remote streaming. Nevertheless I am using the same myplex accounts on both servers. I need the myplex logins in order to keep some libraries hidden from my children. Would it be possible to easily add such an setting to the Settings.cfg?

**Comment by iBaa** [comment]
It's there already, isn't it?
From ATVSettings: ```    'sharedlibrariesview'       :('List', 'Grid', 'Bookcase', 'Hide'), \```
Set it to ```hide``` in aTV->PlexConnect->Settings->Main Nav Bar-> (or similar)

**Comment by TribuneX** [comment]
Yeah, but this options hides the complete menu for shared libraries. But since I enabled that only logged in users can access the local PMS, my local libraries show up there. But I only want to see the local libraries and would like to be able to hide the remote libraries listed as shared libraries.

**Comment by iBaa** [comment]
I guess I don't understand...
>But since I enabled that only logged in users can access the local PMS, my local libraries show up there.

The initial tab isn't "local library", but "own library". I don't get why your sections wouldn't appear there, provided you are logged in with the same ID on aTV that published the PMS.
Anyways - that would lead to the same issue: local and remote libraries in one spot, just a different one.

I really don't know what a setting should select, or how a that option should work. And honestly I am a bit resistant on adding special setting for exactly one user. :-D

But then, here is a list of things that might help:
- creating a second/third plex ID, a special one for each aTV and share your servers/sections according to their location.
- in asserts/templates/PlexConnect.xml change ```:/PMS(owned)/library/sections``` to ```:/PMS(local)/library/sections``` as well as ```:/PMS(shared)...``` to ```:/PMS(remote)```. You could also change the ```<title>``` to something like "local" vs "remote" - and then hide the shared/remote tab. I am not 100% sure if this would work as expected (long time no testing...) but the provisions for it are in PlexAPI.py/getXMLFromMultiplePMS().
- wait for Plex/Home support... (no, I don't give a date)

**Comment by TribuneX** [comment]
Thanks for the hints. I am gonna try to look into it to customize it to my needs. 
Just for completeness:
I have for each ATV a different myplex account and for the PMS a central account to give the other myplex accounts rights for accessing specific libraries. Therefore the local PMS only shows up at shared libraries. 

Yeah I fully agree, if no one else feels the need for such a feature there is no need to implement it!

**Comment by iBaa** [comment]
Unique accounts for each aTV? Then you should easily be able to un-share the particular remote PMS...
