### ISSUE TITLE
Suggestion: Add Shuffle For TV Shows

### ISSUE THREAD

**Issue by reeves122** [iBaa/PlexConnect#318]
Would it be possible to add shuffle functionality for TV shows, similar to how it is implemented for music? For example, if you are viewing the list of episodes for a TV show, the could be the option at the top to shuffle all episodes.

**Comment by wahlmanj** [comment]
This already works I have been shuffling shows for quite a while.

**Comment by reeves122** [comment]
Thanks for the info. I may have been missing the option. Could you please tell me how you shuffle TV shows using PlexConnect?
I usually shuffle shows using the Plex app on my phone but it would be awesome if I could do it from PlexConnect instead. Thank you!

**Comment by wahlmanj** [comment]
Add a playlist in PMS and then under the playlist tab you can play shows/movies/etc.

**Comment by reeves122** [comment]
Oh okay thanks. I wasn't sure if there were a way to shuffle TV shows without using a playlist that I didn't know about. Thanks!!

**Comment by wahlmanj** [comment]
I made a way in my dev theme to shuffle without playlists if your still interested:

https://github.com/wahlmanj3/PlexConnect/commit/cf13d5e9f781bb10f86d388b729608a1aa81c982

**Comment by sharpie00** [comment]
hi wahlmanj,

I copied the xml script from both the Episode_List.xml and Episode_List_Fanart.xml files from your link.  I now see the Shuffle option when I select a TV show.  However, when I select it, it's not shuffling. The show still starts with Episode 1.  Any suggestions? Thanks.

**Comment by wahlmanj** [comment]
I'm not sure it works for me. You can try my fork if you like using that link.
