### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by nmajin** [iBaa/PlexConnect#319]
Could totally be a screwed up install, but any idea what could cause this?

![](http://i.imgur.com/xZ5sfB4.jpg)

Note: I censored out my public IP

**Comment by nmajin** [comment]
p.s. This is on a jailbroken atv2 and everything appears to work fine but when I go to playback media I get this error.

**Comment by roidy** [comment]
Umm... jailbroken atv2, what firmware?

**Comment by wahlmanj** [comment]
I have seen a similar validation issue on iOS 5.3 when my aTV was outside my local network when viewing playlists. I will try to get a log next time I get a chance to visit my buddy. Seems to be within your local network so I'm wondering if the issues are unrelated besides the badges/playlist obvious differences.

**Comment by nmajin** [comment]
Yea jailbroken atv2 5.3 firmware. I actually had plexconnect working before through a .deb install, but had issues updating with git and reinstalled it and now running into this issue.

**Comment by roidy** [comment]
Firmware 5.3 doesn't support the media badges and PlexConnect checks and removes them on that firmware, so are you using the official version or have the xml files been modified?

**Comment by nmajin** [comment]
I was trying to install Option B, but that didn't work, kept getting an error about Plex not being able to connect: https://github.com/iBaa/PlexConnect/tree/master/support/aTV_jailbreak

I uninstalled this and then went with the install mentioned in this post (#231), since that worked once before for me, but now I'm getting the validation error: https://forums.plex.tv/index.php/topic/88905-plexconnect-on-atv2jailbroken-launchctl/page-12

**Comment by roidy** [comment]
Ok, I've got no experience with installing PlexConnect directly onto an aTV... however that version you link to (#231) is very old and doesn't even have media badge support.... so are you sure you haven't got a mix of older and newer files installed at the same time?

**Comment by wahlmanj** [comment]
Post 231 and the newest method based on baa's original method that I simplified to use only ssh always grabs the latest commit since they both git clone the latest version directly upon the aTV2.

**Comment by roidy** [comment]
Download the following PrePlay.xml file:-

http://www25.zippyshare.com/v/aVshrYY4/file.html

And place it in the assets/templates/Movie directory of your PlexConnect installation and see if selecting a movie then works.

**Comment by nmajin** [comment]
Still getting the same error

**Comment by roidy** [comment]
Ok, I'll need a full high level log file to have a look at please.

**Comment by nmajin** [comment]
This is all that is in the PlexConnect.log, even with replicating the issue:

12:14:24 PlexConnect: started: 12:14:24
12:14:24 PlexConnect: Version: 0.5-dev
12:14:24 PlexConnect: Python: 2.7.3 (default, Aug 11 2012, 10:54:38) 
[GCC 4.2.1 Compatible Apple Clang 3.0 (tags/Apple/clang-211.11)]
12:14:24 PlexConnect: Host OS: darwin
12:14:24 PlexConnect: PILBackgrounds: Is PIL installed? False
12:14:24 PlexConnect: IP_self (from settings): 127.0.0.1
12:14:24 WebServer: started: 12:14:24
12:14:24 WebServer: ***
12:14:24 WebServer: WebServer: Serving HTTP on 127.0.0.1 port 80.
12:14:24 WebServer: ***
13:03:45 PlexAPI: ***
13:03:45 PlexAPI: looking up Plex Media Server
13:03:45 PlexAPI: ***
13:03:46 PlexAPI: GDM: Servers discovered: 1
13:03:47 PlexAPI: Servers (local, plex.tv, MyPlex): 4

**Comment by wahlmanj** [comment]
You need to set the Settings.cfg file to High then restart PlexConnect and  try to replicate the issue. Also you can post the file on a site like pastebin or similar to host your log file then just copy the url back to here so he can look at it.

**Comment by nmajin** [comment]
http://pastebin.com/U6nM802Q

Note: I have my aTV version spoofed to 6.5, but it really is 5.3. What is in the log attached is what happened right before I went to play the movie. I took out everything else that was private or wasn't relative to the error I am seeing.

**Comment by roidy** [comment]
>I have my aTV version spoofed to 6.5, but it really is 5.3.

Well after that detail I don't need to see the log, your problem is clear :( 

Plexconnect thinks the aTV is firmware 6.5 and tries to use the media badges but the aTV is really only 5.3 and doesn't support them.... Fail.

Sorry nothing I can do about that.
