### ISSUE TITLE
Trailers is unavaible. Please try again later

### ISSUE THREAD

**Issue by djrobbieh** [iBaa/PlexConnect#320]
Thanks for a very good and informative program. I am running a computer with UBUNTU 14.04
 
I have an Apple TV (latest version both hardware and firmware) that is causing my already short hair to fall off even faster & more. I am soon bald!
 
The reason for this is simply " Whatever i do , i still get the message "Trailer is unavailable. Please try again later" message when pressing the Trailers app in my Apple TV.
 
I have tried nearly everything. I have read forum topics, guides, videos from 2013 , but nothing seams to help me.
 
Her is what i have done.
 
Created the SERTIFICATE FILES (trailers.cer - trailers.key - trailers.pem)
 
Installed the PLEXCONNECT
 
git clone https://github.com/i...PlexConnect.git
cd PlexConnect/
git pull 
 
 
Placed the 3 certificate files inside the folder /home/robert/PlexConnect/assets/certificates
 
Also added the 192.168.1.94/trailers.cer inside my APPLE TV - MENU - Send Data To APPLE play button procedure.
 
Then:
 
sudo ./PlexConnect.py
 
 
This resulting in PLEXCONNECT running fine. Then tried to open the Trailers APP on my Apple TV. resulting in, guess what? Trailers is unavaible. Please try again later
 
What am I doing wrong?
 
Quote
 
 
Your ATV model (2 or 3) and firmware version (found under the ATV settings > general > about > Apple TV software): ATV 3  & 7.0.3 6917
The DNS server set on the ATV (found under the ATV settings > general > network > DNS): 192.168.1.94
The local IP address of the device that PlexConnect is installed on: 192.168.1.94
The device and operating system (including version number) that PlexConnect is installed on: PC & UBUNTU 14.04
The device and operating system (including version number) that the Plex media server (PMS) is installed on: PC & UBUNTU 14.04
The Plex media server (PMS) version number you are running (do not put 'latest'): 
Version 2.3.15
The local IP address of the device that the Plex media server (PMS) is installed on: 192.168.1.94
The PlexConnect version number. If using Github source then a time and date of download (look at the creation date of the folder) and if you are using any non-standard setup e.g. Plexify or a fork. Version: 0.5-dev
The contents of your 'Settings.cfg' file (this is created at first clean shutdown of PlexConnect, using CTR+c) See Below
Detail on the media file if it is an issue related to playing a media file (in order to get the necessary information on a particular media file go into the Plex web interface, select the video file, when it brings up the page for the media file click on the "i" information button on the left hand side, it will then bring up a "media info" box, click on the "View XML" button, it will then open a browser window with the relevant information, copy this to http://www.pastebin.com and use the pastebin link to post the details; posting the information directly in the forum may mess up the formatting and generally takes up a lot of space):
A detailed description of the issue (the clearer you can make this the better):
Ensure you post your 'PlexConnect.log' file to pastebin and post the link ('PlexConnect.log' is located in your PlexConnect folder). If possible, follow these steps to create a "more detailed fresh" one:

shutdown PlexConnect
in 'Settings.cfg', set loglevel to "High" (note the capital 'H')
delete the existing log file
restart PlexConnect
repeat the issue
immediately close PlexConnect and post the log.
in 'Settings.cfg', set the loglevel back to "Normal"
[PlexConnect]
enable_plexgdm = True
ip_pms = 192.168.178.10
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = High
logpath = .

Here is the output from the Terminal. 

root@Server:/home/robert/PlexConnect# sudo ./PlexConnect.py
20:40:04 PlexConnect: ***
20:40:04 PlexConnect: PlexConnect
20:40:04 PlexConnect: Press CTRL-C to shut down.
20:40:04 PlexConnect: ***
20:40:04 PlexConnect: started: 20:40:04
20:40:04 PlexConnect: Version: 0.5-dev
20:40:04 PlexConnect: Python: 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
20:40:04 PlexConnect: Host OS: linux2
20:40:04 PlexConnect: PILBackgrounds: Is PIL installed? True
20:40:04 PlexConnect: IP_self: 192.168.1.94
20:40:04 DNSServer: started: 20:40:04
20:40:04 DNSServer: ***
20:40:04 DNSServer: DNSServer: Serving DNS on 192.168.1.94 port 53.
20:40:04 DNSServer: intercept: ['trailers.apple.com'] => 192.168.1.94
20:40:04 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
20:40:04 DNSServer: forward other to higher level DNS: 8.8.8.8
20:40:04 DNSServer: ***
20:40:04 WebServer: started: 20:40:04
20:40:04 WebServer: ***
20:40:04 WebServer: WebServer: Serving HTTP on 192.168.1.94 port 80.
20:40:04 WebServer: ***
20:40:04 WebServer: started: 20:40:04
20:40:04 WebServer: ***
20:40:04 WebServer: WebServer: Serving HTTPS on 192.168.1.94 port 443.
20:40:04 WebServer: ***
20:41:23 DNSServer: DNS request received!
20:41:23 DNSServer: Source: ('192.168.1.123', 59966)
20:41:23 DNSServer: Domain: trailers.apple.com
20:41:23 DNSServer: ***intercept request
20:41:23 DNSServer: -> DNS response: 192.168.1.94

**Comment by iBaa** [comment]
see forum: https://forums.plex.tv/index.php/topic/145336-trailers-is-unavaible-please-try-again-later/

**Comment by thomassampson** [comment]
Hi All

I spent a whole day trying to fix this issue and I finally found a solution which worked. I tried to post something on the Plex Forum but was unable to so this was the next best thing. 

As I could not find an actual solution I thought I would post this somewhere for people to see.

I am using Windows 7 64bit and this is the solution to the issue:

1) Delete the certificates from the Apple TV
2) Stop the PlexConnect and delete the Folder from your computer
3) Redownload PlexConnect from GitHub and and extract to the desired location
4) Regenerate the certificates in Command Prompt and once done copy them into the default location for them in PlexConnect folder. (c:/[pathtoplex]/assets/certificates/).
4) Open PlexConnect.py to generate the settings file
5) Ensure the pms_ip is correct in the settings file, it needs to be the IP of the computer Plex is running on. Don't change any other settings.
6) Install certificate on AppleTV using http://trailers.appletv.com/trailers.cer
7) Open Trailers app on AppleTV and it should all be working.

Hopefully this will work for everyone but no promises, any questions please ask.

Thanks
Sampson

**Comment by Rycochet** [comment]
There's a full set of pages on the wiki including all instructions on generating certificates for each of the main operating systems - https://github.com/iBaa/PlexConnect/wiki/Install-Guide
