### ISSUE TITLE
PlexConnect fails with custom scanner S-Babs or BABS

### ISSUE THREAD

**Issue by moxz** [iBaa/PlexConnect#321]
Hi.
My anime series are using custom scanner S-Babs and it has stopped working with Plexconnect only. 
When I try to enter the Anime section i get an 404 error stating 

http://localhost/PMS(PMSServeraddress:32400)/library/sections/10?PlexConnect=S_-_BABS
Can't connect to localhost

The Plexconnect Log does not state anything when trying to enter the Anime setion.
When entering a working section like Cartoons it says
12:15:55 XMLConverter: Section scanner found, updating command.

I am running latest commit 
Apple-TV:/Applications/PlexConnect/.git root# git log
commit d16d437e7814a50d6d607436c16fcf8f05ab8004
Author: roidy
Date:   Thu Feb 5 14:27:23 2015 +0000

    1.0 (mono) badge

I have an older version of Plexconnect where my Anime still works. With a commit dated Oct 22.
Apple-TV:/Applications/PlexConnect_old root# git log
commit bd96af4d2c6ef338ce617c0ac23d1128d8db7f95
Author: roidy
Date:   Wed Oct 22 20:10:22 2014 +0100

    Keep Baa happy ;)

BR
Christian Svedin

**Comment by roidy** [comment]
Please web browser to the following address, replacing PMS_IP:PORT with you PMS IP address and port:-

http://PMS_IP:PORT/library/sections

and post the resulting xml.

**Comment by moxz** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<MediaContainer size="12" allowSync="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1420915278" title1="Plex Library">
<Directory allowSync="0" art="/:/resources/show-fanart.jpg" composite="/library/sections/10/composite/1423255816" filters="1" refreshing="0" thumb="/:/resources/show.png" key="10" type="show" title="Anime" agent="com.plexapp.agents.thetvdb" scanner="S - BABS" language="en" uuid="a4c1f896-05ae-4c1a-b3a3-9c8537e649c2" updatedAt="1423255816" createdAt="1410187822">
<Location id="16" path="/home/yakumo/Archive/Video/Anime/Downloaded"/>
<Location id="37" path="/home/yakumo/Archive/Video/Anime/OwnRips"/>
</Directory>
<Directory allowSync="0" art="/:/resources/show-fanart.jpg" composite="/library/sections/12/composite/1423255818" filters="1" refreshing="0" thumb="/:/resources/show.png" key="12" type="show" title="Cartoons" agent="com.plexapp.agents.thetvdb" scanner="Plex Series Scanner" language="en" uuid="760bfa09-a101-4e6f-a726-ed4dd4b53abf" updatedAt="1423255818" createdAt="1410199651">
<Location id="24" path="/home/yakumo/Archive/Video/Cartoons/Downloaded"/>
<Location id="25" path="/home/yakumo/Archive/Video/Cartoons/OwnRips"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/11/composite/1423255819" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="11" type="movie" title="Filmer" agent="com.plexapp.agents.themoviedb" scanner="Plex Movie Scanner" language="en" uuid="d21cbea8-02f8-4fb6-af28-b08ecc72607b" updatedAt="1423255819" createdAt="1410199561">
<Location id="17" path="/home/yakumo/Archive/Video/Movies/Downloaded/EngSub"/>
<Location id="18" path="/home/yakumo/Archive/Video/Movies/Downloaded/NoSub"/>
<Location id="19" path="/home/yakumo/Archive/Video/Movies/Downloaded/SweSub"/>
<Location id="20" path="/home/yakumo/Archive/Video/Movies/Downloaded/Kolla igenom"/>
<Location id="21" path="/home/yakumo/Archive/Video/Movies/Ownrips/EngSub"/>
<Location id="22" path="/home/yakumo/Archive/Video/Movies/Ownrips/NoSub"/>
<Location id="23" path="/home/yakumo/Archive/Video/Movies/Ownrips/SweSub"/>
<Location id="39" path="/home/yakumo/Archive/Video/Movies/Downloaded/couch"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/21/composite/1423256247" filters="1" refreshing="0" thumb="/:/resources/video.png" key="21" type="movie" title="Home Videos" agent="com.plexapp.agents.none" scanner="Plex Video Files Scanner" language="xn" uuid="99f94fc1-45c7-42e6-a64f-e558264d60ff" updatedAt="1423256247" createdAt="1416492517">
<Location id="38" path="/home/yakumo/Archive/Video/Phantom"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/13/composite/1423256247" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="13" type="movie" title="Music" agent="com.plexapp.agents.themoviedb" scanner="Plex Movie Scanner" language="en" uuid="309764ef-111d-465e-8c18-69ab87bffa59" updatedAt="1423256247" createdAt="1410199689">
<Location id="26" path="/home/yakumo/Archive/Video/Music"/>
</Directory>
<Directory allowSync="0" art="/:/resources/show-fanart.jpg" composite="/library/sections/9/composite/1423249021" filters="1" refreshing="0" thumb="/:/resources/show.png" key="9" type="show" title="Serier" agent="com.plexapp.agents.thetvdb" scanner="Plex Series Scanner" language="sv" uuid="7484e149-36c4-4b23-a153-f6b1439a97a1" updatedAt="1423249021" createdAt="1410186335">
<Location id="14" path="/home/yakumo/Archive/Video/Series/Downloaded"/>
<Location id="15" path="/home/yakumo/Archive/Video/Series/Own Rips"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/19/composite/1423249033" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="19" type="movie" title="Serietidnings Filmer" agent="com.plexapp.agents.themoviedb" scanner="Plex Movie Scanner" language="en" uuid="3200c934-e423-44f0-8600-f6e913315977" updatedAt="1423249033" createdAt="1410203684">
<Location id="34" path="/home/yakumo/Archive/Video/Movies/Comic Movies/Downloaded"/>
<Location id="35" path="/home/yakumo/Archive/Video/Movies/Comic Movies/Ownrips"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/14/composite/1423250216" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="14" type="movie" title="Standup" agent="com.plexapp.agents.themoviedb" scanner="Plex Movie Scanner" language="sv" uuid="041ba1ec-a738-4de1-87c8-605583845aa0" updatedAt="1423250216" createdAt="1410199747">
<Location id="27" path="/home/yakumo/Archive/Video/Movies/Standup/OwnRips"/>
<Location id="28" path="/home/yakumo/Archive/Video/Movies/Standup/Downloaded"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/7/composite/1423251008" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="7" type="movie" title="Svenska Filmer" agent="com.plexapp.agents.themoviedb" scanner="Plex Movie Scanner" language="sv" uuid="e6c80da7-fbb0-44e5-9c08-65b805bd990e" updatedAt="1423251008" createdAt="1410179143">
<Location id="11" path="/home/yakumo/Archive/Video/Movies/Downloaded/Swedish"/>
<Location id="12" path="/home/yakumo/Archive/Video/Movies/Ownrips/Swedish"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/16/composite/1423251408" filters="1" refreshing="0" thumb="/:/resources/movie.png" key="16" type="movie" title="Tecknat" agent="com.plexapp.agents.themoviedb" scanner="Plex Movie Scanner" language="sv" uuid="4fe49333-b29a-4cf8-849c-26f458d28ee0" updatedAt="1423251408" createdAt="1410199877">
<Location id="30" path="/home/yakumo/Archive/Video/Movies/Cartoons/Ownrips"/>
<Location id="31" path="/home/yakumo/Archive/Video/Movies/Cartoons/Downloaded"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/18/composite/1423250215" filters="1" refreshing="0" thumb="/:/resources/video.png" key="18" type="movie" title="Träning" agent="com.plexapp.agents.none" scanner="Plex Video Files Scanner" language="xn" uuid="39adea65-4f83-47f9-94e1-e98d0f2fc3b1" updatedAt="1423250215" createdAt="1410199965">
<Location id="33" path="/home/yakumo/Archive/Video/Training"/>
</Directory>
<Directory allowSync="0" art="/:/resources/movie-fanart.jpg" composite="/library/sections/20/composite/1423250216" filters="1" refreshing="0" thumb="/:/resources/video.png" key="20" type="movie" title="Wrestling" agent="com.plexapp.agents.none" scanner="Plex Video Files Scanner" language="xn" uuid="e5847e34-8536-4d34-ba3b-5807d0dbe2f4" updatedAt="1423250216" createdAt="1410205259">
<Location id="36" path="/home/yakumo/Archive/Video/Wrestling"/>
</Directory>
</MediaContainer>

**Comment by roidy** [comment]
Ok, I don't have S-BABS scanner to test with but try the following XMLConverter.py:- 

http://www26.zippyshare.com/v/ju6VltIz/file.html

Download it and replace the original XMLConverter.py file in your PlexConnect install, you'll need to shutdown PlexConnect before replacing the file. Let me know if it fixes the problem and if it does I'll commit the changes.

**Comment by moxz** [comment]
I would be happy to say it works now but I no =(

All sections dissapered and here is what the log is spiting out.
http://pastebin.com/qEEFBiGD

**Comment by roidy** [comment]
Ok, that error is nothing to do with the scanner, that's because your version of PlexConnect is too old for the new XMLConverter.py file to work with.

The XMLConverter.py file I posted will only work with the very latest version of PlexConnect. update and try again.

**Comment by moxz** [comment]
Did a new git pull and replaced the XMLConverter and we are back to square one.
http://localhost/PMS(PMSServeraddress:32400)/library/sections/10?PlexConnect=S_-_BABS
Can't connect to localhost

**Comment by roidy** [comment]
Ok, where can I get this "S-BABS" scanner so I can do some testing myself?

**Comment by CyberGhost84** [comment]
There u go ;

https://forums.plex.tv/index.php/topic/109441-series-better-absolute-scanner-s-babs/

**Comment by roidy** [comment]
Umm... that just thread just gives you a single py file and tells you "To run this, you will need to follow the regular instruction for setting up a scanner" ????? I've got no idea how to do that, isn't there just a complete plug-in package?

Besides that I'm not even sure what the point of this scanner is?

**Comment by moxz** [comment]
Place S - BABS.py in 
On Linux.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scanners/Series/

This is a scanner used mainly for Anime that uses absolute ordering ie Name.123.mkv Instead of Season and episode number and then by putting an tvdb.id file next to your anime The scanner then transforms your anime episodeds to thetvdb season and ep releases in plex so it looks good =)

**Comment by roidy** [comment]
>On Linux.
 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scanners/Series/

I'm not on Linux :( But I'll give it a try.

>This is a scanner used mainly for Anime that uses absolute ordering ie Name.123.mkv Instead of Season and episode number and then by putting an tvdb.id file next to your anime The scanner then transforms your anime episodeds to thetvdb season and ep releases in plex so it looks good =)

Why would you not just name your Anime with the correct Season/Episode numbering to start with?

**Comment by roidy** [comment]
Ok, grab the latest commit and it should work now :D

**Comment by moxz** [comment]
Becuase almost no anime is released that way. 
Example [HorribleSubs] Naruto Shippuuden - 397 [720p].mkv
Examlple2 [yibis]_One_Piece_661_[720p][AE41095E].mkv

Almost always an anime series is just epnumber to end no seasons. And if there are "season" it is almost always a new series when they are released in its original form from Japan.
Example: Code Geass: Lelouch of the Rebellion (In us season1) , Code Geass: Lelouch of the Rebellion R2 (In us season2)

 
What Babs and S-Babs does is that they match the released absolute numbering with the info that is located on thetvdb that are sorted by US television standards more or less.

BTW when setting up the scanner you have select in the PMS web insterface for the whole "Anime Section"

A Anime Demo Archive containing some dummy files for testing
http://yakumo.se/PMS/Anime.zip

**Comment by moxz** [comment]
It works with latest commit.
Thank you !! =)
