### ISSUE TITLE
Plexconnect not connecting to PMS: Unauthorised 

### ISSUE THREAD

**Issue by kanthamohan** [iBaa/PlexConnect#323]
I use a Freenas setup at home with Plex Media Server and PlexConnect running on two separate jails. 

I have setup  plexconnect to access the PMS from my AppleTV3 (all install instructions followed).  I am able to see the plexconnect interface when accessing the Trailers app however there is no PMS discovered by plexconnect both using the plexgdm option and  hardcoded in  Settings.cfg.  The PlexConnect log shows a message We are unable to reach a server.  Reason Unauthorised. 

I am able to access my PMS from other clients i.e browsers across my home but not from the apple TV. Had exhausted all options and now turning to the git community for help. 

Please help me resolve this, happy to provide any supporting log/info needed (just ask)

**Comment by Drewbie1974** [comment]
Git is used for code enhancements/bugs, this should be raised on the forum. https://forums.plex.tv/index.php/forum/136-appletv-plexconnect/ with all the info from the How to Report an Issue section of the WIKI https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue

**Comment by kmaslam** [comment]
The PlexConnect log shows a message We are unable to reach a server. Reason Unauthorised.

Just to be sure... did you get the certificate installed on ATV?

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
