### ISSUE TITLE
Cannot play mkv files

### ISSUE THREAD

**Issue by pascalgoty** [iBaa/PlexConnect#324]
PlexConnect plays without problems mp4 (AVC1) files but fails to play mkv with the same codec.. My aTV is returning "An error occurred loading this content. Try again later"

Here's some info of my installation :
OS: OpenSuse 13.2 64-bit Kernel 3.16.7-7
Python 2.7.8
Plex Server : Version 0.9.11.7

Running the latest version of PlexConnect
git show : 
commit bba21a4af30d9c4168f95ab60ee76f74334f5222
Author: roidy <roidy.parnell@ntlworld.com>
Date:   Sun Feb 8 16:30:05 2015 +0000

My ATVSettings.cfg
[DEFAULT]
plexhome_enable = False
sharedlibrariesview = List
showsynopsis = Hide
movies_navbar_decades = checked
showplayerclock = True
tvshowfanart = Hide
tv_navbar_unwatched = checked
movies_navbar_directors = checked
movies_navbar_ondeck = checked
subtitlesize = 100
transcoderaction = Auto
homevideos_navbar_byfolder = checked
tv_navbar_genres = checked
durationformat = Hours/Minutes
tv_navbar_more = checked
homevideoview = Grid
music_navbar_more = checked
homevideos_navbar_genres = checked
phototranscoderaction = Auto
showtitles_homevideos = Highlighted Only
movies_navbar_more = checked
homevideos_navbar_unwatched = checked
subtitlerenderer = Auto
music_navbar_decade = checked
overscanadjust = 0
showview = List
movieview = Grid
movies_navbar_unwatched = checked
plexhome_auth =
playlistsview = List
movies_navbar_byfolder = checked
showtitles_tvshows = Highlighted Only
showendtime = True
channelview = List
flattenseason = False
tv_navbar_ondeck = checked
moviepreplay_bottomshelf = Extras
homevideos_navbar_ondeck = checked
plexhome_user =
movies_navbar_collections = checked
transcodequality = 1080p 40.0Mbps
showtitles_channels = Highlighted Only
showtitles_movies = Highlighted Only
seasonview = List
myplex_auth =
movies_navbar_actors = checked
showunwatched = True
music_navbar_year = checked
clockposition = Center
myplex_user =
music_navbar_recentlyadded = checked
remotebitrate = 720p 3.0Mbps
homevideos_navbar_collections = checked
music_navbar_genre = checked
libraryview = List
fanart_blur = 0
audioboost = 100
timeformat = 24 Hour
moviefanart = Hide
actorview = Movies
movies_navbar_genres = checked

[F0TNLH25FF54]
moviefanart = Hide
tvshowfanart = Hide
transcoderaction = Auto

-----

The Output i get from PlexConnect Server side (that's from the first to the last line after starting the video)

19:49:22 WebServer: serving .xml: /library/metadata/12694
19:49:23 WebServer: serving subtitle: /library/streams/41817
19:49:23 Subtitle: subtitle URL: http://192.168.0.10:32400/library/streams/41817?encoding=utf-8
19:49:23 Subtitle: xargs: {'X-Plex-Token': ''}
Content-Length: 44436
Content-Type: text/html
Connection: close
X-Plex-Protocol: 1.0
Cache-Control: no-cache

19:49:24 Subtitle: ====== received Subtitle ======
19:49:24 Subtitle: ?1
00:00:00,001 --> 00:00:02,001
Cubbies

2
00:00:02,002 --> 00:00:04,937
<font color="#80ff80">sync and correction by solfieri
www.addic7ed.com</font>

3
00:00:06,511 --> 00:00:09,213
I'm gonna be perfectly
candid with you,  [...]
19:49:24 Subtitle: ====== Subtitle finished ======
19:49:24 Subtitle: ====== generated subtitle aTV subtitle JSON ======
19:49:24 Subtitle: {"Timestamp": [{"time": 0}, {"Line": [{"text": "Girls - S04E04"}, {"text": "Cubbies"}], "time": 1}, {"time": 2001}, {"Line": [{"text": "sync and correction by solfieri"}, {"text": "www.addic7ed.com"}], "time": 2002}, {"time": 4937}, {"Line": [{"text": "I' [...]
19:49:24 Subtitle: ====== aTV subtitle JSON finished ======

Thanks for you help and if you need any other output let me know.

**Comment by depraved22** [comment]
What's the media info file for the mkv look like? I personally use MKVs for everything and have had no issues with playing them.

**Comment by pascalgoty** [comment]
Hi had problems with almost every mkv .. I'm gonna try to change the container for mp4 to see if it's really a matters of codecs or containers.

Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L4.1
Format settings, CABAC : Yes
Format settings, ReFrames : 5 frames
Codec ID : V_MPEG4/ISO/AVC
Writing library : x264 core 140 r2377 1ca7bb9

here's a Avi that doesn't work too

Format : AVC
Format/Info : Advanced Video Codec
Format profile : Main@L3.0
Format settings, CABAC : Yes
Format settings, ReFrames : 4 frames
Codec ID : H264
Writing library : x264 core 125

**Comment by carlsteinhilber** [comment]
As you probably know, the AppleTV does not natively support MKV regardless of video or audio codecs. I've never been able to play MKV through PlexConnect, but my PMS is on a lower-powered NAS that won't do transcoding. Don't know if maybe you have the same situation, or otherwise have an underpowered PMS server that's incapable of keeping up with on-the-fly xcode of higher def MKV video? I have to Handbrake everything to M4V to play from my NAS. PITA, but...

**Comment by roidy** [comment]
> I have to Handbrake everything to M4V to play from my NAS. PITA, but... 

As long as the video contained in the mkv is h264, which most stuff is, then there is absolutely no need to Handbrake the file. A simple remux is more than enough. 

Here's some options:-

Sickbeard mp4 Automator (python, osx, win, linux) - https://github.com/mdhiggins/sickbeard_mp4_automator/

Subler (osx) - https://code.google.com/p/subler/

MkvToMp4 (windows) - http://www.videohelp.com/tools/MkvToMp4 

All of these option will create an aTV compliant m4v file with the necessary AAC and AC3 audio tracks, and because the video isn't being re-encoded it's really fast, only taking a few minutes.

**Comment by pascalgoty** [comment]
Here's the debug log of my PMS.

It's like PlexConnect is sending a stop request ?

Feb 14, 2015 15:12:21 [0x7f2a883fd700] DEBUG - Request: [192.168.0.20:53463] GET /video/:/transcode/universal/stop?session=F0TNLH25FF54 (5 live)

http://pastebin.com/bqkGqCUy

**Comment by depraved22** [comment]
My entire library is MKV files and they play without issue with 2 AppleTVs.

The AC3 is transcoded to AAC. The video is usually copied. 

From my plexwatch history:
Stream Details
Video
Stream Type: copy
Video Resolution: 808p
Video Codec: h264
Video Width: 1920
Video Height: 808
Audio
Stream Type: transcode
Audio Codec: ac3
Audio Channels: 6
Media Source Details
Container: mkv
Resolution: 1080p
Bitrate: 7676 kbps
Video Source Details
Width: 1920
Height: 808
Aspect Ratio: 2.35
Video Frame Rate: 24p
Video Codec: h264
Audio Source Details
Audio Codec: dts
Audio Channels: 6

**Comment by stablebetter** [comment]
In order to make Plex recognize MKV files, we had better convert MKV to Plex more supported video format. 

Here is just the step by step guide at http://www.idealshare.net/video-converter/plex-mkv-solution.html

**Comment by seccubus** [comment]
Does this properly deal with multi-language/multi subtitle support?

I prefer to watch feature length cartoons in their original laguage with Dutch subtitles, but my kids prefer them redubbed in Dutch.

Saving the movie twice, just because of this seems waistful.

Frank

**Comment by alaricjessie** [comment]
i had the same problem, and find this solution to play mkv on plex on google. http://www.ufushare.com/how-to-play-mkv-files-via-plex-successfully/

**Comment by justinpeterson13** [comment]
Just solved this problem by turning off "Dolby Digital" in settings. Hope this helps!

**Comment by tuofulearn** [comment]
I use Avdshare Video Converter to convert mkv to a more compatible format like mp4, mov
