### ISSUE TITLE
Windows Server 2012 R2 Not working

### ISSUE THREAD

**Issue by bfmramalho** [iBaa/PlexConnect#325]
Im trying to running PlexConnect on Windows Server 2012 R2, with already PMS installed and working.
When I run the PlexConnect.py with python I got the following error:
![screen shot 2015-02-11 at 23 17 46](https://cloud.githubusercontent.com/assets/5646901/6158656/815f78ec-b244-11e4-9d4e-7ec1a44a3d8a.png)

How can I fix this?

**Comment by carlsteinhilber** [comment]
By Python34, I'm guessing you're trying to run it under Python 3, which AFAIK isn't supported yet.

I think you need 2.7.

**Comment by iBaa** [comment]
Correct. Python 2.7.x it is... :-)
