### ISSUE TITLE
403 Whenever accessing server where openplex is installed...

### ISSUE THREAD

**Issue by Websteria** [iBaa/PlexConnect#326]
No idea what's wrong.. I installed from scratch. and web server shows this:

19:23:59 PlexConnect: started: 19:23:59
19:23:59 PlexConnect: Version: 0.5-dev
19:23:59 PlexConnect: Python: 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
19:23:59 PlexConnect: Host OS: darwin
19:23:59 PlexConnect: PILBackgrounds: Is PIL installed? True
19:23:59 PlexConnect: IP_self: 192.168.0.88
19:23:59 DNSServer: started: 19:23:59
19:23:59 DNSServer: ***
19:23:59 DNSServer: DNSServer: Serving DNS on 192.168.0.88 port 53.
19:23:59 WebServer: started: 19:23:59
19:23:59 DNSServer: ***
19:23:59 WebServer: ***
19:23:59 WebServer: WebServer: Serving HTTP on 192.168.0.88 port 80.
19:23:59 WebServer: ***
19:23:59 WebServer: started: 19:23:59
19:23:59 WebServer: ***
19:23:59 WebServer: WebServer: Serving HTTPS on 192.168.0.88 port 443.
19:23:59 WebServer: ***

**Comment by iBaa** [comment]
What is "openplex"?

Ok, kidding... :-D
PlexConnect does this by design ("403 - not serving...") - it only wants to talk to your AppleTV. If you need to run a WebServer in parallel, you need to move one of them to a different port, probably with portforwarding and stuff.
