### ISSUE TITLE
Unable to turn on Cert and Hijack autoloader.

### ISSUE THREAD

**Issue by Websteria** [iBaa/PlexConnect#327]
When I click on "Cert and Hijack Auto Loader" or any option on extras (v.42) nothing happens. I also can't figure out which bash scripts these are running or I would try to debug them.

Thanks.
Jeff

**Comment by iBaa** [comment]
PlexConnect? Looks like an issue with wahlman's OpenPlex, doesn't it?
->https://github.com/wahlmanj/OpenPlex
