### ISSUE TITLE
Subtitles SYNC

### ISSUE THREAD

**Issue by proyectabtl** [iBaa/PlexConnect#328]
Hi. I love plexconnect for atv.  Works great, only thing i miss is an option to manually sync the subtitles... 
Some times plex server download a correct but out of sync sub, and It would be easier to manually sync than search and re download a New sub, specially when comes to series. 
Any help or Info i'm exited to cooperate. 
Thanks.

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
