### ISSUE TITLE
Non-existing files referenced from code to assets folder.

### ISSUE THREAD

**Issue by bjornaelvoet** [iBaa/PlexConnect#330]
Some libraries cannot be shown on Apple TV. PlexConnect.log says:

21:42:35 WebServer: File Not Found:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/Applications/PlexConnect-master/XMLConverter.py", line 384, in XML_PMS2aTV
    aTVTree = etree.parse(sys.path[0]+'/assets/templates/'+XMLtemplate)
  File "<string>", line 56, in parse
  File "<string>", line 25, in parse
IOError: [Errno 2] No such file or directory: '/Applications/PlexConnect-master/assets/templates/Movies/NavigationBar.xml'

and also

17:44:47 WebServer: File Not Found:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/Applications/PlexConnect-master/XMLConverter.py", line 384, in XML_PMS2aTV
    aTVTree = etree.parse(sys.path[0]+'/assets/templates/'+XMLtemplate)
  File "<string>", line 56, in parse
  File "<string>", line 25, in parse
IOError: [Errno 2] No such file or directory: '/Applications/PlexConnect-master/assets/templates/TV/NavigationBar.xml'

Copying the assets/templates/Movie folder to assets/templates/Movies and assets/templates/TVShow to assets/templates/TV resolves the issue.

The better choice will off course be fixing the references in the python code.

**Comment by roidy** [comment]
Again see my answer to your other issue, looks like you've got a mixture of older and newer files. Try a complete fresh install.

**Comment by bjornaelvoet** [comment]
You are probably right, I always do a git pull to keep my generated certificates, but probably something is messed up with my install.

I will verify this evening on my Apple TV and close the issue if issue is solved with clean install.

**Comment by bjornaelvoet** [comment]
Doing a clean install and behaviour is still the same; so getting same log messages. Changed the log debugging to high and looking at the detailed log file now start to understand what is going wrong.

First of all, the plex library I am trying to access on the Apple TV is a library with my own written scanner called "EyeTV_TV_Scanner". Apparently there is some code in XMLConverter.py that does following:

    # Special case scanners
    if cmd=='S_-_BABS':
        dprint(__name__, 1, "Found S - BABS.")
        dir = 'TVShow'
        cmd = 'NavigationBar'
    elif cmd.find('Scanner') != -1:
        dprint(__name__, 1, "Found Scanner.")
        parts = cmd.split('_')
        dir = parts[1].replace('Series', 'TVShow')
        dir = dir.replace('Video', 'HomeVideo')
        dir = dir.replace('iTunes', 'Music')
        cmd = 'NavigationBar'

Now as I understand cmd variable equals 'EyeTV_TV_Scanner' so dir variable becomes 'TV' (since none of the replace functions have matches). So this explains why we are getting "IOError: [Errno 2] No such file or directory: '/Applications/PlexConnect-master/assets/templates/Movies/NavigationBar.xml'".

So solution is to rename my scanner something like EyeTV_TVShow_Scanner of and the error will be gone. Perhaps it would be a good idea to mention in the installation instructions of PlexConnect that if people are using custom scanners, that they have to name it appropriately in order to be compatible with PlexConnect. Renamed the scanner and problem is resolved.

Anyway, thanks for the GREAT work!
