### ISSUE TITLE
WebServer: File not found

### ISSUE THREAD

**Issue by bjornaelvoet** [iBaa/PlexConnect#331]
Following extract from PlexConnect.log:

19:35:54 WebServer: File Not Found:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/WebServer.py", line 198, in do_GET
    JS = JSConverter(basename, options)
  File "/Applications/PlexConnect-master/WebServer.py", line 44, in JSConverter
    f = open(sys.path[0] + "/assets/js/" + file)
IOError: [Errno 2] No such file or directory: '/Applications/PlexConnect-master/assets/js/scrobble.js'

The scrabble.js file is probably obsolete, since there is now found a Scrobble folder in the assets/templates folder.

Need fix in code to use the new scrobble javascript files?

**Comment by roidy** [comment]
There hasn't been a scrobble.js file for sometime. It was remove weeks, even months ago and all the code merged into utils.js

Sound like your PlexConnect install is corrupt in some way. Like you've got a mixture of old and new files.Try a complete fresh install.

**Comment by bjornaelvoet** [comment]
You are probably right, I always do a git pull to keep my generated certificates, but probably something is messed up with my install.

I will verify this evening on my Apple TV and close the issue if issue is solved with clean install.

**Comment by bjornaelvoet** [comment]
The clean install did not remove the issue.

There is still a leftover reference to scrobble.js in one of the templates:

macmini:PlexConnect bjorn_aelvoet$ grep -r scrobble.js .
./assets/templates/TVShow/Episode_List_Fanart.xml:    <script src="{{URL(:/js/scrobble.js)}}" />

Removing this reference removes the error message, but I am still getting the "Trailers is unavailable. Try again later." message on the Apple TV. The log does not however contain any errors.

**Comment by roidy** [comment]
>There is still a leftover reference to scrobble.js in one of the templates:

Good find... I'll clean that up and re-commit the file.

>Removing this reference removes the error message, but I am still getting the "Trailers is unavailable. Try again later." message on the Apple TV. The log does not however contain any errors.

Post a full high level log please.
