### ISSUE TITLE
I'm running Plex (and will run PlexConnect) on a computer that isn't always on. When it's off, will the Apple TV stop working because of the local DNS not working?

### ISSUE THREAD

**Issue by starg09** [iBaa/PlexConnect#332]
Well, as I mention in the title, my computer isn't always on. The Apple TV, however, is used by other members of my family (for netflix or youtube), and I don't want them to depend on the local DNS being on to use it (and I don't want to be switching the DNS setting on and off each time).

Let's say, if I configure the DNS, and my computer turns off, will the Apple TV stop working on other channels, or will it rollback to using the default dns, as if I had it set to "0.0.0.0" like right now? Thanks for reading.

**Comment by roidy** [comment]
No, if PlexConnect is shut down then the ATV wont default back to original DNS, it's up to you to manually set it back. 

This is why most people run PlexConnect on a device that runs 24/7 like a server, NAS or even a router that supports openWRT or Tomato.

**Comment by depraved22** [comment]
I run PlexConnect on my Plex Server at home. Works fine for me in that config as my plex server never goes off.

**Comment by kmaslam** [comment]
I had the same situation like you. I run PMS off my laptop and my ATV will go near dead if my kids close the lid on the laptop. My primary DNS was my RT-AC68R router and so after some experiments, I was able to tweak its DNS to add an entry for the URL. I wasn't using Trailers app rather decided to use WSJ. So secure.marketwatch.com has an entry in my DNS that redirects it to my PMS. 

Now my ATV is not affected by the status of my PMS.. Whether its up or not, it continues to work. If you kind of a router or a DNS server that you could tweak, you should be good with that too..

**Comment by starg09** [comment]
I have a Cisco/Linksys e2500, and AFAIK, it doesn't have an incorporated dns, or url redirector... What a shame, seems like I won't be able to use this :/

Thanks for the replies anyway!

**Comment by roidy** [comment]
>I have a Cisco/Linksys e2500, and AFAIK, it doesn't have an incorporated dns, or url redirector... What a shame, seems like I won't be able to use this :/

Umm... doesn't that router support Tomato??? I think it does.

Flash it with Tomato and use Tomato's DNS or even install PlexConnect on the router.

**Comment by starg09** [comment]
I think it does, I'll try that... Although, I'm not sure if it will be able to handle plexconnect inside it (only 60MB of RAM it seems...). But if I can redirect trailers.apple.com to there, it's good enough for me! :D

**Comment by starg09** [comment]
I used DNSMasq, and it seems to have worked! it redirects the url successfully, and the network actually seems to work better on some old devices compared to the default firmware... Double thanks!

For those interested, this is the line I added: "address=/trailers.apple.com/192.168.1.136" (replacing the last IP with your Plexconnect IP)
