### ISSUE TITLE
Metadata values in XML files

### ISSUE THREAD

**Issue by OskarPersson** [iBaa/PlexConnect#334]
Where can I find the different metadata values I can use on the different pages? For example, on the "onDeck" page I want to have the episode number shown as "S01 E02" instead of "1x02" below each show when selected. In the onDeck.xml file I found `<subtitle>{{episodestring(parentIndex:0:index:0)}}</subtitle>` but I don't know what I should replace it with.

Same thing on the movie page, how do I get multiple genres to display in the details section? In PrePlay_Fanart.xml there is `<label>{{VAL(Video/Genre/tag)}}</label>` but again, what should I replace it with?

**Comment by roidy** [comment]
> <subtitle>{{episodestring(parentIndex:0:index:0)}}</subtitle> 

parentIndex is the Season Number
index is the Episode Number
However the Season episode string is parsed in the {{episodesting()}} function which is in XMLConverter.py, you would need to edit that function.

XMLConverter.py line 1207, change:-

`out = self._("{0:0d}x{1:02d} {2}").format(int(parentIndex), int(index), title)`
to
`out = self._("S{0:0d} E{1:02d} {2}").format(int(parentIndex), int(index), title)`

> <label>{{VAL(Video/Genre/tag)}}</label>  
Try:-
`<label>{{VAL(Video/Genre[0]/tag)}}{{VAL(Video/Genre[1]/tag::=, )}}{{VAL(Video/Genre[1]/tag)}}{{VAL(Video/Genre[2]/tag::=, )}}{{VAL(Video/Genre[2]/tag)}}</label>`

This will list up to 3 genres.
