### ISSUE TITLE
What is transcodequality parameter ?

### ISSUE THREAD

**Issue by moodyblue** [iBaa/PlexConnect#336]
In theory PMS should base its transcoding "decision process" using the Plex Profile of the device, as described here-> https://forums.plex.tv/index.php/topic/42523-writing-profiles-for-dlna-devices/

It's the profile that tells PMS that the file can be Directly Played, or needs remuxing or transcoding. In the later case the "Transcode Targets" section specifies the output characteristics of the transcoder.

But my ATVSettings.cfg file contains these two parameters:
   transcodequality = 1080p 40.0Mbps
   remotebitrate = 720p 3.0Mbps

How do they change the "decision process" ? Do they change the accepted limits ? Or do they override the transcode targets ? Finally, what is the difference between transcodequality and remotebitrate ?

I think that the PlexConnect documentation should include this explanation.

**Comment by roidy** [comment]
transcodequality and remotequality are the limits, eg if transcodequality is set to 720p 12.0Mbps then if a file needs transcoding then it will be transcoded to 720p 12Mbps

transcodequality is for any local network traffic ie Your PMS to your client across your LAN.
remotequality is for any traffic that is non local traffic that is sent across the internet ie channels or remote PMS's.

The "decision process" is determined in the transcoder profile, for the aTV it's in the resources/profiles directory and is called iOS-AppleTV.xml, we also do some of the decision process in XMLConverter.py.

**Comment by moodyblue** [comment]
I'm still confused... I know that the ATV supports H.264 up to 20Mbps, and I have a relatively slow PC with PMS installed, able to transcode up to 4Mbps.

If I have a MP4 file with a H.264 video@20Mbps I want it "Direct Play". But if it is coded VC-1@24Mpbs I want it transcoded to 4Mbps. Is this possible ? How ?

**Comment by iBaa** [comment]
Hm. I guess this is currently not possible. You would need to kick the transcodequality limit out of the decision process (direct play vs direct stream/transcode) and once the decision for the transcoder is done, limit the output to those 4MB/s.
Nothing in PlexConnect to handle that, needs a code change...

**Comment by ttdkr3w** [comment]
what are the smoothest 720p/1080p playback settings?
