### ISSUE TITLE
error creating certificate

### ISSUE THREAD

**Issue by wtnixon** [iBaa/PlexConnect#337]
Following the instructions on https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Windows-Certificates....

When I use this command, C:\trailers.pem -keyout C:\trailers.key -x509 -days 7300 -subj "/C=US/CN=trailers.apple.com" -config C:\OpenSSL-Win32\bin\openssl.cfg , I get a message that 'c:\trailers.pem' is not  recognized as an internal or external command, operable program or batch file.

**Comment by iamgeef** [comment]
you're missing the first part of the command (which shows as the first line in the readme):

*C:\OpenSSL-Win32\bin\openssl.exe req -new -nodes -newkey rsa:2048 -out*

There are no line-breaks in the command so enter everything on one line.

**Comment by wtnixon** [comment]
Wonderful!  Thank you for the quick response!
