### ISSUE TITLE
Shuffle video playlist doesn't work

### ISSUE THREAD

**Issue by surrealroad** [iBaa/PlexConnect#345]
Repro:

1. Have a playlist containing a number of video files
2. In plexconnect, go to Playlists > Choose the video playlist
3. At the top, choose "shuffle"

Expected:

Random video plays

Actual:

First video in list plays

**Comment by Drewbie1974** [comment]
This is as it was designed and from memory is due to a limitation on the ATV

**Comment by surrealroad** [comment]
shouldn't it be called something other than "shuffle" then?

**Comment by Drewbie1974** [comment]
After the first item it is shuffle.

**Comment by surrealroad** [comment]
ah ok!

**Comment by wahlmanj** [comment]
I made a fork (theme) where this works:

https://github.com/wahlmanj3/PlexConnect

Only limitation is that the first item plays last. Once randomly then once again at the end of the list. You can also shuffle shows without creating playlist.
