### ISSUE TITLE
Remember Credentials and Settings

### ISSUE THREAD

**Issue by alzeric** [iBaa/PlexConnect#346]
Is there a way to get Plex Connect to remember user/password and Video player settings per device?

It seems like whenever my Apple TV goes into hibernation mode, or isn't used for a few hours if I go back into trailers, it requires me to enter the user /pass again and my settings are all reverted back to default, so I have to go in each time and turn off the clock and duration text.

**Comment by roidy** [comment]
PlexConnect does store the settings on a per device basis.

Sounds like incorrect permissions on the settings files, which means PlexConnect isn't able to write to the file.

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
