### ISSUE TITLE
Photo problem with 0.5-dev

### ISSUE THREAD

**Issue by airmamaf** [iBaa/PlexConnect#348]
I've got the following problem with PlexConnect 0.5.9 when trying to access Photo 

11:50:25 WebServer: File Not Found:
Traceback (most recent call last):
  File "/volume1/@appstore/plexconnect/share/PlexConnect/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/volume1/@appstore/plexconnect/share/PlexConnect/XMLConverter.py", line 380, in XML_PMS2aTV
    aTVTree = etree.parse(sys.path[0]+'/assets/templates/'+XMLtemplate)
  File "<string>", line 62, in parse
  File "<string>", line 26, in parse
IOError: [Errno 21] Is a directory: '/volume1/@appstore/plexconnect/share/PlexConnect/assets/templates/'

**Comment by roidy** [comment]
PlexConnect 0.5.9 ????? That's not a PlexConnect version number :(

https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue

**Comment by airmamaf** [comment]
OK, maybe it's badly written, package was found there 
http://www.brigittehelsen.be/plexconnect/packages/plexconnect_noarch_0.5-9.spk

I'm running it on Synology DS214play with ATV3
In the log, version is
Version: 0.5-dev

**Comment by roidy** [comment]
Ok..... so where is the log? How can we help without it?

**Comment by airmamaf** [comment]
Ok, I found the problem, in the above package this line was missing in XMLConverter.py
 elif cmd.find('Photo') != -1: dir = 'Photo'

After that, I can access to Photo section, but there's another bug, after that XMLConverter.py try to find 
SectionPreview-Photo.xml (Photo with captial P) and the file is SectionPreview-photo.xml (Photo with a lowercase p)



13:51:43 WebServer: File Not Found:
Traceback (most recent call last):
  File "/volume1/@appstore/plexconnect/share/PlexConnect/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/volume1/@appstore/plexconnect/share/PlexConnect/XMLConverter.py", line 381, in XML_PMS2aTV
    aTVTree = etree.parse(sys.path[0]+'/assets/templates/'+XMLtemplate)
  File "<string>", line 62, in parse
  File "<string>", line 26, in parse
IOError: [Errno 2] No such file or directory: '/volume1/@appstore/plexconnect/share/PlexConnect/assets/templates/Main/SectionPreview-Photo.xml'

**Comment by airmamaf** [comment]
Maybe it's a packaing problem so I've just posted a comment here
https://forums.plex.tv/index.php/topic/72356-plexconnect-on-synology/page-71

**Comment by moodyblue** [comment]
Still an issue ?

**Comment by moodyblue** [comment]
Closed due to inactivity.
