### ISSUE TITLE
Allow to download latest localization files

### ISSUE THREAD

**Issue by bcse** [iBaa/PlexConnect#351]
According to my investigation, Get Localization doesn't allow anyone to download localization files except authorized user.
Can we move to Transifex? It have better editor UI, more features, and allow anyone to download latest localization files.

**Comment by iBaa** [comment]
Currently the language files of the github rep are like 3 days old... I have no idea about the other service, but also no real concerns against it. Let me check with DennisO - he was dealing with the translation so far, maybe he has more background information than I do. :-D

**Comment by bcse** [comment]
That's good to know. Thanks!

In fact, I just updated Chinese Traditional localization and want to test on my machine and couldn't find a way to download the PO file... :stuck_out_tongue_closed_eyes:

**Comment by bcse** [comment]
I have imported current localizations to Transifex.
https://www.transifex.com/projects/p/plexconnect/

If we are going to moving to Transifex, let me know your username so I can add you as admin.

**Comment by bcse** [comment]
@dennisoderwald Hi, what's your opinion on this?
