### ISSUE TITLE
While watching "Ends at:" doesn't disappear

### ISSUE THREAD

**Issue by ferologics** [iBaa/PlexConnect#353]
Constantly shows "ends at: XX : XX" on the bottom of the screen while watching (after os update)

Can I fix this somehow?

**Comment by iBaa** [comment]
You should be able to switch it off completely - see Settings/OSD. But that shouldn't be the way to go...
What about the clock (upper screen), does that stay there as well?

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
