### ISSUE TITLE
smooth playback settings 

### ISSUE THREAD

**Issue by ttdkr3w** [iBaa/PlexConnect#354]
what are the best settings for smooth playback? every few minutes i experience a split second re buffer. really would appreciate some help. cheers

**Comment by OstlerDev** [comment]
It depends on how fast your internet speed is and how powerful the machine you are running Plex on is. Plex needs to transcode it and send the stream. If you are experiencing issues with buffering try turning down the quality on the PlexConnect Settings page.

**Comment by Drewbie1974** [comment]
Internet speed only comes into it if you have your plex machine at a different site to your plexconnect/atv.

It's more a question of what format and codecs the media is in as the ATV only native plays a limited set, so everything else is transcoded and this needs a reasonable CPU.

**Comment by ttdkr3w** [comment]
My atv sits next to my Mac mini. Help with best settings is what I'm after! Movies that playback well are 700-2gb, most movies in my library are 10-50gb. I am unsure to what settings need to be set at. Cheers

**Comment by OstlerDev** [comment]
What kind of video quality are you using for your videos? 4k? 10-50GB would be a HUGE file for a movie, at that point if you are using a slow hard drive it will not be fast enough to transcode, or even play without transcoding.

Your Mac Mini is most likely not powerful enough to transcode those videos live. Are you able to watch the same movie on Plex Web?

**Comment by Drewbie1974** [comment]
Why not just connect the Mac mini to the tv and use PHT as PHT can play more files natively

**Comment by ttdkr3w** [comment]
My mac isn't the issue. I have a 2.3ghz i7 quad core mac mini with 32gb ram and 1tb ssd with a 4 bay 6tb thunderbolt raid as my media library. I have 2 ATV's hard wired to my network and run all of this through a gefen hdmi matrix across 4 60" screens.  

60% of my movies are compressed 1080p 1-5GB all of these play fine on plexconnect without missing a beat, 40% of my movies are 40GB+ in size 1080p, through atv plexconnect at times they play mint, sometimes they rebuffer every few minutes or not at all. I have transcoder action set to 'auto'. transcoder quality to 1080p 40mbps. remote bitrate 1080p 40mbps. I am unfamiliar with pht? 

Are either of you the developers? Im after the best settings for my system!!

**Comment by OstlerDev** [comment]
While I have not contributed code to this repository, I do have a similar project that runs on the same principles. I understand how the code of Plex Connect works. I do believe that the processor on your Mac Mini is just not powerful enough to transcode at that high of a bitrate. Are you able to watch the movies on the web player while transcoding at 40mbps? I do not believe that this is an issue with PlexConnect but either your hardware or an issue with Plex itself.

Best of luck on your journey.

**Comment by ttdkr3w** [comment]
So what kind of processor power is actually required to achieve top performance?

Nick Porter
ttdkr3w@gmail.com
+64275235678

**Comment by OstlerDev** [comment]
I honestly do not know, but estimating at transcoding that live you would need a server grade processor. If you were looking to keep with Mac, then you might need a Mac Pro.

This is just my opinion and could be completely wrong, take it with a grain of salt.

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
