### ISSUE TITLE
WSJ Live/Video can no longer be hijacked

### ISSUE THREAD

**Issue by johncoxon** [iBaa/PlexConnect#356]
An update to the WSJ Live app which renamed it WSJ Video, and now it cannot be hijacked by PlexConnect. See also [this thread on the Plex forums](https://forums.plex.tv/index.php/topic/168109-plexconnect-suddendly-stopped-working/).

**Comment by iBaa** [comment]
The linked thread comes with a solution as well, doesn't it?
I don't think the given host addresses/URLs are found "here" on github - so there is nothing I can update to help.

**Comment by coolspot18** [comment]
What is the resolution? With the hack... the forums are down.

Thanks.

**Comment by iBaa** [comment]
Yep, forum is down. Solution is to use the new address - which I honestly don't know. Wahlman does, tough... :-D
