### ISSUE TITLE
"No Plex Library Sections Available” 

### ISSUE THREAD

**Issue by CheukYeeCheng** [iBaa/PlexConnect#357]
Hi there, I have tried everything I know of, but I still can't get it to work again, you guys are my last hope! Help would be much appreciated! The issue form:
![image](https://cloud.githubusercontent.com/assets/13165359/8498700/360a9722-218a-11e5-82eb-42bcc1e09201.png)
![image](https://cloud.githubusercontent.com/assets/13165359/8498707/3dddcfb4-218a-11e5-8113-cfa8a4595a58.png)

Hopefully somebody can help me out here. 

Regards,
Cheuk

**Comment by iBaa** [comment]
Your pastebin log link holds a screenshot of your issue description?

Using Plex Home? Have "require authentication" enabled in PMS?
My guess: Your aTV is not connecting to your myPlex account. Or your PMS is not correctly published.

As PlexConnect still serves XML to aTV I don't really see an issue with it. And without a log, I guess I can't help much further...

**Comment by CheukYeeCheng** [comment]
Yes the pastebin holds the log. http://pastebin.com/WcgDAExC
Can you help me further?

**Comment by iBaa** [comment]
Discovery process:
> 13:28:31 PlexAPI: GDM: No servers discovered
> ...
> 13:28:33 PlexAPI: MediaContainer friendlyName="myPlex" identifier="com.plexapp.plugins.myplex" machineIdentifier="195f84a00a85c6621b3427c7c488629fb9dbdaeb" size="0"

a) PMS does not answer to the GDM request
b) there is no PMS known at plex.tv

You got to have a PMS visible. Either an own now in your local LAN - which might be detected with GDM - or a remote one, published at plex.tv and shared with your Myplex account.

**Comment by CheukYeeCheng** [comment]
Hm.. how do I do that?

**Comment by CheukYeeCheng** [comment]
Ah never mind, I figured it out how to do it. I had to enable UPnP on my modem, which in turn made the remote server accessible. Don't know why this had suddenly changed... 
Anyway, it's working again! Thank you very much for the help!! :)
