### ISSUE TITLE
Shared Libraries Can't Be Found

### ISSUE THREAD

**Issue by farmboi** [iBaa/PlexConnect#358]
Hi, 

Shared Libraries / remote servers do not appear to be showing up. I have tried logging in and out of myplex under settings and still not. Discovery only shows one plex server which is mine. I have tried turning off GDM Discovery on Plex as well as removing my IPs from the whitelist to require login to no affect. I have made sure the remote server is online and accessible and can access it via Plex Web. 

I have rebooted both plex, plexconnect and apple tv's. I don't think it is so much an issue with the plex version at least in the case of 0.9.11.4 as this used to work in the past. I have only recent gotten access back to my friends remote server since they had data loss. However I tried upgrading to match his 0.9.12.4 and still no change. 

My setup is as follows. 

PlexConnect 0.5 (Stable). Also tried PlexConnect 0.5-dev-020615
Plex Media Server 0.9.12.4, Was Previously Running 0.9.11.4 with the same issue. 
Apple TV 2 and Apple TV 3
CentOS 6.6
Python 2.7

I am not sure if anyone else is having issues or if there is anything else that can be done to fix this.

**Comment by Drewbie1974** [comment]
We will need a lot to help you.  Have a read of this section https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue and complete the template and provide all information

**Comment by iBaa** [comment]
Probably an publishing issue with those PMSs - aka "light published". See if the server shows up under ```https://plex.tv/pms/servers```, ask you friend to re-publish it.
Plex/Web does cache information really hard once a PMS was seen, PlexConnect does not.

**Comment by farmboi** [comment]
Hi,

To note the DNS is set to Manual and the PlexConnect Servers IP which is internal.

The IP of the PlexConnect server and Plex server are different.

As an example the PlexConnect is on 192.168.1.10
The Plex Server is on 192.168.1.11

Both servers are running CentOS 6.6 as mentioned previously with Python 2.7 on PlexConnect. These are in virtual environments. 

The output of the PlexConnect.log is quite large so I have included it in the link below, however with users and IP Addresses redacted for security. 

https://raw.githubusercontent.com/farmboi/Misc/master/plexconnect_log_redacted.txt

Below is my settings.cgf

# cat Settings.cfg 
[PlexConnect]
enable_plexgdm = True
ip_pms = REDACTED
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = REDACTED
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = video-api-secure.wsj.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/wsj.pem
loglevel = Normal
logpath = .

iBaa: To note when visiting the above url in your post both my server and his show up. He recently had to re-set this back up under Plex since it was using a different machine identifier, so I don't think it is cached. I even had him reset up remote access today and we can both see each others servers on plex.tv, and in the web app. Both servers also show up in the PlexConnect log when searching for them, however it only shows the One Discovered in the interface and according to the log, despite getting the details for his server. 

To note my server is Pichu and his is rubberducky

If you need anything else let me know.

**Comment by iBaa** [comment]
There sure is something fishy...
I don't know exactly what's going on, but it seems you PlexConnect code is somewhat outdated. There were some rather big changes to the discovery process with the arrival of the Plex Home feature. Your issues might be connected to that... but I am really not sure about that.
Are you able to update PlexConnect to the latest sources? Further investigation would be a lot easier for me. :-D

**Comment by farmboi** [comment]
Below is the log output from the latest code. I have chosen to say on 0.5 Stable as I have had other issues with the latest version such as with On Deck so far. I'll open a new issue for that. 

https://github.com/farmboi/Misc/raw/master/PlexConnectLog-0.5-dev-020615.txt

**Comment by farmboi** [comment]
I tested with my own external server and this is working. I will have to get back with him to see how he has this setup. I know he says he uses a proxy for the web login but don't think this would affect this. Going to go ahead and close this out for now.
