### ISSUE TITLE
Special Episodes (Episode 0) won't show

### ISSUE THREAD

**Issue by bcse** [iBaa/PlexConnect#359]
Some TV Shows have special episodes.
Special episodes are marked as episode 0 in Plex Media Server.
But they won't show in PlexConnect.

A simple fix would be replace `{{COPY(Video:index::=|0 =COPY)}}` into `{{COPY(Video)}}` in Episode_List.xml and Episode_List_Fanart.xml.
But I'm not sure if this will cause other issues.

Here are some examples of Episode 0:
* Supergirl - [Unaired Pilot](http://thetvdb.com/?tab=season&seriesid=295759&seasonid=623813&lid=7)
* Fate/Stay Night: Unlimited Blade Works - [Prologue](http://thetvdb.com/?tab=season&seriesid=278626&seasonid=577004&lid=7)
* Undateable - [A Live Show Walks Into A Bar (West Coast Feed)](http://thetvdb.com/?tab=season&seriesid=269618&seasonid=606156&lid=7)

**Comment by Rycochet** [comment]
Those are generally marked as Season 0, Episode xx - and have been showing up in mine without any issues pretty much forever - are you sure you're not trying to put them into the season they're marked as Specials in?

**Comment by bcse** [comment]
@Rycochet Thank you. I thought they should be marked as Season xx, Episode 0... Mark them as Season 0, Episode xx will fix this. I'll close this issue.
