### ISSUE TITLE
Mult-user support

### ISSUE THREAD

**Issue by legabil** [iBaa/PlexConnect#361]
Is it possible for there to be multi-user profiles on PlexConnect?  When I enable must-user on my PMS, it is breaking PlexConnect on ATV.

**Comment by iBaa** [comment]
Multi-user? Plex Home? It's there, isn't it?

**Comment by legabil** [comment]
It breaks once I try to access the option on AppleTV.  I can enable it in Plex Media Server, but then PlexConnect stops working.

Sent from Outlook




On Fri, Jul 10, 2015 at 11:18 AM -0700, "iBaa" <notifications@github.com> wrote:
Multi-user? Plex Home? It's there, isn't it?

---

**Comment by rodneytasm** [comment]
Yes, the option is there but I'm seeing the same issue, even when trying to switch users from the primary to the managed user.  As soon as the managed user is removed from Plex, PlexConnect starts working again.

**Comment by legabil** [comment]
@Rodneytasm. That's exactly the issue I am experiencing.

Sent from Outlook




On Sun, Jul 12, 2015 at 7:12 AM -0700, "rodneytasm" <notifications@github.com> wrote:
Yes, the option is there but I'm seeing the same issue, even when trying to switch users from the primary to the managed user.  As soon as the managed user is removed from Plex, PlexConnect starts working again.

---

**Comment by iBaa** [comment]
Huh. Anything special with the secondary user names? Like special chars, punctuation, foreign language, whatever? A log might help...
Plex Forum is open again - I would recommend moving the discussion over there. I bet the threads there are read (and answered) by more people.

**Comment by legabil** [comment]
No special characters.  Just a name, Claire.

I'll try the forums.  Thanks for your help.

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
