### ISSUE TITLE
Trailer not availible after watching a home movie

### ISSUE THREAD

**Issue by yabbah** [iBaa/PlexConnect#362]
When we watching some of out home movies, no matter which one. After each one, there is an error message say "trailer not availible" and we have to start over again. This is not happening when watching regular movies, just home movies.

Can this be reprocused by you and solved in some way?

**Comment by iBaa** [comment]
Do you have the latest version?
Are you abel to share logs?

**Comment by yabbah** [comment]
How can I confirm that I use the latest? I use the git-installed stuff, and
tried 'git pull' and it say up-to-date tho :)
And the second one, where is the logs?

2015-08-03 16:40 GMT+02:00 iBaa <notifications@github.com>:

**Comment by iBaa** [comment]
version: it's printed on the PlexConnect/settings page. The most recent versions also spell out the date... But then, if github says it's fine, it should be so.
logs: Typically right in the PlexConnect folder.

**Comment by yabbah** [comment]
Sorry, but, PlexConnect/settings page? Do you mean Settings.cfg? I cant
find any date in there?

2015-08-04 17:20 GMT+02:00 iBaa <notifications@github.com>:

**Comment by iBaa** [comment]
From your aTV... hit Trailers (PlexConnect), then move right to Settings. Somewhere under the Plex Logo you will find the version printed. Like 0.5-dev-<date> or similar. Can't remember right now...

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
