### ISSUE TITLE
WD MyCloud EX2 NAS throwing SSLv2 method error

### ISSUE THREAD

**Issue by tobsn** [iBaa/PlexConnect#363]
I just tried to run it and I'm getting:

```
root@EX2 PlexConnect-master # ./PlexConnect.py
Traceback (most recent call last):
  File "./PlexConnect.py", line 19, in <module>
    import DNSServer, WebServer
  File "/home/root/PlexConnect-master/WebServer.py", line 21, in <module>
    import ssl
  File "/usr/local/modules/python27/lib/python2.7/ssl.py", line 60, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /usr/local/modules/python27/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: SSLv2_method
```

I mean this would be optimal if it could be run on the NAS that also runs plex...

**Comment by roidy** [comment]
The latest firmware seem to break python on the MyCloud devices:-

http://community.wd.com/t5/WD-My-Cloud-EX2/Python-no-longer-compiled-against-SSL/td-p/888450
http://community.wd.com/t5/WD-My-Cloud-EX4/1-05-36-Broke-Python/td-p/892635

This would need to be fixed at the firmware level by WD.

**Comment by sahlex** [comment]
Why has this issue been closed? It does not seem to be solved by now. 
I have update 2.11.169 on my system (ex2) from January, 23. 2018 and experience the same issue.

**Comment by moodyblue** [comment]
As said by @roidy this needs to be solved in the WD side.

As a hint, some other NAS (for example QNAP and Synology) allow installation of community supported python versions.

**Comment by sahlex** [comment]
OK, thanks.
