### ISSUE TITLE
Plexconnect and Internal network

### ISSUE THREAD

**Issue by abrikman** [iBaa/PlexConnect#365]
I have a server with Debian 8, and this server work as router.

In eth0 - Internet, eth1 - local network 

After start PlexConnect i see as plexconnect use Internet IP address, but I want use ip my local network for plexconnect. 

'ip_pms' i wrote local ip. 

Can you help me?

**Comment by iBaa** [comment]
If I understand your question correctly, you got to set...
- enable_plexconnnect_autodetect = False
- ip_plexconnect = <your local IP>

**Comment by abrikman** [comment]
Nope, It seems that Plexconnect automatically runs on eth0 interface. Your solution did not help.

**Comment by depraved22** [comment]
So for me, it works fine. If you can post your config, that may help. I have PlexConnect on my second interface:

```
ip_pms = 192.168.1.31
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = False
enable_plexconnect_autodetect = False
ip_plexconnect = 192.168.1.32
hosttointercept = trailers.apple.com
port_webserver = 80
```

**Comment by iBaa** [comment]
>Nope, It seems that Plexconnect automatically runs on eth0 interface. Your solution did not help.

Well, when defining PlexConnect's IP manually, you should be able to push it to eth1, too.
