### ISSUE TITLE
Wiki page for how to setup with pow firewall running

### ISSUE THREAD

**Issue by kdawgwilk** [iBaa/PlexConnect#367]
I was stuck for hours trying to figure out why my certificates would never install and then finally found that I had a pow firewall setup and I had to uninstall it cause I could figure out no way to have them both running at the same time

**Comment by iBaa** [comment]
This "pow firewall": http://pow.cx/manual.html?
Never seen it, never used it. No idea how to set it up, nor how to write a guide... :-D

**Comment by kdawgwilk** [comment]
Yep that is the one, I did find this:

http://forums.plex.tv/discussion/71212/trailers-is-unavailable-try-again-later

"I almost thought it would work now, cause when i followed your instructions i figured out, that a pow-server (for ruby-on-rails-development) was running on port 80, so when i visit (192.168.1.2) from a different computer (or just try "localhost" on the current one) POW responded. Unfortunately after shutting down POW the problem still exist...
*Update:*
I found something interesting in the POW documentation:
"The firewall rule installed by Pow redirects all incoming traffic on port 80 to port 20559, where Pow runs. This means if you have another web server running on port 80, like the Apache that comes with Mac OS X, it will be inaccessible without either disabling the firewall rule or updating that server's configuration to listen on another port."
So i somehow have to find where to change this firewall rule."
