### ISSUE TITLE
Poster art screen saver? Willing to try myself with some direction.

### ISSUE THREAD

**Issue by jsahlen** [iBaa/PlexConnect#37]
It would be really cool to be able to select Trailers are the screen saver source on ATV, and have PlexConnect serve up its poster art. Not sure if this functionality uses the same XML interface as the regular Trailers 'App' so it would be possible, but it would be really nice.

I'm a developer myself, and I'd love to give this a whirl. Having never done any work with the Apple TV though, I was wondering what the best way to intercept calls to find out the URLs as well as what Apples XML responses look like would be. Charles?

**Comment by moodyblue** [comment]
This was an interesting idea. @iBaa and team did not implement it, and I think that now it's too late to consider it.
