### ISSUE TITLE
PMS & XMLconverter

### ISSUE THREAD

**Issue by fatfreddyone** [iBaa/PlexConnect#370]
Hello

how can I verify the connection between PlexConnect and PMS server
Everything seems to work but the movies do not appear on TV
I see the DNS flow in the cmd window where PlexConnect is running
With the option high nothing in the logreport about the connection to the PMS or XMLconverter

[PlexConnect]
enable_plexgdm = False
ip_pms = 192.168.0.17 (my local adresse on the lan PMS and PlexConnect runs on the same W32)
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 89.2.0.1(my DNS, it's work's like Google's DNS)
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 192.168.0.17
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = High
logpath = .

i set debug.py to 2 for xmlconverter but no more log
thanks for your help

**Comment by iBaa** [comment]
>I see the DNS flow in the cmd window where PlexConnect is running

It's at least a start.
Somewhere in between - once you hit the trailers app - you should find a "intercept" message, followed by a request for "application.js" and the discovery process. At that point in time you should see more detailed information about the servers connected as well as possible access restrictions.
Messages from XMLConverter will come later - once the aTV->PlexConnect connection is well established and data pulled in from attached PMSs.

**Comment by fatfreddyone** [comment]
Thanks a lot for your message :blush: 

I don't understand completely "once you hit the trailers app" ?
when i run the trailers app on the apple TV ?
it seems that there is no trailers app on ATV3 7.3 (french)
trailers are everywhere when you choose the movies option

there is no DNS request to apple.trailers.com
i give you my log, sorry it's a bit long 
192.168.0.17 is my host with PlexConnect & PMS running
192.168.0.20 is the ATV3
89.2.0.1 is my provider DNS, it works like 8.8.8.8

13:15:13 PlexConnect: started: 13:15:13
13:15:13 PlexConnect: Version: 0.5-dev-020615
13:15:13 PlexConnect: Python: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
13:15:13 PlexConnect: Host OS: win32
13:15:13 PlexConnect: PILBackgrounds: Is PIL installed? False
13:15:13 Settings: getsetting enable_plexconnect_autodetect=True
13:15:13 PlexConnect: IP_self: 192.168.0.17
13:15:13 Settings: getsetting hosttointercept=trailers.apple.com
13:15:13 Settings: getsetting enable_dnsserver=True
13:15:13 Settings: getsetting enable_webserver_ssl=True
13:15:13 DNSServer: started: 13:15:13
13:15:13 Settings: getsetting port_dnsserver=53
13:15:13 Settings: getsetting ip_dnsmaster=89.2.0.1
13:15:13 Settings: getsetting prevent_atv_update=True
13:15:13 DNSServer: ***
13:15:13 DNSServer: DNSServer: Serving DNS on 192.168.0.17 port 53.
13:15:13 DNSServer: intercept: ['trailers.apple.com'] => 192.168.0.17
13:15:13 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
13:15:13 DNSServer: forward other to higher level DNS: 89.2.0.1
13:15:13 DNSServer: ***
13:15:13 WebServer: started: 13:15:13
13:15:13 Settings: getsetting port_webserver=80
13:15:13 WebServer: ***
13:15:13 WebServer: WebServer: Serving HTTP on 192.168.0.17 port 80.
13:15:13 WebServer: ***
13:15:14 WebServer: started: 13:15:14
13:15:14 Settings: getsetting port_ssl=443
13:15:14 Settings: getsetting certfile=./assets/certificates/trailers.pem
13:15:14 Settings: getsetting certfile=./assets/certificates/trailers.pem
13:15:14 WebServer: ***
13:15:14 WebServer: WebServer: Serving HTTPS on 192.168.0.17 port 443.
13:15:14 WebServer: ***
13:16:35 DNSServer: DNS request received!
13:16:35 DNSServer: Source: ('192.168.0.20', 51992)
13:16:35 DNSServer: Domain: init.itunes.apple.com
13:16:35 DNSServer: ***forward request
13:16:35 DNSServer: -> DNS response from higher level
13:16:36 DNSServer: DNS request received!
13:16:36 DNSServer: Source: ('192.168.0.20', 65025)
13:16:36 DNSServer: Domain: gs-loc.apple.com
13:16:36 DNSServer: ***forward request
13:16:36 DNSServer: -> DNS response from higher level
13:16:36 DNSServer: DNS request received!
13:16:36 DNSServer: Source: ('192.168.0.20', 59199)
13:16:36 DNSServer: Domain: cl5.apple.com
13:16:36 DNSServer: ***forward request
13:16:36 DNSServer: -> DNS response from higher level
13:16:36 DNSServer: DNS request received!
13:16:36 DNSServer: Source: ('192.168.0.20', 57723)
13:16:36 DNSServer: Domain: local
13:16:36 DNSServer: ***forward request
13:16:36 DNSServer: -> DNS response from higher level
13:16:36 DNSServer: DNS request received!
13:16:36 DNSServer: Source: ('192.168.0.20', 51992)
13:16:36 DNSServer: Domain: init.itunes.apple.com
13:16:36 DNSServer: ***forward request
13:16:36 DNSServer: -> DNS response from higher level
13:16:37 DNSServer: DNS request received!
13:16:37 DNSServer: Source: ('192.168.0.20', 65025)
13:16:37 DNSServer: Domain: gs-loc.apple.com
13:16:37 DNSServer: ***forward request
13:16:37 DNSServer: -> DNS response from higher level
13:16:37 DNSServer: DNS request received!
13:16:37 DNSServer: Source: ('192.168.0.20', 59199)
13:16:37 DNSServer: Domain: cl5.apple.com
13:16:37 DNSServer: ***forward request
13:16:37 DNSServer: -> DNS response from higher level
13:16:38 DNSServer: DNS request received!
13:16:38 DNSServer: Source: ('192.168.0.20', 64635)
13:16:38 DNSServer: Domain: init-p01md.apple.com
13:16:38 DNSServer: ***forward request
13:16:38 DNSServer: -> DNS response from higher level
13:16:38 DNSServer: DNS request received!
13:16:38 DNSServer: Source: ('192.168.0.20', 59199)
13:16:38 DNSServer: Domain: cl5.apple.com
13:16:38 DNSServer: ***forward request
13:16:38 DNSServer: -> DNS response from higher level
13:16:38 DNSServer: DNS request received!
13:16:38 DNSServer: Source: ('192.168.0.20', 61014)
13:16:38 DNSServer: Domain: setup.icloud.com
13:16:38 DNSServer: ***forward request
13:16:38 DNSServer: -> DNS response from higher level
13:16:38 DNSServer: DNS request received!
13:16:38 DNSServer: Source: ('192.168.0.20', 62108)
13:16:38 DNSServer: Domain: time-ios.apple.com
13:16:38 DNSServer: ***forward request
13:16:38 DNSServer: -> DNS response from higher level
13:16:38 DNSServer: DNS request received!
13:16:39 DNSServer: Source: ('192.168.0.20', 55245)
13:16:39 DNSServer: Domain: bookkeeper.itunes.apple.com
13:16:39 DNSServer: ***forward request
13:16:39 DNSServer: -> DNS response from higher level
13:16:39 DNSServer: DNS request received!
13:16:39 DNSServer: Source: ('192.168.0.20', 60644)
13:16:39 DNSServer: Domain: itunes.apple.com
13:16:39 DNSServer: ***forward request
13:16:39 DNSServer: -> DNS response from higher level
13:16:39 DNSServer: DNS request received!
13:16:39 DNSServer: Source: ('192.168.0.20', 51821)
13:16:39 DNSServer: Domain: xp.apple.com
13:16:39 DNSServer: ***forward request
13:16:39 DNSServer: -> DNS response from higher level
13:16:40 DNSServer: DNS request received!
13:16:40 DNSServer: Source: ('192.168.0.20', 53870)
13:16:40 DNSServer: Domain: p39-buy.itunes.apple.com
13:16:40 DNSServer: ***forward request
13:16:40 DNSServer: -> DNS response from higher level
13:16:41 DNSServer: DNS request received!
13:16:41 DNSServer: Source: ('192.168.0.20', 50906)
13:16:41 DNSServer: Domain: e2842.e9.akamaiedge.net
13:16:41 DNSServer: ***forward request
13:16:41 DNSServer: -> DNS response from higher level
13:16:42 DNSServer: DNS request received!
13:16:42 DNSServer: Source: ('192.168.0.20', 53904)
13:16:42 DNSServer: Domain: p39-buy.itunes-apple.com.akadns.net
13:16:42 DNSServer: ***forward request
13:16:42 DNSServer: -> DNS response from higher level
13:16:43 DNSServer: DNS request received!
13:16:43 DNSServer: Source: ('192.168.0.20', 57407)
13:16:43 DNSServer: Domain: setup.icloud.com.akadns.net
13:16:43 DNSServer: ***forward request
13:16:43 DNSServer: -> DNS response from higher level
13:16:43 DNSServer: DNS request received!
13:16:43 DNSServer: Source: ('192.168.0.20', 53904)
13:16:43 DNSServer: Domain: p39-buy.itunes-apple.com.akadns.net
13:16:43 DNSServer: ***forward request
13:16:43 DNSServer: -> DNS response from higher level
13:16:44 DNSServer: DNS request received!
13:16:44 DNSServer: Source: ('192.168.0.20', 57464)
13:16:44 DNSServer: Domain: init.itunes.apple.com
13:16:44 DNSServer: ***forward request
13:16:44 DNSServer: -> DNS response from higher level
13:16:45 DNSServer: DNS request received!
13:16:45 DNSServer: Source: ('192.168.0.20', 51538)
13:16:45 DNSServer: Domain: mesu.apple.com
13:16:45 DNSServer: ***restrain request
13:16:45 DNSServer: -> DNS response: 192.168.0.17
13:16:46 DNSServer: DNS request received!
13:16:46 DNSServer: Source: ('192.168.0.20', 54086)
13:16:46 DNSServer: Domain: init-p01st.push.apple.com
13:16:46 DNSServer: ***forward request
13:16:46 DNSServer: -> DNS response from higher level
13:16:47 DNSServer: DNS request received!
13:16:47 DNSServer: Source: ('192.168.0.20', 62634)
13:16:47 DNSServer: Domain: 42-courier.push.apple.com
13:16:47 DNSServer: ***forward request
13:16:47 DNSServer: -> DNS response from higher level
13:16:48 DNSServer: DNS request received!
13:16:48 DNSServer: Source: ('192.168.0.20', 65233)
13:16:48 DNSServer: Domain: se.itunes.apple.com
13:16:48 DNSServer: ***forward request
13:16:48 DNSServer: -> DNS response from higher level
13:16:49 DNSServer: DNS request received!
13:16:49 DNSServer: Source: ('192.168.0.20', 64399)
13:16:49 DNSServer: Domain: a4.mzstatic.com
13:16:49 DNSServer: ***forward request
13:16:49 DNSServer: -> DNS response from higher level
13:16:50 DNSServer: DNS request received!
13:16:50 DNSServer: Source: ('192.168.0.20', 54717)
13:16:50 DNSServer: Domain: a3.mzstatic.com
13:16:50 DNSServer: ***forward request
13:16:50 DNSServer: -> DNS response from higher level
13:16:50 DNSServer: DNS request received!
13:16:50 DNSServer: Source: ('192.168.0.20', 57347)
13:16:50 DNSServer: Domain: a2.mzstatic.com
13:16:50 DNSServer: ***forward request
13:16:50 DNSServer: -> DNS response from higher level
13:16:50 DNSServer: DNS request received!
13:16:50 DNSServer: Source: ('192.168.0.20', 50651)
13:16:50 DNSServer: Domain: a5.mzstatic.com
13:16:50 DNSServer: ***forward request
13:16:50 DNSServer: -> DNS response from higher level
13:16:50 DNSServer: DNS request received!
13:16:50 DNSServer: Source: ('192.168.0.20', 52411)
13:16:50 DNSServer: Domain: time-ios.g.aaplimg.com
13:16:50 DNSServer: ***forward request
13:16:50 DNSServer: -> DNS response from higher level
13:16:58 DNSServer: DNS request received!
13:16:58 DNSServer: Source: ('192.168.0.20', 59335)
13:16:58 DNSServer: Domain: www.apple.com
13:16:58 DNSServer: ***forward request
13:16:58 DNSServer: -> DNS response from higher level
13:17:03 DNSServer: DNS request received!
13:17:03 DNSServer: Source: ('192.168.0.20', 63521)
13:17:03 DNSServer: Domain: configuration.apple.com
13:17:03 DNSServer: ***forward request
13:17:03 DNSServer: -> DNS response from higher level
13:17:03 DNSServer: DNS request received!
13:17:03 DNSServer: Source: ('192.168.0.20', 51226)
13:17:03 DNSServer: Domain: xp.apple.com
13:17:03 DNSServer: ***forward request
13:17:03 DNSServer: -> DNS response from higher level
13:17:03 DNSServer: DNS request received!
13:17:03 DNSServer: Source: ('192.168.0.20', 58378)
13:17:03 DNSServer: Domain: pd-nk.itunes.apple.com
13:17:03 DNSServer: ***forward request
13:17:03 DNSServer: -> DNS response from higher level
13:17:05 DNSServer: DNS request received!
13:17:05 DNSServer: Source: ('192.168.0.20', 54982)
13:17:05 DNSServer: Domain: apple.com
13:17:05 DNSServer: ***forward request
13:17:05 DNSServer: -> DNS response from higher level
13:17:08 DNSServer: DNS request received!
13:17:08 DNSServer: Source: ('192.168.0.20', 59196)
13:17:08 DNSServer: Domain: p16-keyvalueservice.icloud.com
13:17:08 DNSServer: ***forward request
13:17:08 DNSServer: -> DNS response from higher level
13:17:08 DNSServer: DNS request received!
13:17:08 DNSServer: Source: ('192.168.0.20', 61380)
13:17:08 DNSServer: Domain: keyvalueservice.icloud.com
13:17:08 DNSServer: ***forward request
13:17:08 DNSServer: -> DNS response from higher level
13:17:08 DNSServer: DNS request received!
13:17:08 DNSServer: Source: ('192.168.0.20', 63481)
13:17:08 DNSServer: Domain: play.itunes.apple.com
13:17:08 DNSServer: ***forward request
13:17:08 DNSServer: -> DNS response from higher level
13:17:42 DNSServer: DNS request received!
13:17:42 DNSServer: Source: ('192.168.0.20', 57275)
13:17:42 DNSServer: Domain: itunes.apple.com
13:17:42 DNSServer: ***forward request
13:17:42 DNSServer: -> DNS response from higher level
13:17:47 DNSServer: DNS request received!
13:17:47 DNSServer: Source: ('192.168.0.20', 59481)
13:17:47 DNSServer: Domain: securemetrics.apple.com
13:17:47 DNSServer: ***forward request
13:17:47 DNSServer: -> DNS response from higher level
13:17:47 DNSServer: DNS request received!
13:17:47 DNSServer: Source: ('192.168.0.20', 59878)
13:17:47 DNSServer: Domain: a3.mzstatic.itunes-apple.com.akadns.net
13:17:47 DNSServer: ***forward request
13:17:47 DNSServer: -> DNS response from higher level
13:17:47 DNSServer: DNS request received!
13:17:47 DNSServer: Source: ('192.168.0.20', 54067)
13:17:47 DNSServer: Domain: a4.da1.akamai.net
13:17:47 DNSServer: ***forward request
13:17:47 DNSServer: -> DNS response from higher level
13:17:47 DNSServer: DNS request received!
13:17:47 DNSServer: Source: ('192.168.0.20', 49352)
13:17:47 DNSServer: Domain: a5.da1.akamai.net
13:17:47 DNSServer: ***forward request
13:17:47 DNSServer: -> DNS response from higher level
13:17:48 DNSServer: DNS request received!
13:17:48 DNSServer: Source: ('192.168.0.20', 52011)
13:17:48 DNSServer: Domain: a2.da1.akamai.net
13:17:48 DNSServer: ***forward request
13:17:48 DNSServer: -> DNS response from higher level
13:17:48 DNSServer: DNS request received!
13:17:48 DNSServer: Source: ('192.168.0.20', 55797)
13:17:48 DNSServer: Domain: a1.mzstatic.com
13:17:48 DNSServer: ***forward request
13:17:48 DNSServer: -> DNS response from higher level
13:18:16 DNSServer: DNS request received!
13:18:16 DNSServer: Source: ('192.168.0.20', 60594)
13:18:16 DNSServer: Domain: a2.da1.akamai.net
13:18:16 DNSServer: ***forward request
13:18:16 DNSServer: -> DNS response from higher level
13:18:52 DNSServer: DNS request received!
13:18:52 DNSServer: Source: ('192.168.0.20', 57325)
13:18:52 DNSServer: Domain: a3.da1.akamai.net
13:18:52 DNSServer: ***forward request
13:18:52 DNSServer: -> DNS response from higher level
13:18:52 DNSServer: DNS request received!
13:18:52 DNSServer: Source: ('192.168.0.20', 64353)
13:18:52 DNSServer: Domain: a1.da1.akamai.net
13:18:52 DNSServer: ***forward request
13:18:52 DNSServer: -> DNS response from higher level
13:18:52 DNSServer: DNS request received!
13:18:52 DNSServer: Source: ('192.168.0.20', 56099)
13:18:52 DNSServer: Domain: a2.da1.akamai.net
13:18:52 DNSServer: ***forward request
13:18:52 DNSServer: -> DNS response from higher level
13:18:52 DNSServer: DNS request received!
13:18:52 DNSServer: Source: ('192.168.0.20', 53417)
13:18:52 DNSServer: Domain: a5.da1.akamai.net
13:18:52 DNSServer: ***forward request
13:18:52 DNSServer: -> DNS response from higher level
13:18:53 DNSServer: DNS request received!
13:18:53 DNSServer: Source: ('192.168.0.20', 53788)
13:18:53 DNSServer: Domain: a4.da1.akamai.net
13:18:53 DNSServer: ***forward request
13:18:53 DNSServer: -> DNS response from higher level
13:21:29 DNSServer: DNS request received!
13:21:29 DNSServer: Source: ('192.168.0.20', 60690)
13:21:29 DNSServer: Domain: e673.e9.akamaiedge.net
13:21:29 DNSServer: ***forward request
13:21:29 DNSServer: -> DNS response from higher level
13:21:29 DNSServer: DNS request received!
13:21:29 DNSServer: Source: ('192.168.0.20', 55541)
13:21:29 DNSServer: Domain: upp.itunes.apple.com
13:21:29 DNSServer: ***forward request
13:21:29 DNSServer: -> DNS response from higher level
13:21:41 DNSServer: DNS request received!
13:21:41 DNSServer: Source: ('192.168.0.20', 61032)
13:21:41 DNSServer: Domain: mesu.apple.com
13:21:41 DNSServer: ***restrain request
13:21:41 DNSServer: -> DNS response: 192.168.0.17
13:24:26 PlexConnect: Shutting down.
13:24:26 WebServer: Shutting down (HTTPS).
13:24:26 WebServer: Shutting down (HTTP).
13:24:26 DNSServer: Shutting down.
13:24:26 PlexConnect: shutdown

**Comment by iBaa** [comment]
There has to be the apple trailer app...
anybody heard of a missing trailers app?

**Comment by roidy** [comment]
>it seems that there is no trailers app on ATV3 7.3 (french)
 trailers are everywhere when you choose the movies option

When I set my ATV3 to French I still get the Trailers app... make sure you haven't hidden it, go to Settings->Main Menu and make sure Trailers is set to "Show"

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
