### ISSUE TITLE
Delete Files after watching

### ISSUE THREAD

**Issue by tjenvy** [iBaa/PlexConnect#371]
Many people utilize plex and a number of other resources for localized one time content.  I have researched this topic extensively but still no resolution.  It appears requests have been made dating back to 2011 for the ability to delete files directly without the need to go back to the media server and delete them.  

This function is there on other clients, however it seems to be missing from plexconnect.  I have seen reference to a roadmap for this but no progress or updates.

Dont get me wrong I am VERY thankful for this software and its creators!!!

I am happy to test beta versions or whatever is needed to get this working. Please reach out to me and I will help in any way I can.

Thank You.

**Comment by moodyblue** [comment]
PlexConnect has been enhanced to allows users to delete content, therefore I'm closing this request.
