### ISSUE TITLE
[REQUEST] Playlist Feature / AutoPlay

### ISSUE THREAD

**Issue by alzeric** [iBaa/PlexConnect#372]
I saw another issue on the board, requesting the ability to play the next episode in the season (sorta how Netflix or Now YouTube's AutoPlay works) I think that is a great idea, I for one would love to see this as I have small children and would like to be able to let their shows continuously play throughout the day, without them having to use the remote to navigate plex connect.

I also would like to request a Playlist feature to be able to queue up different shows for the children to watch, so it's not all the same show all the time.

Thank you for our consideration on this feature(s).

**Comment by Drewbie1974** [comment]
Playlists already exists.  Make a playlist in plex web and then select playlists from the top menu of the first screen after entering plex connect.

Continuous play is also available if you enter the show/season and start playing from the list, once the episode ends the next auto starts

**Comment by alzeric** [comment]
Thanks didn't realize it also pulled the playlist from Plex.

**Comment by farmboi** [comment]
Yeah that works or if you go all the way into the season, it will continue to play. Would be nice if we could mimick the interface like how Netflix's is and show you the next video and give a description of it. 

It would also be nice to prompt to play the next episode if one exists when playing the show from On Deck.

**Comment by Rycochet** [comment]
So this:
* "Season View" = auto-continue, popup showing next episode synopsis and countdown to play (Menu button to come out) - "Playing in xx seconds, press Menu to cancel"
* "On Deck" = auto-quit to "On Deck", popup showing next episode synopsis and countdown to quit - "Quitting in xx seconds, press Play to watch"

Not sure if that's even possible, but hopefully someone who knows the code will be able to comment - I do like that idea though, maybe for the last 10 seconds (user option to change) :-)

**Comment by aredondo** [comment]
An issue that I've found when starting to play a series from the season view is that subtitles won't play. I need to go into the chapter and play from there for subtitles to work—and then the next chapter won't play automatically.

Does anyone have the same issue?

**Comment by farmboi** [comment]
Yeah. It has to be doable if Netflix and YouTube can. I'm sure Baa could
figure it out.

**Comment by almontef** [comment]
I have never gotten autoplay to work. If I go into a series and start playing an episode it does not autoplay the next episode. Is there a setting that needs to be enabled that I may have missed?  Running Plexconnect .5 on ATV3. Any suggestions would be welcomed. Thanks in advance.

**Comment by CyberGhost84** [comment]
Press the "Play" button on the remote on an episode than the next episode schould start automatically.. By pressing the "Enter" button on the remote it will just play the selected episode..

**Comment by almontef** [comment]
Thanks @cyberghost84. That did the trick!!

**Comment by CyberGhost84** [comment]
nice :)
