### ISSUE TITLE
Poster Art for Folder View

### ISSUE THREAD

**Issue by cbradley66** [iBaa/PlexConnect#373]
Hey is there any way to enable art to show in place of the generic folder icon in folder view? It seems that this is not a Plex feature yet or am I missing something? It seems crazy to me as I organize all of my movie series into folders and so have a swath of generic folder icons in folder view. Does PlexConnect have a method to show art on folders?

Many thanks

**Comment by roidy** [comment]
No, for two main reasons:-
1. As you said, it's not a Plex feature, Plex doesn't return any artwork in the xml for folders
2. Folders are general containers and could contain multiple items, for example I have a folder called holiday videos that contains about 30 videos, which artwork from which video would you use.

**Comment by cbradley66** [comment]
Oh ok. I also run ATV Flash and it does show the folder with an image of choice by putting an image file inside the folder with the same name as the folder

On Sep 5, 2015, at 3:12 PM, roidy <notifications@github.com<mailto:notifications@github.com>> wrote:


No, for two main reasons:-
1. As you said, it's not a Plex feature, Plex doesn't return any artwork in the xml for folders
2. Folders are general containers and could contain multiple items, for example I have a folder called holiday videos that contains about 30 videos, which artwork from which video would you use.
