### ISSUE TITLE
DNS forwarding timeout

### ISSUE THREAD

**Issue by newhook** [iBaa/PlexConnect#375]
I get frequent hangs with netflix. Looking at the logs I see mostly see when this occurs:

```
19:35:50 DNSServer: -> DNS response from higher level
19:35:50 DNSServer: DNS request received!
19:35:50 DNSServer: Source: ('192.168.2.3', 59893)
19:35:50 DNSServer: Domain: securemetrics.apple.com
19:35:50 DNSServer: ***forward request
19:35:50 DNSServer: -> DNS response from higher level
19:35:53 DNSServer: DNS request received!
19:35:53 DNSServer: Source: ('192.168.2.3', 49924)
19:35:53 DNSServer: Domain: api-global.netflix.com
19:35:53 DNSServer: ***forward request
19:35:53 DNSServer: -> DNS response from higher level
19:35:53 DNSServer: DNS request received!
19:35:53 DNSServer: Source: ('192.168.2.3', 59893)
19:35:53 DNSServer: Domain: securemetrics.apple.com
19:35:53 DNSServer: ***forward request
```

Note in the final case there is no response to the DNS query to securemetrics.apple.com. Looking at the code there is no retry in the event of a timeout. Shouldn't there be?

**Comment by iBaa** [comment]
Our DNSServer wouldn't do a retry by itself. If no-one answers (timeout) it is designed to just start over and wait for the next request. If aTV thinks the earlier IP resolution is important, it would retry on its own, again pinging PlexConnect.
Do you see anything else in that log, anything after your last line? When introducing an error here, it is either caught (like timeout) or will shut down DNSServer, with a note of just that.

**Comment by newhook** [comment]
Well that doesn't happen. The ATV2 just hangs for a long time.

**Comment by iBaa** [comment]
What system is PlexConnect running on?
What happens when you put a "bad" ip_dnsmaster into settings.cfg?
Here - running MacOS, bad ip_dnsmaster - aTV just keeps poking, while PlexConnect times out... producing the following log:
```
21:02:40 DNSServer: DNS request received!
21:02:40 DNSServer: Source: ('192.168.178.25', 60905)
21:02:40 DNSServer: Domain: itunes.apple.com
21:02:40 DNSServer: ***forward request
21:02:45 DNSServer: DNS request received!
21:02:45 DNSServer: Source: ('192.168.178.25', 55670)
21:02:46 DNSServer: Domain: itunes.apple.com
21:02:46 DNSServer: ***forward request
21:02:51 DNSServer: DNS request received!
21:02:51 DNSServer: Source: ('192.168.178.25', 55670)
21:02:51 DNSServer: Domain: itunes.apple.com
21:02:51 DNSServer: ***forward request
```

**Comment by newhook** [comment]
Its running on archlinux. I'll try later with a bad DNS master.

**Comment by iBaa** [comment]
We might be able to help that, spawning a thread for every outgoing request - just as mentioned in line 410. As long as the main loop stays alive, timing out those request threads shouldn't matter...

**Comment by newhook** [comment]
I changed the forwarding code the following and it is now very reliable.

try:
                        with closing(socket.socket(socket.AF_INET, socket.SOCK_DGRAM)) as DNS_forward:
                            DNS_forward.settimeout(5.0)
                            DNS_forward.sendto(data, (cfg_IP_DNSMaster, 53))
                            paket, addr_master = DNS_forward.recvfrom(1024)
                            # todo: double check: ID has to be the same!
                            # todo: spawn thread to wait in parallel
                            dprint(__name__, 1, "-> DNS response from higher level")
                    except socket.timeout:
                        dprint(__name__, 0, "DNS forward: socket timeout")
                        continue
                    except Exception, e:
                        dprint(__name__, 0, "Failed to create socket on UDP port 49152: {0}", e)
                        continue

**Comment by madmaiike** [comment]
Would that accelerate the interface ? It can take up to 10 seconds before getting my content to display - anyone else has this issue ? plexconnect running on hosted pms server (remote)

**Comment by iBaa** [comment]
newhook: So you think the DNS socket is dying halfways? Or still "busy" when a new request is coming in? Why? And why don't we have to re-create the listening port every now and then?

madmaiike: No, I don't think so. I can't see any reason why this would speed up things. How much stuff to show do you have in your library? How fast is the PlexConnect host? Switch off debug logging, that seems to generate a lot of processor load.

**Comment by madmaiike** [comment]
iBaa : thanks for the reply - not so much actually - when I'm running Plexconnect.py with output on terminal (using Ubuntu 14 on core i7 16 Gb RAM) the python webserver seems a bit slow to deliver static content - ever considered using nginx istead :) ?

**Comment by iBaa** [comment]
nginx - not really. When starting on PlexConnect I was just getting my feet wet with python. Never seen this crazy language before, really. So anything special was way out of my league, just the very basic commands and syntax comparing to Basic from the 90's were the way to go. Okay, slowly it improved, but then I didn't see much gain in a total rewrite.

**Comment by madmaiike** [comment]
iBaa thanks looks like the log level improved things. It was on normal and indeed an i7 can handle this. Oh well it's all good now.

**Comment by newhook** [comment]
If the slow content displaying is caused by DNS lookups this patch could fix it. :) I haven't had any issues since running with this fix... 

@iBaa: No, what happens is as I said in my comment I believe.  What listening port?

**Comment by iBaa** [comment]
listening port: :53, the one aTV talks to.

**Comment by newhook** [comment]
I don't think its necessary to re-open the listening port.

**Comment by iBaa** [comment]
No, don't think so either. ATV opens new connection for every DNS request, look at the used ports in the logs.
And actually right now, it's very similar to the WebServer part. There, too, we open a new connection for every request to PMS, but keep the socket on :80, :443. Hope that helps, though I have never personally seen that issue. :-D
