### ISSUE TITLE
Failed to create socket on UDP port 53 - can't use Ubuntu on OS X 

### ISSUE THREAD

**Issue by cocart** [iBaa/PlexConnect#381]
I keep get this:
Erans-iMac:~ eranzeira$ sudo "/Applications/PlexConnect-master/PlexConnect.py"
18:40:50 PlexConnect: ***
18:40:50 PlexConnect: PlexConnect
18:40:50 PlexConnect: Press CTRL-C to shut down.
18:40:50 PlexConnect: ***
18:40:50 PlexConnect: started: 18:40:50
18:40:50 PlexConnect: Version: 0.5-dev-020615
18:40:50 PlexConnect: Python: 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
18:40:50 PlexConnect: Host OS: darwin
18:40:50 PlexConnect: PILBackgrounds: Is PIL installed? False
18:40:50 PlexConnect: IP_self: 192.168.1.102
18:40:51 DNSServer: started: 18:40:50
18:40:51 DNSServer: Failed to create socket on UDP port 53: [Errno 48] Address already in use
18:40:51 PlexConnect: DNSServer not alive. Shutting down.
18:40:51 PlexConnect: Shutting down.
18:40:51 PlexConnect: shutdown
18:40:51 PlexConnect: shutdown
Erans-iMac:~ eranzeira$ 

I tried using Ubuntu, but it is for windows not for osx..
please advice.

**Comment by iBaa** [comment]
I don't understand the story about Ubuntu, Windows, OS X...

But then, there seems to be something sitting on your DNS port already. Try to find out, which process this might be.

**Comment by cocart** [comment]
nothing is there, I killed all of 53 port sitters. 
it might be El Capitan? is it support El Capitan?

Eran Zeira
coca interactive
+972 52 4717242
www.coca.co.il




‫ב-4 באוק׳ 2015, בשעה 22:41, ‏‏iBaa ‏<notifications@github.com> כתב/ה:‬

**Comment by joswart** [comment]
I found a similar issue on the plex forums. Might want to have a look there as well: http://forums.plex.tv/discussion/comment/1019092/#Comment_1019092

**Comment by wahlmanj** [comment]
Did you reboot OS X yet?

**Comment by cocart** [comment]
Sure, all the time.
and I keep getting this:

Erans-iMac:~ eranzeira$ sudo /Applications/PlexConnect-master/PlexConnect.py

Password:

09:44:51 PlexConnect: ***

09:44:51 PlexConnect: PlexConnect

09:44:51 PlexConnect: Press CTRL-C to shut down.

09:44:51 PlexConnect: ***

09:44:51 PlexConnect: started: 09:44:51

09:44:51 PlexConnect: Version: 0.5-dev-020615

09:44:51 PlexConnect: Python: 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015,
09:33:12)

[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

09:44:51 PlexConnect: Host OS: darwin

09:44:51 PlexConnect: PILBackgrounds: Is PIL installed? False

09:44:51 PlexConnect: IP_self: 192.168.1.102

09:44:51 DNSServer: started: 09:44:51

09:44:51 DNSServer: Failed to create socket on UDP port 53: [Errno 48]
Address already in use

09:44:51 PlexConnect: DNSServer not alive. Shutting down.

09:44:51 PlexConnect: Shutting down.

09:44:51 PlexConnect: shutdown

09:44:51 PlexConnect: shutdown

Erans-iMac:~ eranzeira$










<http://www.coca.co.il>
------------------------------------
Eran Zeira | 052-471-7242
------------------------------------
  <https://plus.google.com/u/0/b/107918846748496703769/+CocaCoIl>
<https://www.linkedin.com/company/399701>
<https://www.youtube.com/user/cocainteractive1> [image: twitter]
<https://twitter.com/cocainteractive>  <eran@coca.co.il>  <052-471-7242>



2015-10-18 6:29 GMT+03:00 wahlmanj <notifications@github.com>:

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
