### ISSUE TITLE
Issues with PlexConnect

### ISSUE THREAD

**Issue by hawkeye64** [iBaa/PlexConnect#382]
On my ATV I get everything, until I go into one of the sections and then it says "Accessing Trailers". And, does so until it times out.

I notice a couple of issues in the log file:

After gathering up the XML, I get this:

14:55:51 XMLConverter: ====== aTV-XML finished ======
14:55:51 Settings: getsetting allow_gzip_atv=False
14:55:51 WebServer: File Not Found:
Traceback (most recent call last):
  File "D:\GitHub\PlexConnect\WebServer.py", line 230, in do_GET
    self.sendResponse(XML, 'text/xml', True)
  File "D:\GitHub\PlexConnect\WebServer.py", line 92, in sendResponse
    self.end_headers()
  File "C:\Python27\lib\BaseHTTPServer.py", line 412, in end_headers
    self.wfile.write("\r\n")
  File "C:\Python27\lib\socket.py", line 324, in write
    self.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine

What file is it looking for here (third line from the log file)?

The other issue is that I am now continually getting DNS error 10054. Not always, but a LOT. 10.0.1.6 is my ATV.

14:56:41 DNSServer: DNS request received!
14:56:41 DNSServer: Source: ('10.0.1.6', 64928)
14:56:41 DNSServer: Domain: upp.itunes.apple.com
14:56:42 DNSServer: ***forward request
14:56:42 DNSServer: -> DNS response from higher level
14:56:42 DNSServer: Warning: DNS error (10054): An existing connection was forcibly closed by the remote host

I started getting these after my last Plex update, where everyone go a free certificate. I'm not sure if that is the problem. I realized there could be other issues, so I restored my ATV, recreated a new certificate (the last one was for 365 days, new one is 8000+ days) and still have the same issue.

I'm at a loss. I searched for others that may be having this same issue and don't seem to see any so maybe it's just me, I don't know.

Here's my cfg file (which has worked for the past year or so):

[PlexConnect]
enable_plexgdm = True
ip_pms = 127.0.0.1
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = True
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = High
logpath = .

Any insight into my issues would be appreciated.

**Comment by hawkeye64** [comment]
It occurred to me that maybe I needed to update PlexConnect to work with this latest Plex, so I did that. Now I get the following:

15:15:21 WebServer: serving .xml: /library/sections
15:15:21 XMLConverter: ---------------------------------------------
15:15:21 XMLConverter: PMS, path: owned /library/sections 
15:15:21 XMLConverter: Initial Command: Library_View
15:15:21 XMLConverter: Split Directory: Library Command: View
15:15:21 XMLConverter: XMLTemplate: Library/View.xml
15:15:21 XMLConverter: ---------------------------------------------
15:15:21 PlexAPI: URL: http://10.0.1.150:32400/library/sections
15:15:21 PlexAPI: xargs: {'X-Plex-Platform': 'iOS', 'X-Plex-Model': '3,1', 'X-Plex-Client-Platform': 'iOS', 'X-Plex-Client-Identifier': 'C07GGBVFDDR5', 'X-Plex-Device': 'AppleTV', 'X-Plex-Product': 'PlexConnect', 'X-Plex-Platform-Version': '6.2.1', 'X-Plex-Version': '0.5-dev-020615'}
15:15:22 PlexAPI: No Response from Plex Media Server
15:15:22 PlexAPI: We failed to reach a server. Reason: Unauthorized
15:15:22 PlexAPI: Traceback:
Traceback (most recent call last):
  File "D:\GitHub\PlexConnect\PlexAPI.py", line 378, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized


So, "Unauthorized" it is. I'm still at a loss. Suggestions?

**Comment by abetancort** [comment]
Did you turn `Secured Connections` to **REQUIRED** instead than the default **PREFERRED**. If you did so that could be why plexconnect is failing on you; it does not support secured connections yet so change it to **PREFERRED** and see if that works for you.

**Comment by hawkeye64** [comment]
No. It's on Preferred. The reason I was getting "Unauthorized" is because I didn't have my ATVSettings.cfg set up when I got the latest from GIT. I fixed that. So, now I am back to my original issue which is the "Accessing Trailers" just spinning until it times out.

From the log file:
16:48:33 XMLConverter: ====== aTV-XML finished ======
16:48:33 Settings: getsetting allow_gzip_atv=False
16:48:33 WebServer: File Not Found:
Traceback (most recent call last):
  File "D:\GitHub\PlexConnect\WebServer.py", line 230, in do_GET
    self.sendResponse(XML, 'text/xml', True)
  File "D:\GitHub\PlexConnect\WebServer.py", line 92, in sendResponse
    self.end_headers()
  File "C:\Python27\lib\BaseHTTPServer.py", line 412, in end_headers
    self.wfile.write("\r\n")
  File "C:\Python27\lib\socket.py", line 324, in write
    self.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine

Still getting that pesky "File not found" which is likely the error. If I had to guess, it can't find the generated XML to serve to ATV.

**Comment by abetancort** [comment]
Try this...

1.   Install plexconnect using **git** directly from the **master branch** of this **GitHub Repo**. 
1.   If you already did that then force a full git reset using the following command **`git reset --hard`** execute it from your plexconnect app folder and then proceed by issuing a **`git pull`** in the same folder; that way so you'll be sure to get a fresh full install of the latest commit from the master branch. (**Observation**: Depending on your system or user configuration *it may be necessary to prepend the* ***git commands*** *with the full path to the bin folder inside of your git installation*).     

**Note:** I'm pretty sure your config files will not be overwritten, **but better safe than sorry**, so first make a copy of them to another folder!

**Comment by chronicza** [comment]
Hi , have the exact same issue , I managed to find a slight fix by unclaiming my server.  this allows plex connect to connect to the server and play my media, however it has a negative side effect , now my xbox plex app cannot detect the server.

**Comment by gleep52** [comment]
Hawkeye - did you ever solve this issue?  I'm facing the same problem.  10053.

**Comment by Cyb3rGh05t** [comment]
Add the IP of PlexConnect device to the List of allowed divec without authentification on network in server settings.

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
