### ISSUE TITLE
No library Access with Secure Connection "Required"

### ISSUE THREAD

**Issue by I-RiX-I** [iBaa/PlexConnect#383]
Hi, I am super glad how well PlexConnect works with my AppleTV (3rd Gen).

With the Icon hack incorporated it pretty much feels like a standalone app on the device. That is without any jailbreak at all!

Since I share my PMS remotely, I would be happy to set Secure Connection to "Required", but this option blocks PlexConnect from accessing the server.

Any chance this will be fixed (as in: SSL support for PlexConnect)?

**Comment by Rycochet** [comment]
Already an open issue: #352

**Comment by I-RiX-I** [comment]
Sorry for the Duplicate
