### ISSUE TITLE
[REQUEST] Hide Library Option

### ISSUE THREAD

**Issue by I-RiX-I** [iBaa/PlexConnect#384]
My PMS has different libraries of which I would only want to use Movies/Music/Shows on the aTV

Would there be an easy way to implement hiding the others (Pictures/Home Videos/Audiobooks) per library? A long press currently only opens a search dialogue.

**Comment by iBaa** [comment]
Use another PlexHome user and only share some?
PlexConnect was never meant to host a database for such a feature, it's only a stupid client forwarding everything your PMS is serving.

**Comment by I-RiX-I** [comment]
Sounds reasonable. Thank you for this project & the great support.
