### ISSUE TITLE
[Reuest] Wake on Lan

### ISSUE THREAD

**Issue by I-RiX-I** [iBaa/PlexConnect#386]
My server hibernates between 22:00 and 16:00 on weekdays and 8:00 on the weekend if there are no connections to it.

I run PlexConnect on my raspberry pi which is on 24/7 and functions as my webserver/reverse proxy.

Is there any way to add Wake on Lan to PlexConnect?

This doesnt need to be implemented in this main project,

All I am looking for is a simple hack to execute ```wakeonlan SO:ME:MA:CA:DR``` (outside of python)
before the main menu is sent to the atv.

Currently I use Jeremy Blums Remote WOL Script (php) on my server which calls the above programm from php. Is that possible in python as well?

Would be super glad if you could help me save some energy!

**Comment by iBaa** [comment]
Hm, I have no experience with that stuff at all. But google brings a couple of probably suitable result when searching:
https://www.google.de/search?client=safari&rls=en&q=wakeonlan+python&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=TjcZVseDBsSI8QfMyZmYAQ
http://code.activestate.com/recipes/358449-wake-on-lan/
http://stackoverflow.com/questions/28765352/wakeup-on-lan-with-python
Have a look... it doesn't seem to be to complicated.

**Comment by I-RiX-I** [comment]
Thanks for the help. I figured it out!

If someone wants to work on this please look at:
https://github.com/I-RiX-I/PlexConnect/commit/97813df40cb0e1659b656635d798772d11c0cc7b
