### ISSUE TITLE
no internet connection = no plexconnect - anybody have an offline solution?

### ISSUE THREAD

**Issue by ttdkr3w** [iBaa/PlexConnect#387]
currently having an ongoing issue with my isp.

as soon as I loose my internet connection, the ate does this:

![fullsizerender](https://cloud.githubusercontent.com/assets/12859665/10413248/75c1e1e6-6ffe-11e5-943c-8b19e1ef71c6.jpg)

as soon as the connection is back, its back to normal

how can I edit plexconnect to work both online and offline?

no internet connection = no plexconnect - anybody have an offline solution?

**Comment by finkdiff** [comment]
This is true of any ATV app.

**Comment by finkdiff** [comment]
You could briefly tether using a smartphone to get the apps to appear.

**Comment by ttdkr3w** [comment]
so its apple not plex?

**Comment by finkdiff** [comment]
Yep, see this for a rundown of why: http://www.appletvhacks.net/2014/03/04/how-apple-adds-new-channels-to-apple-tv/

**Comment by ttdkr3w** [comment]
cheers

**Comment by ttdkr3w** [comment]
do you know much about the transcoding process?

**Comment by finkdiff** [comment]
What specifically?

**Comment by ttdkr3w** [comment]
hi

60% of my content is compressed 1080p 1-5GB all of these play fine on plexconnect without missing a beat, the other 40% of my content is 10-40GB+ in size 1080p, through atv plexconnect at times they play mint, sometimes they rebuffer every few minutes or not at all. I have transcoder action set to 'auto'. transcoder quality to 1080p 40mbps. remote bitrate 1080p 40mbps.

What are the best settings for smooth playback? Or is it dependant on processor power?

I have a 2.3ghz i7 quad core mac mini with 32gb ram and 1tb ssd with a 4 bay 6tb thunderbolt raid as my content library.


thanks

nick




> On 12/10/2015, at 7:16 AM, f00b4r <notifications@github.com> wrote:
> 
> What specifically?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/iBaa/PlexConnect/issues/387#issuecomment-147232453>.
> 

Nick Porter
+64275235678
ttdkr3w@gmail.com

**Comment by finkdiff** [comment]
That is powerful enough to transcode anything but there are a some potential issues: 

the ATV has limits on what it can play 

PlexConnect decides whether to ask for a transcode of the file based upon certain criteria and the PMS also has a profile it checks as well (if memory serves this does not differentiate between the ATV2 and ATV3).

In theory if the file cannot be played it should get transcoded but the profiles and logic are designed for the 99.9% of files and some edge cases can cause issues. Also if the file isn't in proper specification eg number of reference frames then you might also see issues. 

You might also see issues if you have network problems or use wifi but I guess you should be able to tell by seeing if it is the same files giving the problems or if it is intermittent issues.

If you can narrow it down to specific files then check the wiki for how to get media info on them and creates a thread in the forums.

**Comment by ttdkr3w** [comment]
Cheers

Nick Porter
ttdkr3w@gmail.com
+64275235678

**Comment by ferantivero** [comment]
@finkdiff and what if in this case (without an internet),  plexconnect provide us with the latest well-known-storefront file. Is that something possible?

**Comment by iBaa** [comment]
No... unfortunately Apple has added another layer of security (signature and such things) to their Storefront. We did play around with that, but aTV hasn't accepted files, that didn't directly come from Apple's servers.

**Comment by ferantivero** [comment]
the idea is to cache and retrieve exactly the same that would had been originally fetched from Apple's server(s). I'm sure you guys have already tried such thing (just double checking)

**Comment by wahlmanj** [comment]
If you lose your ISP and do not reboot your aTV all the icons will stay. Simply log out of myplex on your PMS server and PlexConnect will still work on your aTV(s).
