### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by madmaiike** [iBaa/PlexConnect#388]
Hey iBaa,

Great work on PlexConnect - I don't really have an issue more of a question. Is there a way I could see live the DNS requests and their content (or a log) that are sent ?

Thanks a lot

**Comment by iBaa** [comment]
There are a couple of debug print lines plus helper function in DNSServer.py. For example:
```
                #print "incoming:"
                #printDNSdata(data)
```
or
```
                #print "-> respond back:"
                #printDNSdata(paket)
```
Uncomment them and give it a try...
Also there is a comments section about the actual DNS protocol with link to the info's source.

Does that answer help you with your investigation?

**Comment by madmaiike** [comment]
I've been looking at that code. I'll give it a try. Thanks a lot !

Envoyé de mon iPhone
