### ISSUE TITLE
latest version errors re-architect discovery

### ISSUE THREAD

**Issue by miniop** [iBaa/PlexConnect#389]
Getting errors with the latest release and the library doesn't show up.
I revert back

http://jpst.it/CDBc

**Comment by iBaa** [comment]
The log shows, that aTV was still in a Plex session, while PlexConnect was restarted. That way PlexConnect looses connection to your PMS - a "discover" is needed.
Please exit out of trailers, and try again!

**Comment by miniop** [comment]
I tried to logout from trailer and login and it appears same problem.

<MediaContainer size="1"><Device name="Server" product="Plex Media Server" productVersion="0.9.12.16.1509-8e31408" platform="Windows" platformVersion="6.2 (Build 9200)" device="PC" clientIdentifier="a4fef6b9314188c7df82296d3c4041037xxxxx" createdAt="1383671352" lastSeenAt="1445688155" provides="server" owned="0" httpsRequired="0" ownerId="996571" home="1" accessToken="xxxxxxxxx" sourceTitle="miniop" synced="0" publicAddressMatches="0" presence="1"><Connection protocol="https" address="xxxxxxx" port="32400" uri="https://xxx-xxxx-xxxx-xxx.d21de88cf1a54b9b84b472ae692a636e.plex.direct:32400" local="0"/></Device></MediaContainer>

**Comment by iBaa** [comment]
Any chance to check the XML as stated above?

**Comment by miniop** [comment]
ya http://pasted.co/b8c41070

**Comment by iBaa** [comment]
That is so strange...
a) you only have one - remote - connection shown.
b) ```publicAddressMatches="0"``` as well points to a remote server.
Both data points should lead to a fully functional discovery process...
Did you grab the XML from the computer running PlexConnect? If you didn't... is that one on another subnet? Is it "local" to the PMS?

**Comment by miniop** [comment]
hey @baa which XML are you saying ? Let me know so i can install again the latest version and check it.
The server and plexconnect is on a dedicate server and it has public internet ip

**Comment by iBaa** [comment]
The pasted one...
> ya http://pasted.co/b8c41070
Where did you request it from? Are you able to pull it in from the PlexConnect host?

**Comment by miniop** [comment]
correct it was from the server the time the plexconnect was running

**Comment by depraved22** [comment]
Hmm. Same issue/logs for me as well. 

I did a git pull today from the server running plex and doesn't work anymore.

**Comment by depraved22** [comment]
I am working as I just logged out and logged back in and that fixed it for me.

**Comment by iBaa** [comment]
minion - your posted log (http://pasted.co/b8c41070) is missing the closing XML tags. Could you please post the complete myplex response? Does it also miss a second connection?

**Comment by miniop** [comment]
@iBaa  its working now !

**Comment by balkce** [comment]
This last commit made my Apple TV not be able to connect, showing "No Plex Libraries found". Reverted to the one before and it worked again. Don't know what you did, but it's a big no no from me.

There was an error on the log:

14:14:53 PlexAPI: ***
14:15:14 PlexAPI: No Response from Plex Media Server
14:15:14 PlexAPI: We failed to reach a server. Reason: timed out
14:15:14 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/Applications/PlexConnect/PlexAPI.py", line 406, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

14:15:14 PlexAPI: Servers (local, plex.tv, MyPlex): 1
14:15:14 WebServer: serving .xml: /PlexConnect.xml
14:15:14 WebServer: serving /js/utils.js
14:15:14 WebServer: serving /js/handlePlexConnectNavbar.js
14:15:14 WebServer: serving .xml: /library/sections
14:15:14 WebServer: serving /js/utils.js
14:15:14 WebServer: serving /js/sectionHoldSelect.js
14:16:40 WebServer: Shutting down (HTTP).


The DNS redirection was working though.

**Comment by iBaa** [comment]
Any chance of more log information - with loglevel=High?
