### ISSUE TITLE
Local Server Not Found

### ISSUE THREAD

**Issue by CyberGhost84** [iBaa/PlexConnect#391]
hi all :)

After the 2 last commits i do not get PlexConnect to work:( it shows in log that it founds 3 servers but it only shows up 2 Servers under Settings Tab in PlexConnect. and these are my shared servers, so on Library tab i get a NO PLEX MEDIA SECTION AVAILABLE. i am signed into Myplex and everything.

thanks for any help.

Traceback (most recent call last):
  File "/Applications/PlexConnect/PlexAPI.py", line 406, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

13:03:06 PlexAPI: Servers (local, plex.tv, MyPlex): 3

**Comment by iBaa** [comment]
As always... whole log, loglevel="High". :-D
Two ideas, though:
- your local server is not published - unlikely, as it seemingly tries to access it.
- PlexConnect is trying to use https now, with those direct plex (or whatever) hostnames. Possibly your router prevents resolution of a name resulting in a local addresses (my understanding - I will check how that feature is called)? There should be a white list somewhere in the setup to allow specific hostnames. But then... from the router point of view, it is deemed a security issue. Now why we need to accept that in order to use https is a mystery to me... :-D

**Comment by CyberGhost84** [comment]
Found somthing for Fritzbox routers..

http://en.avm.de/service/fritzbox/fritzbox-7390/knowledge-base/publication/show/663_No-DNS-resolution-of-private-IP-addresses/

Could it be that?

**Comment by CyberGhost84** [comment]
here's my full log at High Level :

https://www.dropbox.com/s/sennnolex1fsdw4/PlexConnect.log%202.zip?dl=0

Thx baa

**Comment by CyberGhost84** [comment]
i found this in my routers network settings:

https://www.dropbox.com/s/lpf81ctlas61nf2/Screen%20Shot%202015-10-29%20at%2013.56.17.zip?dl=0

so now i don't know or don't understand what i have to add in here? how can i find out a domain name? first time i had to do something like that i really don't know what exactly i have to do/add.

**Comment by iBaa** [comment]
Yep, that's the place for the "white list". Add "plex.direct" there. That's the domain Plex uses for the https stuff.

**Comment by CyberGhost84** [comment]
thx baa that made it for me :) works perfectly now :)
