### ISSUE TITLE
[Suggestion] QNAP (NAS) App

### ISSUE THREAD

**Issue by Rycochet** [iBaa/PlexConnect#397]
Going to put this out there - not got the time (or direct knowledge), so hopefully someone else reading this will have ;-)

There are simple(ish) instructions on the Plex forums for getting PlexConnect running on it, but only when running in the most simple setup...

An App would be able to put a proxy forward into Apache (which annoyingly resets it's config on any update / change of options) and launch automatically. It could also start PlexConnect automatically after reboots, and automatically update regularly.

http://wiki.qnap.com/wiki/QPKG_Development_Guidelines and http://download.qnap.com/dev/QDK_2.0.pdf

**Comment by Rycochet** [comment]
First pre-release out there now - https://github.com/Rycochet/PlexConnect-QNAP/releases/tag/v0.1-alpha - there's a bug somewhere that's stopping my QNAP from auto-running the script (read the release notes), but it's 4am, and I'm off to bed - I'll try and track it down over the next couple of days ;-)

**Comment by moodyblue** [comment]
Thanks for your work. If you decide to continue with it let's discuss in the forum.
