### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by miniop** [iBaa/PlexConnect#398]
I am getting an error today and the library doesnt show up : 

54:36 PlexAPI: poke plex.tv - request Plex Media Server list
15:54:36 PlexAPI: ***
15:54:37 PlexAPI: No Response from Plex Media Server
15:54:37 PlexAPI: We failed to reach a server. Reason: [Errno 11001] getaddrinfo failed
15:54:37 PlexAPI: Traceback:
Traceback (most recent call last):
  File "C:\PlexConnect-master\PlexAPI.py", line 406, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

15:54:37 PlexAPI: Servers (local, plex.tv, MyPlex): 1
15:54:46 PlexAPI: ***
15:54:46 PlexAPI: poke plex.tv - request Plex Media Server list
15:54:46 PlexAPI: ***

I tried to logoff login again but same problem

**Comment by iBaa** [comment]
a) loglevel=High
b) PMS correctly published?
c) Router: DNS rebind to local network allowed?

**Comment by Rycochet** [comment]
The most recent Plex server build died on my system at some point last night - though it was showing as still running - manually stopping and restarting Plex itself might be the solution (I restarted PlexConnect itself first, as it was also not responding).

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
