### ISSUE TITLE
Error writing media: 32 - Broken pipe

### ISSUE THREAD

**Issue by jowandijkhuis** [iBaa/PlexConnect#399]
PlexConnect can't play MKV files from my Plex Media Server but MP4 files works fine.
Is anyone here familiar with this error?

PlexConnect 0.5-dev-211015 (MacOSX 10.11.1)
ATV 2 (iOS 5.2 Jailbroken)
Plex Media Server 0.9.12.19.1537-f38ac80

![img_3538](https://cloud.githubusercontent.com/assets/593324/11022561/a63e2950-8661-11e5-991f-82179a8d5745.jpg)

**Comment by iBaa** [comment]
Logs?
Settings to force "Direct Play"?

**Comment by jowandijkhuis** [comment]
Removed PlexConnect from OSX. Now using [OpenPlex] (https://github.com/wahlmanj/OpenPlex) with latest PlexConnect (0.5-dev-211015). No 32 broken pipe error in this setup. Issue closed.
