### ISSUE TITLE
Music files DirectPlay (such as ALAC)

### ISSUE THREAD

**Issue by moodyblue** [iBaa/PlexConnect#400]
PlexConnect does decides correctly when to transcode (or DirectPlay) music files. XMLConverter.py uses maxbitrate=384, which is incorrect. The limit for mp3, drm, aac and ac3 should be 320, alac, aiff and wav (the non-compressed audio formats supported by the ATV) should have no bitrate limit.

**Comment by moodyblue** [comment]
Thanks

**Comment by moodyblue** [comment]
maxAudioBitrateUncompressed = '1000' is insufficient, suggest that this value is increased to 1500

**Comment by moodyblue** [comment]
Please correct this issue, maxAudioBitrateUncompressed has to be 1500 instead of 1000

**Comment by iBaa** [comment]
Current "lowest bitrate limit" (the one for 480p video) is 2Mbps. Maybe we should just align it with that number? At least it would be somewhat reasonable - any bitrate above this should get limited by the `bitrate setting`.

**Comment by moodyblue** [comment]
Ok, let's go for 2Mbps. Thanks
