### ISSUE TITLE
Starting an episode from season view does not honor subtitle settings

### ISSUE THREAD

**Issue by ksmandersen** [iBaa/PlexConnect#405]
I have configured my Plex server to always enable subtitles. It works fine when starting a movie or TV episode from the summary screen. But it doesn't work when clicking the play button on the remote in the list of episodes in a TV season.

**Comment by iBaa** [comment]
Play button in season view will actually try a continuos play starting at the selected episode. For subsequent videos subtitles are known to not work, but for the first? It should... I guess.

**Comment by ksmandersen** [comment]
Yes, thats right. it starts continous playback. But there aren't any subtitles. Not even on the first episode

**Comment by moodyblue** [comment]
Still a problem ?

**Comment by moodyblue** [comment]
Closed due to inactivity.
