### ISSUE TITLE
DRM and subtitles

### ISSUE THREAD

**Issue by Fredde87** [iBaa/PlexConnect#406]
Hey guys,

Not sure if this is possible from your side as it should really be done on the Plex side of things but I doubt they would care to implement it. But when you format the XML and send it to the Apple TV. Are you able to retrieve the Format of the subtitle stream?

If so, can I add a request that movies/tv shows who's subtitle format is "NONE" has it's Subtitle button removed?

The reason behind this request is that the Plex Scanner detects the subtitle stream in iTunes DRM protected content. It detects the format as "NONE" and therefor a Subtitle button is displayed in PlexConnect for that movie. However selecting the subtitle stream through PlexConnect will not work. It does however work via the normal Apple TV way if you start playing the movie in PlexConnect and then switch on the subtitle by holding in the OK button. So would just like to hide the Subtitles buttons on the movie info page for any DRM protected movies to avoid confusion.

Does that make sense?

**Comment by iBaa** [comment]
Not being able to select the sub in the PrePlay screen is not related to DRMed files, but every "native" or direct play file with embedded subtitles, if I understand your proposal correctly. But then you could change that by forcing a full transcode...
Also, the "..." button would also show mulitple audio streams, wouldn't it?

**Comment by Fredde87** [comment]
Hi iBaa, sorry for the delay, ran into some trouble testing (will create a separate thread about it).

Not sure I understand what you mean? Transcoding is not possible on DRM content for example.

You raised a interesting question though if selecting a different audio language would work. I tested it and whilst it does play if I change it to Spanish, it actually still plays it in English, so the Audio Language/Subtitle function is therefore not needed at all for DRM content. Therefore I would say if it is possible, could we hide the Sub/Audio button if DRM is detected and let the user select it the iOS way whilst in the movie?

**Comment by moodyblue** [comment]
Can you please test with `0.7-dev-020318` or later ?

**Comment by Fredde87** [comment]
Hi moodyblue, unfortunately I no longer work at the same job where we had
this setup. So I am unable to test unfortunately.

**Comment by moodyblue** [comment]
Thanks. Closing this request.
