### ISSUE TITLE
Suggestion for web framework

### ISSUE THREAD

**Issue by sodabrew** [iBaa/PlexConnect#41]
I'd like to suggest a web micro-framework to replace the BaseHTTPServer / CGI setup that can only handle one client at a time.

Survey of current Python web micro-frameworks:
http://www.slideshare.net/r1chardj0n3s/web-microframework-battle

Winner of the survey is Bottle:
http://bottlepy.org/

Cheers!

**Comment by moodyblue** [comment]
I'm closing this because PlexConnect already supports multiple ATV's.
