### ISSUE TITLE
About Plex-Connect master need help no work at all

### ISSUE THREAD

**Issue by XxReNxZ** [iBaa/PlexConnect#411]
i installed that like the instructions and is still not work on my apple tv 3rd 
i would happy for help here and Especially On Skype: sender.hadad

Thanks.

**Comment by iBaa** [comment]
Please check in the Plex forums, I am sure you will find one going with you through the setup remotely.
https://forums.plex.tv/categories/appletv-plexconnect

**Comment by XxReNxZ** [comment]
THANKS

2015-12-29 0:38 GMT+02:00 iBaa <notifications@github.com>:
