### ISSUE TITLE
How to Make PlexConnect Compatible with Synology DSM 6.0b? 

### ISSUE THREAD

**Issue by abetancort** [iBaa/PlexConnect#412]
*Crossposted from __forums.plex.tv AppleTv – Plexconnect__*
 
#### __Plexconnect__ and __Synology DSM 6b__      

Hi everyone, 
  
* *Has anyone managed to get Plexconnect to work under* __DSM 6b__? 
* *Does anyone one knows or has any ideas about the changes that need to be made in the* __DSM Config Files__  (I'm quite sure that all changes need to be done on the configuration of ngnix to properly respond to the requests made by the AppleTV ) *and/or in* __Plexconnect Source__ (I'm don't think anything at all would actually needs to be changed to Plexconnect, other than including in the sprk packages the script to make the changes to DSM 6b config ) *to make them compatible (work) with the way web pages and ports are now dealt on* __DSM 6b__? 
     
I think this would be interesting, useful and not too difficult to implement.  Especially in light that Synology has deprecated the longstanding Apache's ad-hoc role as a reverse proxy in most, if not all, former DSM releases, in favor of the more robust and flexible **ngnix** reverse proxy server.

Thanks and Regards,

*abetancort*

**Comment by iBaa** [comment]
Forum thread moved into PlexConnect section:
https://forums.plex.tv/discussion/201396/how-to-make-plexconnect-compatible-with-synology-dsm-6-0b
I hope you will get more help there... :-D

**Comment by abetancort** [comment]
I hope I get a an indication for a possible solution somewhere, not just for me but for everyone upgrading DSM 6b... Thanks anyways.
