### ISSUE TITLE
How do you guys debug/test PlexConnect?

### ISSUE THREAD

**Issue by pudds** [iBaa/PlexConnect#413]
I'm making a few tweaks for my own use (which I might submit as pull requests if warranted).  It seems like the ideal way to test these changes would be to access from a web browser, but that results in a "Not Serving Client" error.  Adding "Apple TV" to my User-Agent header gets me a step further, but only as far as a "unidentified ATV" error.

Considering the difficulty of testing on an ATV directly, it seems likely that you guys already have something in place for debugging, but on first glance through the code, I'm not seeing it.

Can you describe the methods you use for testing without an Apple TV, assuming you do in fact test that way?

Thanks,
pudds

**Comment by iBaa** [comment]
>Adding "Apple TV" to my User-Agent header gets me a step further, but only as far as a "unidentified ATV" error.

After a fresh start of PlexConnect.py, it needs the chance to do server discovery: `http://<PlexConnect IP>/?PlexConnect=Discover&PlexConnectUDID=<aTV UDID>`
The UDID is important on each subsequent call... it defines which aTV is calling and therefore where to look up the local settings. From a browser you can use your original UDID or some random string...

PlexConnect usually requires a hint to the PMS to trigger. Add `PMS(<PMS IP:Port>)/ as first directory level - i.e. `http://<PlexConnect IP>/PMS(<PMS IP:Port>/library/sections?PlexConnectUDID=<aTV UDID>` should give you the first overview to your library...

There really is no way around debugging the last step from aTV itself, adding a lot of logs to python and js. It's always a hassle, it really is. You never know how aTV will digest your generated XML, though with time you will get kind of feeling for it.
Best approach: Don't do bugs - this avoids the trouble for getting them cleared lateran. :-D

**Comment by pudds** [comment]
Right on, this is a good start, thanks iBaa.

For anyone following along in the future, I'll just clarify based on some trial and error.

The url format appears to be as follows (correct me if I'm wrong, iBaa):

`http://<PlexConnectIP:Port>/PMS(<PlexIP:Port>/library/sections)/<TemplateName>.xml?PlexConnectUDID=<udid>`

In my case, the two URLs I needed to use to get the home template to appear were:

'http://trailers.apple.com/?PlexConnect=Discover&PlexConnectUDID=1234567'

`http://trailers.apple.com/PMS(172.16.0.69:32400/library/sections)/PlexConnect.xml?PlexConnectUDID=1234567` (I used trailers.apple.com for the plexconnect IP, since all requests on my network on that address are forwarded there anyway).

To avoid the initial error with the User Agent, I use a Chrome Extension called "User-Agent Switcher for Chrome", with a user-agent that contains "Apple TV" in the string.

Thanks again iBaa, if I get somewhere with my plan and it seems worthy of a pull request, I'll be in touch.

**Comment by finkdiff** [comment]
Want to share what you are planning, just in case we can save you some time?

**Comment by pudds** [comment]
Sure.  I'm hoping to make PlexConnect refresh in a few spots when navigating through channels.  I have an IPTV channel which would benefit from having the "now playing" data updated when the user stops playing a video, or goes back in the menu structure.

From looking at the ATV XML, I notice that there is a "volatile" attribute in the main menu's XML.  Not sure if I can apply that to the pages that I would like, but I figured I'd start digging in the ATV docs once I found a way to debug.

**Comment by pudds** [comment]
The volatile attribute on the pre play template appears to have done the trick. So much easier than I expected...

Next up is the menus themselves, and some more testing.

**Comment by finkdiff** [comment]
Pretty sure the updating bits were all either by design or in some cases limitations but Baa and Roidy can probably speak to it better.

**Comment by pudds** [comment]
That's fair, ultimately this might just be a personal tweak.  I'm going to look a bit closer at the Plex API as well though - ideally I think a volatile/static decision like this should be able to be controlled by the channel itself.  A channel with a fixed (or mostly fixed) list of items probably doesn't need to be updated all the time.  An IPTV channel like mine though can benefit from it.  If there was a property on the VideoClipObject or ObjectContainer that could be inspected, that would be ideal I think.

**Comment by iBaa** [comment]
> http://trailers.apple.com/PMS(172.16.0.69:32400~~/library/sections~~)/PlexConnect.xml?PlexConnectUDID=1234567

No way... I am pretty sure the path does not flow into the PMS address. PlexConnect.xml - the main menu bar - doesn't need a path, so ignoring the path here doesn't do anything wrong.
`http://trailers.apple.com/PMS(<pmsid>)/PlexConnect.xml?PlexConnectUDID=1234567`

The later templates (with some luck everything but menu bar) are specified by an additional "query" options. Example:
`http://trailers.apple.com/PMS(<pmsid>)/library/sections?PlexConnect=Library_View&PlexConnectUDID=1234567`
One caveat: `<pmsid>` doesn't always specify one specific PMS, but can also hold `all`, `owned`, `shared`. This might actually trigger multiple PMS requests and internally create an overall XML. Make sure the used template supports that combined XML...

**Comment by pudds** [comment]
For some reason, when trying to access without the PlexConnect.xml template in the path I was getting an access denied error in the log.  Not sure why, but specifying the template directly resolved the problem for me.

**Comment by iBaa** [comment]
Yep... for PlexConnect.xml (again, the main manu bar) this is correct. Everything else should specify the template via the query option. Not sure what happens if you add that filename there - it might just get ignored/overwritten by the query-specified template?

**Comment by pudds** [comment]
Oh yes, sorry, I misunderstood.  Yes, I noticed the different path structure for sub-templates.

Thanks again for the help, I think I have a pretty good handle on things now.
