### ISSUE TITLE
Plexconnect works on wireless but not ethernet

### ISSUE THREAD

**Issue by facWiz** [iBaa/PlexConnect#414]
• Your ATV model (2 or 3) and firmware version (found under the ATV settings > general > about > Apple TV software):  **APPLE TV 3, Ver: 7.2(7512)**

• The DNS server set on the ATV (found under the ATV settings > general > network > DNS):
**10.0.0.55**

• The local IP address of the device that PlexConnect is installed on:
**10.0.0.55**

• The device and operating system (including version number) that PlexConnect is installed on:
**Windows 7: Professional SP 1, 64bit, Core 2 Duo, 4GB Ram.**

• The device and operating system (including version number) that the Plex media server (PMS) is installed on:
**Windows 7: Professional SP 1, 64bit, Core 2 Duo, 4GB Ram.**

• The Plex media server (PMS) version number you are running (do not put 'latest'):
**Version 2.4.23**

• The local IP address of the device that the Plex media server (PMS) is installed on:
**10.0.0.55**

• The PlexConnect version number. If using Github source then a time and date of download (look at the creation date of the folder) and if you are using any non-standard setup or a fork.
**2015/12/12**

• The contents of your 'Settings.cfg' file (this is created at first clean shutdown of PlexConnect, using CTR+c)

[PlexConnect.log.txt](https://github.com/iBaa/PlexConnect/files/80259/PlexConnect.log.txt)
[Settings.cfg.txt](https://github.com/iBaa/PlexConnect/files/80258/Settings.cfg.txt)

• Detail on the media file if it is an issue related to playing a media file (in order to get the necessary information on a particular media file go into the Plex web interface, select the video file, when it brings up the page for the media file click on the "i" information button on the left hand side, it will then bring up a "media info" box, click on the "View XML" button, it will then open a browser window with the relevant information, copy this tohttp://www.pastebin.com and use the pastebin link to post the details; posting the information directly in the forum may mess up the formatting and generally takes up a lot of space):

• A detailed description of the issue (the clearer you can make this the better):
**My previous router got struck by lightning and after receiving new router my plexconnect setup no longer functioned while trying to connect using ethernet. To eliminate the cable/ethernet as the cause I tested the cable with other devices and they connect to the internet. While testing cable I also setup the wireless connection which worked 100% apart from the fact that it struggles to stream 1080p content wirelessly and hence my need to get it to work on ethernet. The problem comes in when trying to add a profile via ethernet and it throws out a message _" An error occured while adding the profile [-1009]. Check the url and try again"_ I have deleted and re-added certificates when attempting setup on both methods. When adding a new profile using Wifi there are no issues**

**My setup consists of a VDSL modem dialing the net connection which is connected to my router's WAN port. Previously I had the VDSL modem in bridge mode however bridge mode is disabled in current setup. Previous router was a Asus RT-AC68U and current router is ZyXel NBG6616**

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
