### ISSUE TITLE
Plexconnect ATV3 need help 

### ISSUE THREAD

**Issue by darby007** [iBaa/PlexConnect#415]
Hi install plexconnect to a windows vista ( I know it's a old OS ) my plex server running inthis PC. I also install Python 2,7 and have all the right on the c: drive.
I create the certificates and insert them to the plex connect folder under certificates
I change in the ATV3 the DNS for the PC DNS 
I think I follow all the step:
When I acces trailer in the ATV always have the error message trailers not available.

See bellow the python log

Please help

20:14:07 PlexConnect: ***
20:14:07 PlexConnect: PlexConnect
20:14:07 PlexConnect: Press CTRL-C to shut down.
20:14:07 PlexConnect: ***
20:14:07 PlexConnect: started: 20:14:07
20:14:07 PlexConnect: IP_self: 192.168.1.138
20:14:07 DNSServer: started: 20:14:07
20:14:07 DNSServer: ***
20:14:07 DNSServer: Starting up.
20:14:07 DNSServer: intercept: ['trailers.apple.com', 'atv.plexconnect'] => 192.
168.1.138
20:14:07 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld
.apple.com.edgesuite.net'] => 127.0.0.1
20:14:07 DNSServer: forward other to higher level DNS: 8.8.8.8
20:14:07 DNSServer: ***
20:14:07 WebServer: started: 20:14:07
20:14:07 WebServer: ***
20:14:07 WebServer: WebServer: Serving HTTP on 0.0.0.0 port 80.
20:14:07 WebServer: ***
20:14:07 PlexGDM: ***
20:14:07 PlexGDM: looking up Plex Media Server
20:14:07 PlexGDM: ***
20:14:08 PlexGDM: servers discovered: 1
20:14:08 XMLConverter: PlexGDM - PMS: 192.168.1.138:32400
20:14:23 DNSServer: DNS request received!
20:14:23 DNSServer: Source: ('192.168.1.134', 55561)
20:14:23 DNSServer: Domain: p57-buy.itunes-apple.com.akadns.net
20:14:23 DNSServer: ***forward request
20:14:23 DNSServer: -> DNS response from higher level
20:14:24 DNSServer: DNS request received!
20:14:24 DNSServer: Source: ('192.168.1.134', 50868)
20:14:24 DNSServer: Domain: se-cdn.itunes-apple.com.akadns.net
20:14:24 DNSServer: ***forward request
20:14:24 DNSServer: -> DNS response from higher level
20:14:24 DNSServer: DNS request received!
20:14:24 DNSServer: Source: ('192.168.1.134', 61037)
20:14:24 DNSServer: Domain: itunes.apple.com.edgekey.net
20:14:24 DNSServer: ***forward request
20:14:24 DNSServer: -> DNS response from higher level
20:14:25 DNSServer: DNS request received!
20:14:25 DNSServer: Source: ('192.168.1.134', 53340)
20:14:25 DNSServer: Domain: a3.mzstatic.itunes-apple.com.akadns.net
20:14:25 DNSServer: ***forward request
20:14:25 DNSServer: -> DNS response from higher level
20:14:25 DNSServer: DNS request received!
20:14:25 DNSServer: Source: ('192.168.1.134', 64148)
20:14:25 DNSServer: Domain: a4.da1.akamai.net
20:14:25 DNSServer: ***forward request
20:14:25 DNSServer: -> DNS response from higher level
20:14:27 DNSServer: DNS request received!
20:14:27 DNSServer: Source: ('192.168.1.134', 57301)
20:14:27 DNSServer: Domain: appleglobal.102.112.2o7.net
20:14:27 DNSServer: ***forward request
20:14:27 DNSServer: -> DNS response from higher level
20:14:27 DNSServer: DNS request received!
20:14:27 DNSServer: Source: ('192.168.1.134', 63502)
20:14:27 DNSServer: Domain: a5.mzstatic.com
20:14:27 DNSServer: ***forward request
20:14:27 DNSServer: -> DNS response from higher level
20:14:27 DNSServer: DNS request received!
20:14:27 DNSServer: Source: ('192.168.1.134', 54205)
20:14:27 DNSServer: Domain: a1.da1.akamai.net
20:14:27 DNSServer: ***forward request
20:14:27 DNSServer: -> DNS response from higher level
20:14:28 DNSServer: DNS request received!
20:14:28 DNSServer: Source: ('192.168.1.134', 52305)
20:14:28 DNSServer: Domain: a2.da1.akamai.net
20:14:28 DNSServer: ***forward request
20:14:28 DNSServer: -> DNS response from higher level
20:14:41 DNSServer: DNS request received!
20:14:41 DNSServer: Source: ('192.168.1.134', 52329)
20:14:41 DNSServer: Domain: trailers.apple.com
20:14:41 DNSServer: ***intercept request
20:14:41 DNSServer: -> DNS response: 192.168.1.138

**Comment by pudds** [comment]
Have you installed the certificate on your Apple TV?  This is a separate step from creating and installing it in plex connect.

https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Certificate-via-Ethernet

**Comment by iBaa** [comment]
That log seems to be quite outdated... please grab the latest sources (or at least the latest release), try again and head over to the plex forums for more help!

**Comment by darby007** [comment]
Hi
That resolve the issue

Many, many tks

Envoyé de mon iPhone
