### ISSUE TITLE
Wiki Pull Request

### ISSUE THREAD

**Issue by jzgdev** [iBaa/PlexConnect#417]
Changed `Install-Guide-Mac-Certificates.md` to `Install-Guide-Mac-and-Unix-Certificates.md`, added link to go back to `Install-Guide-Linux.md` from `Install-Guide-Mac-and-Unix-Certificates.md`, updated linking in `Install-Guide.md`.

I've also consolidated the certificate creation command to a one liner which can be run from the 'PlexConnect' root folder; no need for unneccesary copying/dragging/dropping/etc, this one liner `cd` to `assets/certificates` based on the relative path of PlexConnect's root and generates the certificates right there, then `cd` back to install directory. 

Removed reference to iPhone Configuration Utility as the installation of profiles is not pertinent (for OS X and Unix systems) to local certificate generation on host machine and I believe this technique has long since fallen out of favor the far easier method described in [Install Guide Certificate via Ethernet](https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Certificate-via-Ethernet)

None of these changes are by any means neccessary but are a few minor points I felt would add some clarity based on some hang ups I had with the current wiki when initially setting everything up for the first time.

My cloned repo of the wiki is located at [https://github.com/jzgdev/PlexConnect-Wiki](https://github.com/jzgdev/PlexConnect-Wiki)

**Comment by moodyblue** [comment]
Thanks, but your repo is no longer available. Closing this request.
