### ISSUE TITLE
MODEM DROP OUT 

### ISSUE THREAD

**Issue by coooolhandluke** [iBaa/PlexConnect#418]
Firstly thanks for this awesome plugin I recently brought a ATV2 and was really annoyed I could't use Plex, so this is a life saver.

 Just one issue I tend to have dropouts with my modem quite often, so I have to reset my modem. I've found that when I do this I have to rerun the plugin and go through the process of manually entering the DSN number in order to get my ATV working again. Just wondering if there is an easier solution? or is this the only one for when my internet drops out and I have to reset my modem.

Cheers

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
