### ISSUE TITLE
Plexconnect Only Works Whithout Win10 Firewall

### ISSUE THREAD

**Issue by sergiopadua** [iBaa/PlexConnect#419]
All works fine without firewall, but with firewall no way.

I already create a new inbound rule to allow Python and ports 80/443 and nothing, my world wide web already stoped.

Please I neeed help.

**Comment by iBaa** [comment]
Please check in the forums - I have no idea about Win10.
There might be some threads already, or post a new question. I'm sure - compared to here - you will find more helpful people over there.
