### ISSUE TITLE
what if we could check the health of my ATV conn

### ISSUE THREAD

**Issue by ferantivero** [iBaa/PlexConnect#421]
looking forward to improve my home network I found that it would be great if we can check how well is my ATV connection. And, searching I also found that Netflix provides you with a video that gives similar information. more info http://www.engadget.com/2013/12/17/heres-how-to-check-your-apple-tvs-netflix-bandwidth-using-a-hi/

am I missing something that would help me to get easier such info? I think this will help me to understand when the bottleneck is my network. 

Thanks,

**Comment by moodyblue** [comment]
Thanks for your suggestion. This must be done in PMS (as Netflix is doing), so I'm closing your request.
