### ISSUE TITLE
Unable to start fresh install on QNAP - stops before ATVsettings

### ISSUE THREAD

**Issue by Rycochet** [iBaa/PlexConnect#422]
Currently putting together a simple QNAP package to auto-run PlexConnect and finding it can't start within the package itself.

Not going to post a log (it's on High, but stopping way to early) simply because it's not useful - the last line is:

`16:36:10 Settings: getsetting hosttointercept=trailers.apple.com`

Why this is so annoying - another (older but up-to-date) install is sitting elsewhere on the NAS, and runs perfectly with an identical config and the next log line from that starting up is `16:40:36 init class CATVSettings`)

The only obvious difference is the paths -
- Working - /share/Projects/PlexConnect
- Not working - /share/MD0_DATA/.qpkg/PlexConnect/PlexConnect

I would say it doesn't like the "." in the path, but renaming the working one as `.PlexConnect` makes no difference.

**Comment by iBaa** [comment]
If I interpret your report plus the source code correctly, next thing up would be the instantiation of the proxy server to communicate application internal between the processes: PlexConnect.py, lines 83ff.
Are you sure both of your PlexConnect installations would run the same python version? The info herein be found in the logs as well...

**Comment by Rycochet** [comment]
They are running absolutely identical setups on the same machine - I skipped the extra lines of log simply because they are identical and "normal" - including the Python version.

Since it was being pointed out I decided to backup the working one and copy the non-working one over to the same folder - and it didn't work - done a byte comparison and shown differences where there shouldn't be, so going to try to track down what's actually going on here and get back to this - looking more likely that it's not anything weird within PlexConnect itself though...

**Comment by Rycochet** [comment]
And to followup - I found the problem, it was actually something I manually deleted in the old install after it got changed on here and broke in this exact way (and I'd completely forgotten, it was from a commit back in [September 2014](https://github.com/iBaa/PlexConnect/commit/e5c0feb730a03450aa88fbd6f45941c669636cbf))

https://github.com/iBaa/PlexConnect/blob/master/PlexConnect.py#L89

    // proxy.start(initProxy)
    proxy.start()

Running on python 2.7.3 on there (can't update sadly) - but for some reason that changed line just stopped it from working - I can put a manual replacement of that line in the run script easily enough.

Feel free to close this issue if there's no way to fix that, but I'll leave it up to you since it's related to #397 :-)

**Comment by iBaa** [comment]
Ok, great that you got it working again!
I just checked: python 2.7.11 documentation describes the use of `BaseManager.start(init-fn, init-args)`, whereas 2.7.6 doesn't allow those parameters.
The `initProxy()` doesn't really do that much... only making sure the proxy itself is ignoring any `SIGINT`. It probably doesn't make a difference, if you have PlexConnect running as a daemon, rather than within a terminal window. Unfortunately I really forgot the underlying reason for that structure...
If it is running fine on your side, you don't seem to need that "ignoring" thing, do you? But then, I am a bit resistant to just delete it. What to do?
We could modify the source to...
```
    try:
        proxy.start(initProxy)
    except:
        proxy.start()  // initializer first supported somewhere between python 2.7.7 and 2.7.10...
```

**Comment by Rycochet** [comment]
The exception handler would be the safest and easiest - found the original issue with #290 - and managed devices are one case where the installed version of python isn't so easy to update ;-)

I'd also suggest logging that failure on High so that (hopefully) it can be seen and acted on.

**Comment by Rycochet** [comment]
Thinking about this - I'm not sure it actually causes an exception, it seems like it just silently fails - unless the exception isn't meant to be printed to the log / console at all.

I was looking at this - http://stackoverflow.com/a/1093331/3328079 - as an alternative, and basically just checking if the version of Python being used is high enough - so something like this -

```
import sys
if sys.version_info>(2,7,7):
   proxy.start(initProxy)
else:
   proxy.start()
   // log something to point out updating python is safer
```

**Comment by iBaa** [comment]
Hm. Not sure about the log, at that point it might not set up correctly to get all the data.
Are you able to run it in a terminal window? With the faulty line... you should get an error message there, just before python stops execution. This would give us a better hint about the exception. :-)

**Comment by Rycochet** [comment]
Here we go -

```
17:28:01 PlexConnect: IP_self (from settings): 192.168.0.2
Traceback (most recent call last):
  File "./PlexConnect.py", line 188, in <module>
    running = startup()
  File "./PlexConnect.py", line 89, in startup
    proxy.start(initProxy)
TypeError: start() takes exactly 1 argument (2 given)
```

Looks like the try/except would catch this after all :-)

**Comment by Rycochet** [comment]
Given it a little testing, and a final version seems to work perfectly well on QNAP (or "older python") -

```
    try:
        proxy.start(initProxy)
    except TypeError as msg:
        if str(msg) == 'start() takes exactly 1 argument (2 given)':
            proxy.start() # initializer first supported somewhere between python 2.7.7 and 2.7.10
        else:
            raise
```

**Comment by iBaa** [comment]
Ok, though I don't see a reason for only limiting your re-try to the TypeError (and only if it comes back with the correct, detailed description), plus raising it otherwise. Why not re-trying it without arguments in any case? Python should raise a new exception when falling over something doing the `proxy.start()` - no matter if TypeError or something else went wrong in the first place.

**Comment by Rycochet** [comment]
It would, but I've got a longstanding habit of trying not to call any function twice when it's got unknown side-effects, and this is making sure that it's only being called twice in that very specific situation - defensive coding from dealing with badly implemented APIs - in this case I don't think it'd make a difference mind you ;-)

**Comment by iBaa** [comment]
Well, I don't like checking for the error message by the character - it might be very dependent on the python version, and other settings/environmental status (debug? verbose? underlying OS?).
Plus, if it fails the second time python will exit immediately, no questions asked.
The only concern left on my side is the fact, that we are not able to ignore the ESC key in the proxy thing... depending on the startup process (ie. demon vs terminal) and the input/control possibilities (someone actually hits ESC?) we might end up with a couple of running PlexConnect processes that actually lost their communication channel. Will that be bad?

**Comment by Rycochet** [comment]
I think the error message itself might change in future versions - but is likely to be similar in older ones - depends whether this is going in as a fix for this specific case of "We know the highest version that can be installed on this OS and it isn't going to change", or "This is a fix for anyone on an older version".

I'm pretty sure that anyone who **can't** update their Python to a "safe" version doesn't have a choice in the matter, so changing the call is literally the only solution (the pull request in Python itself actually had this exact argument about changing the API) - hence why reporting it in the log seems like a good idea for people who can, but haven't - so maybe log + wiki for killing wild processes (and I hope it'll only really affect people running closed-in systems without a choice to upgrade).

For anyone with an older version, not being able to kill the proxy is pretty much their default state so it's more important to not break anything for the 99% of users who are on a more recent release.

**Comment by moodyblue** [comment]
Still an issue ?

**Comment by moodyblue** [comment]
Closed due to inactivity.
