### ISSUE TITLE
DNSServer: Failed to create socket on UDP port 53: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by lucafolin** [iBaa/PlexConnect#424]
How can I fix the following issue: "DNSServer: Failed to create socket on UDP port 53: [Errno 13] Permission denied". Below all my system settings.
PMS is running fine but PlexConnect won't to sart up.
Please help me.

ATV Apple TV 3 firmware 7.2 (7512)
ATV DNS server 192.168.2.10
PlexConnect IP 192.168.2.10
PlexConnect installed on synology DS214play DSM 5.2
PMS installed on synology DS214play DSM 5.2
PMS version 0.9.15.2
The local IP address of the device that the Plex media server (PMS) is installed on: 192.168.2.10
PlexConnect version 20150623-1

Settings.cfg

[PlexConnect]
enable_plexgdm = True
ip_pms = 192.168.178.10
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 192.168.2.10
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = High
logpath = .

PlexConnect.log

17:25:41 PlexConnect: started: 17:25:41
17:25:41 PlexConnect: Version: 0.5-dev-020615
17:25:41 PlexConnect: Python: 2.7.11 (default, Dec 17 2015, 14:08:17)
[GCC 4.6.3]
17:25:41 PlexConnect: Host OS: linux2
17:25:41 PlexConnect: PILBackgrounds: Is PIL installed? True
17:25:41 Settings: getsetting enable_plexconnect_autodetect=True
17:25:41 PlexConnect: IP_self: 192.168.2.10
17:25:41 Settings: getsetting hosttointercept=trailers.apple.com
17:25:41 ATVSettings: init class CATVSettings
17:25:41 ATVSettings: load settings
17:25:41 Settings: getsetting enable_dnsserver=True
17:25:41 DNSServer: started: 17:25:41
17:25:41 Settings: getsetting port_dnsserver=53
17:25:41 Settings: getsetting ip_dnsmaster=192.168.2.10
17:25:41 DNSServer: Failed to create socket on UDP port 53: [Errno 13] Permission denied
17:25:41 PlexConnect: DNSServer not alive. Shutting down.
17:25:41 PlexConnect: Shutting down.
17:25:41 ATVSettings: save settings
17:25:42 PlexConnect: shutdown
17:25:42 ATVSettings: save settings
17:25:42 PlexConnect: shutdown

**Comment by iBaa** [comment]
... by running it with elevated rights? Like sudo.
If not something else in your Linux box is holding it down. I suggest checking out the plex forums/Third Party clients/PlexConnect and post a request there.
