### ISSUE TITLE
Cannot start the service

### ISSUE THREAD

**Issue by iforlife** [iBaa/PlexConnect#425]
The instance's SvcRun() method failed 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\win32\lib\win32serviceutil.py", line 835, in SvcRun
    self.SvcDoRun()
  File "C:\Program Files (x86)\PlexConnect\PlexConnect_WinService.py", line 40, in SvcDoRun
    running = PlexConnect.startup()
  File "C:\Program Files (x86)\PlexConnect\PlexConnect.py", line 89, in startup
    proxy.start(initProxy)
  File "C:\Python27\lib\multiprocessing\managers.py", line 502, in start
    self._address = reader.recv()
EOFError 
%2: %3

I've tried this on 2 different machines - Win7 & Win10. Should be OS agnostic.

**Comment by iBaa** [comment]
> should be OS agnostic.

Well, I see it the other way: Python should behave the same, independent of the OS. :-D

Anyway, the strange thing is, this is the first time I have heard/seen reports of this error. And I bet, there are multiple instances running on Win7 & Win10 already... So what exactly is going on? What version of Python are you running?

**Comment by iforlife** [comment]
Totally agree with you.
Python is 2.7.
https://www.python.org/ftp/python/2.7/python-2.7.msi
And the extensions are:
http://sourceforge.net/projects/pywin32/files/pywin32/Build%20217/pywin32-217.win32-py2.7.exe/download

**Comment by iBaa** [comment]
Any chance to update to a later Python? Currently we are at 2.7.10 or 2.7.11 or so. My guess is, that 2.7 would be equal to 2.7.0, right?

**Comment by hillyswandweck** [comment]
I can confirm I'm seeing this issue too. Running on Win10 x64 with Python 2.7.x (the latest one as of 24-Apr-2016) AMD64 version. Installed from this link - https://www.python.org/ftp/python/2.7/python-2.7.amd64.msi
