### ISSUE TITLE
Without plex sign in, server works, when signed in, error received

### ISSUE THREAD

**Issue by psyciknz** [iBaa/PlexConnect#428]
I thought i was similar to this: https://github.com/iBaa/PlexConnect/issues/390

I have one server on my network.  Without being sign in the myplex it works as advertised.
When I signed in to myplex with my main plex user, suddenly my library was empty.  I am sharing with another plex user (I see their library).  When i looked at shared library or did a search, it looked like it was picking up his library while mine was empty.

I tried a git update to the later plexconnect and the same behaviour existed.

Here is the portion of the, you can see the error I receive, then I sign out of myplex:
20:27:05 DNSServer: DNSServer: Serving DNS on 192.168.10.40 port 53.
20:27:05 DNSServer: ***
20:27:05 WebServer: started: 20:27:05
20:27:05 WebServer: ***
20:27:05 WebServer: WebServer: Serving HTTP on 192.168.10.40 port 80.
20:27:05 WebServer: ***
20:27:06 WebServer: started: 20:27:06
20:27:06 WebServer: ***
20:27:06 WebServer: WebServer: Serving HTTPS on 192.168.10.40 port 443.
20:27:06 WebServer: ***
20:27:23 PlexAPI: ***
20:27:23 PlexAPI: poke plex.tv - request Plex Media Server list
20:27:23 PlexAPI: ***
20:27:25 PlexAPI: No Response from Plex Media Server
20:27:25 PlexAPI: We failed to reach a server. Reason: [Errno -2] Name or service not known
20:27:25 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/var/www/plexconnect/PlexAPI.py", line 406, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

20:27:25 PlexAPI: Servers (local, plex.tv, MyPlex): 2
20:27:36 PlexAPI: MyPlex Sign Out done

My plex server is on 10.1, plexconnect is on 10.40 serving DNS and web server.
Settings.cfg
[PlexConnect]
enable_plexgdm = True
ip_pms = 192.168.10.50
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 123.123.123.123
prevent_atv_update = False
enable_plexconnect_autodetect = True
ip_plexconnect = 192.168.10.40
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = /var/www/plexconnect/assets/certificates/trailers.pem
allow_gzip_atv = True
allow_gzip_pmslocal = True
allow_gzip_pmsremote = True
loglevel = Normal
logpath = /var/log/

**Comment by iBaa** [comment]
The issue is...
- when not signed in PlexConnect will use PlexGDM (or a fixed IP) to connect to your PMS. The server will answer an everything is good to go.
- when signed in, PlexConnect uses connection data from `https://plex.tv/api/resources?includeHttps=1`. This was ultimately done to support PMS encryption and such. Sometimes, though, the data provides multiple IP addresses (often cached, old, outdated), and PlexConnect is not set up to figure out which one to choose.
It sure needs an improvement here, I just don't know where to find the spare time to work on it...

**Comment by psyciknz** [comment]
So really the real issue for me is not the access to myplex - although that would be nice, but PLexConnect isn't using my plex user name - which I use for plex/trakttv integration.  So when I play something with the apple tv, it doesn't pass the x-plex-username parameter.
