### ISSUE TITLE
I have issue with plexconnect

### ISSUE THREAD

**Issue by Webmasterparis** [iBaa/PlexConnect#429]
Your ATV model (2 or 3) and firmware version (found under the ATV settings > general > about > Apple TV software): ATV 3 / firmware 7.2

The DNS server set on the ATV (found under the ATV settings > general > network > DNS): 136.243.58.194

The local IP address of the device that PlexConnect is installed on:136.243.58.194

The device and operating system (including version number) that PlexConnect is installed on: server didicated hetzner linux ubuntu 14.04lts 

The device and operating system (including version number) that the Plex media server (PMS) is installed on: linux ubuntu 14.04lts 

The Plex media server (PMS) version number you are running (do not put 'latest'): Version 0.9.15.2

The local IP address of the device that the Plex media server (PMS) is installed on: not local it in internet 136.243.58.194

The PlexConnect version number. If using Github source then a time and date of download (look at the creation date of the folder) and if you are using any non-standard setup or a fork
: I dont know were see that I launch command 
http://www.htpcguides.com/install-plex-media-server-ubuntu-14-04/

The contents of your 'Settings.cfg' file (this is created at first clean shutdown of PlexConnect, using CTR+c)

PlexConnect]
enable_plexgdm = False
ip_pms = 136.243.58.194
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = High
logpath = .

A detailed description of the issue (the clearer you can make this the better):

I install the plexconnect following your procedure

right here
https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Linux

plex good start

I set

the certificate and the IP of the DNS server my PMS / DNS 136.243.58.194 in the ATC

but nothing is happening ??

or no message log is displayed in the plexconnect ???

I have nothing going on the ATV and even appears as the trailers of apple ??

even changing the dns manually on the ATV ??

I testing this configuration with 3 apple TV / V3 - firemware 7.2

Thank you for your help

Ensure you post your 'PlexConnect.log' file to pastebin and post the link ('PlexConnect.log' is located in your PlexConnect folder).:

http://pastebin.com/fkVFxMU5

**Comment by Webmasterparis** [comment]
up no reponse please? friends

**Comment by carlsteinhilber** [comment]
Have you tried the forums?
Then again, maybe they sent you here.

**Comment by Webmasterparis** [comment]
Hello

not I try that here because I invented the program that connect plex was best to find the solution to my problem ..

here would be nice if the inventor IAFB pourvez help me find the solution.

Giving me the trick to test here why does not work?

the plexconnect displays nothing, is that it's in the update I'm on Plex?

thank you

**Comment by carlsteinhilber** [comment]
The problem is that "the inventor" can really only have experience with the system configurations he's developed on or tested with.

On the forums, the user base is broader so the chances are greater that you'd find someone there who has the same configuration that you have or has experienced the same issues that you are, and can offer more immediate tips/help.

**Comment by finkdiff** [comment]
Also the wiki here specifically asks you to post the requested information in the dedicated PlexConnect subforum on the Plex website.

**Comment by Webmasterparis** [comment]
you give no solution and you close the topic ??
What's this site ??

whatever?

It's not serious

**Comment by finkdiff** [comment]
https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue

**Comment by Webmasterparis** [comment]
Your ATV model (2 or 3) and firmware version (found under the ATV settings > general > about > Apple TV software): ATV 3 / firmware 7.2

The DNS server set on the ATV (found under the ATV settings > general > network > DNS): 136.243.58.194

The local IP address of the device that PlexConnect is installed on:136.243.58.194

The device and operating system (including version number) that PlexConnect is installed on: server didicated hetzner linux ubuntu 14.04lts

The device and operating system (including version number) that the Plex media server (PMS) is installed on: linux ubuntu 14.04lts

The Plex media server (PMS) version number you are running (do not put 'latest'): Version 0.9.15.2

The local IP address of the device that the Plex media server (PMS) is installed on: not local it in internet 136.243.58.194

The PlexConnect version number. If using Github source then a time and date of download (look at the creation date of the folder) and if you are using any non-standard setup or a fork
: I dont know were see that I launch command 
http://www.htpcguides.com/install-plex-media-server-ubuntu-14-04/

The contents of your 'Settings.cfg' file (this is created at first clean shutdown of PlexConnect, using CTR+c)

PlexConnect]
enable_plexgdm = False
ip_pms = 136.243.58.194
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = High
logpath = .

A detailed description of the issue (the clearer you can make this the better):

I install the plexconnect following your procedure

right here
https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Linux

plex good start

I set

the certificate and the IP of the DNS server my PMS / DNS 136.243.58.194 in the ATC

but nothing is happening ??

or no message log is displayed in the plexconnect ???

I have nothing going on the ATV and even appears as the trailers of apple ??

even changing the dns manually on the ATV ??

I testing this configuration with 3 apple TV / V3 - firemware 7.2

Thank you for your help

Ensure you post your 'PlexConnect.log' file to pastebin and post the link ('PlexConnect.log' is located in your PlexConnect folder).:

http://pastebin.com/fkVFxMU5

**Comment by Webmasterparis** [comment]
I write exaly that ??

https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue

**Comment by Webmasterparis** [comment]
see up ???

**Comment by finkdiff** [comment]
It specifically asks you to post on the Plex forum, having the development team help  every individual user is not feasible if development is to continue. The forums have lots of users that can help share that burden and get you a quick answer.

**Comment by iBaa** [comment]
...your aTV DNS request is NOT routed through PlexConnect. It would be the first indication in the logs:
You have to see something like the following messages: `DNS request received`, `DNS request forward`, `DNS request intercepted`.
If not... your aTV DNS isn't set correctly. Or your firewall filters incoming DNS requests.

**Comment by Webmasterparis** [comment]
ho! Finally, an answer to the inventor wow !!
Great
I'm glad finally to have your participation in my post.
So yes it is incompréhensible..il is no request that arrives on my DNS server plexconnect ???
bizzard yet ATV V3 firmware 7.2 before upgrading to the latest version of Plex here work well, the redirect plexconnect well.
And overnight nothing ??
I do not know what it is to pass on the server, I do not voyer redirects the console plexconnnect ???
I have the break I'll reinstall.
can you advise me a tutorial to install Plex on ubuntu + plexconnect or formula works directly?
thank you

**Comment by Webmasterparis** [comment]
hello IAFB

I think just being the problem is because of my configuration?

my box is on a network with private IP 10.0.0.109 type default gateway: 10.0.0.138 and my ubuntu server is located in a web host with a public IP?

here is the config

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 149.202.94.29
        netmask 255.255.255.0
        network 149.202.94.0
        149.202.94.255 broadcast
        gateway 149.202.94.254
        dns-nameservers 8.8.8.8 8.8.4.4

iface eth0 inet6 static
        address 2001: 41d0: 1004: 0e1d ::
        netmask 64
        post-up / sbin / ip route add -family inet6 2001: 41d0: 1004: 0eff: ff: ff: ff: ff dev eth0
        post-up / sbin / ip route add default -family inet6 through 2001: 41d0: 1004: 0eff: ff: ff: ff: ff
        Pre-down / sbin / ip route del default -family inet6 through 2001: 41d0: 1004: 0eff: ff: ff: ff: ff
        Pre-down / sbin / ip route del -family inet6 2001: 41d0: 1004: 0eff: ff: ff: ff: ff dev eth0


can you help me?

because in my log I found my box well ATC which is connect ??

here is the log ??
12:57:18 PlexConnect: started: 12:57:18
12:57:18 PlexConnect: Version: 0.5-dev-101215
12:57:18 PlexConnect: Python: 2.7.10 (default, October 14, 2015, 4:09:02 p.m.)
[GCC 5.2.1 20151010]
12:57:18 PlexConnect: Host OS: linux2
12:57:18 PlexConnect: PILBackgrounds: Is PIL installed? true
12:57:18 Settings: GetSetting enable_plexconnect_autodetect = True
12:57:18 PlexConnect: IP_self: 149.202.94.29
12:57:18 Settings: GetSetting hosttointercept = trailers.apple.com
12:57:18 ATVSettings: init class CATVSettings
12:57:18 ATVSettings: load settings
12:57:18 Settings: GetSetting enable_dnsserver = True
12:57:18 DNSServer: started: 12:57:18
12:57:18 Settings: GetSetting port_dnsserver = 53
12:57:18 Settings: GetSetting ip_dnsmaster = 10.0.0.138
12:57:18 Settings: GetSetting prevent_atv_update = True
12:57:18 DNSServer: ***
12:57:18 DNSServer: DNSServer: Serving DNS is 149.202.94.29 port 53.
12:57:18 DNSServer: Intercept: [ 'trailers.apple.com'] => 149.202.94.29
12:57:18 DNSServer: restrain [ 'mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
12:57:18 DNSServer: --other forward to Higher Level DNS: 10.0.0.138
12:57:18 DNSServer: ***
12:57:18 WebServer: started: 12:57:18
12:57:18 Settings: GetSetting port_webserver = 80
12:57:18 WebServer: ***
12:57:18 WebServer: WebServer: Serving HTTP port 80 on 149.202.94.29.
12:57:18 WebServer: ***
12:57:18 Settings: GetSetting enable_webserver_ssl = True
12:57:18 WebServer: started: 12:57:18
12:57:18 Settings: GetSetting sslport = 443
12:57:18 Settings: GetSetting certfile = / assets / certificates / trailers.pem.
12:57:18 Settings: GetSetting certfile = / assets / certificates / trailers.pem.
12:57:18 WebServer: ***
12:57:18 WebServer: WebServer: Serving HTTPS port 443 is 149.202.94.29.
12:57:18 WebServer: ***


What can I do to make it work?

thank you

**Comment by iBaa** [comment]
No idea...
The strange parts:
>12:57:18 PlexConnect: IP_self: 149.202.94.29
>12:57:18 DNSServer: --other forward to Higher Level DNS: 10.0.0.138

So PlexConnect is hosted "off-site" - with your ubuntu server on public IP? But then it tries to reach your "next level DNS" at your local gateway address? How is that supposed to work?

My advice:
- Start with a standard configuration (aTV, PlexConnect, PMS in one LAN).
- Don't use PlexConnect's DNS in places open to the public. It really is NOT designed with big security in mind.
- Step by step modify your setup to reach your goal, making sure the intermediate setup is understood and working.
- Check in the Plex forums for people with a similar setup - I sure am not one of them...
