### ISSUE TITLE
Use only connections in the same net/subnet

### ISSUE THREAD

**Issue by Chimecho** [iBaa/PlexConnect#431]
I have Hamachi installed and it provides an additional network address to access the PMS, so in my api/resources I have two connections available:

![image](https://cloud.githubusercontent.com/assets/5361042/13556107/be87112a-e39f-11e5-8228-3444141b22b0.png)

For some reason PlexConnect detects the second one as primary and messes up things with the AppleTV. It should take into account the AppleTV's IP address, and detect if the network provided by api/resources are on the same net/subnet.

**Comment by finkdiff** [comment]
You are using an unsupported and edge case setup but you can override the auto detection on interfaces and set it manually, see the advanced  settings section of the wiki.

**Comment by Chimecho** [comment]
I've seen it, I've done that. I was just pointing out a possible improvement.
People likes things that works out of the box...

**Comment by finkdiff** [comment]
Fair enough :)
There are some varied setups out there though so it might make sense and improve auto detection, assuming it isn't just robbing Peter to pay Paul, e.g. there are users running the components on separate subnets at home.

**Comment by iBaa** [comment]
Yep... for a long time there has been a limitation in the way PlexConnect dealt with the PMS discovery.
Please try my latest commit (https://github.com/iBaa/PlexConnect/commit/cfd51deffb2d1159f15edc29faee56166717526c). It should fix those issues. :-D
Any feedback is appreciated!
