### ISSUE TITLE
Channel Tou.TV crashes everything

### ISSUE THREAD

**Issue by cferron** [iBaa/PlexConnect#439]
Not sure if it it plexconnect fault but I'm posting anyway in case code could be improved (i'm no coder by the way)
Refer to this post.
https://forums.plex.tv/discussion/comment/1175269/#Comment_1175269

Basically, starting a stream from this channel will make PLex server crash but the stream will continue anyway. But when done server has to be restarted... If stream is not stopped on plexconnect it is impossible to restart the Server.

[Crashlog.txt.zip](https://github.com/iBaa/PlexConnect/files/243401/Crashlog.txt.zip)
[plexserver-log.txt.zip](https://github.com/iBaa/PlexConnect/files/243402/plexserver-log.txt.zip)
[com.plexapp.plugins.toutv.log.zip](https://github.com/iBaa/PlexConnect/files/243403/com.plexapp.plugins.toutv.log.zip)
[PlexConnect.log.zip](https://github.com/iBaa/PlexConnect/files/243404/PlexConnect.log.zip)

**Comment by moodyblue** [comment]
PlexConnect streams directly from the provider, with no PMS interference, until its told to stop. Therefore nothing needs to be fixed in PlexConnect.

Your issue should be solved in PMS.
