### ISSUE TITLE
ios?

### ISSUE THREAD

**Issue by PaidSubscription** [iBaa/PlexConnect#442]
Why did you call it IOS?, ios stands for iphone OS lmao

**Comment by iBaa** [comment]
Call it where?
tvOS was introduced with aTV4, as far as I remember. Earlier (aTV2/3) where said to run some kind of iOS, wasn't it?

**Comment by carlsteinhilber** [comment]
Exactly. Gens 2 and 3 ran "a variant of iOS".
https://en.wikipedia.org/wiki/Apple_TV#2nd_and_3rd_generation

But more to the point, iOS does not stand for iPhone OS, anymore than iMac stands for iPhone Mac, iPad stands for iPhone Pad, or iPod stands for iPhone Pod. The "i" is simply synonymous with Apple products. It is said that the "i" in the original iMac stood for "internet", but no one's really sure. Probably more than you wanted to know  ;-)
