### ISSUE TITLE
Plex + Apple TV + 25fps = Stuttery Picture

### ISSUE THREAD

**Issue by ssurfong** [iBaa/PlexConnect#443]
Hi all,

I have a Sony Bravia TV and use Plex on my iMac with the latest gen ATV. All streams look good except for those that are 25fps, which result in stuttery picture. I can't seem to find a fix, whether it's a TV setting or a Plex setting. Any thoughts? Thanks!

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
