### ISSUE TITLE
PlexConnect no longer working reliably with latest PMS update (1.1.3)

### ISSUE THREAD

**Issue by betalogue** [iBaa/PlexConnect#445]
Hi,

After months (even years) without significant issues, last week I innocently installed the 1.1.3 update for Plex Media Server on my Mac Pro. Since then, I have had nothing but trouble. I thought that reverting to PMS 1.0.0 would help, but I tried it tonight and I still have trouble, so I am at a loss.

My setup is slightly unique in that I have a Mac Pro that has two different network connections: 1) one to an AirPort Base Station in DHCP + NAT mode (router 10.0.1.1) connected to the Internet (cable modem) with one line, and 2) one to an (older) AirPort Base Station in Bridge mode connected to a cable box that acts as a router (192.168.1.1) and is connected to the Internet as well (different cable connection). For the second connection, the Mac Pro has a manually assigned IP address of 192.168.1.20.

I use 8.8.8.8 and 8.8.4.4 as the top 2 DNS servers on both networks.

The Apple TV (3rd gen.) is on the 192.168.1.x network and has the fixed IP address 192.168.1.3. It has 192.168.1.20 as the DNS server, so that Trailers can be used for PlexConnect running on the Mac Pro.

My Settings.cfg file for PlexConnect is the following:

```
[PlexConnect]
enable_plexgdm = False
ip_pms = 192.168.1.20
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = False
ip_plexconnect = 192.168.1.20
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = Normal
logpath = .
```

This has worked well for me in recent times, but not anymore. :-(

Like I said, the problems started when I installed the PMS 1.1.3 update over 1.0.0, but now I have reverted to 1.0.0 (from a backup) and I still have the problem. 

The PMS 1.1.3 was unusual in that it automatically signed me out on the Apple TV and I had to re-enter my user name and password manually. Then it worked for a while, and then, the next day, it stopped working.

The symptoms are the following:
1. PlexConnect fails to display the previews of the video files in the UI.
2. When I select one of the files to play it, I get "Accessing Trailers…" and the spinning wheel and nothing happens. (Meanwhile, I can play the exact same file just fine in the web interface for Plex on the Mac Pro.)
3. After that, even if I get out of the Trailers app and try, for example, to view a movie trailer in the iTunes Store, it fails as well, with "Accessing the iTunes Store…" and the spinning wheel. Nothing seems to work anymore, except that the network test in Settings on the Apple TV works fine.

I've tried restarting the Apple TV and that seems to give me back access to the iTunes Store, but only until I try to use the Trailers app for PlexConnect again and then everything fails again.

Meanwhile, on the Mac Pro, the running PlexConnect app displays something like the following in Terminal:

```
22:28:40 DNSServer: DNS request received!
22:28:40 DNSServer: Source: ('192.168.1.3', 55017)
22:28:40 DNSServer: Domain: a1.da1.akamai.net
22:28:40 DNSServer: ***forward request
22:28:40 DNSServer: -> DNS response from higher level
22:28:50 DNSServer: DNS request received!
22:28:50 DNSServer: Source: ('192.168.1.3', 61741)
22:28:50 DNSServer: Domain: trailers.apple.com
22:28:50 DNSServer: ***intercept request
22:28:50 DNSServer: -> DNS response: 192.168.1.20
22:28:50 WebServer: serving /js/application.js
22:28:51 WebServer: serving .xml: /
22:28:51 PlexAPI: ***
22:28:51 PlexAPI: poke plex.tv - request Plex Media Server list
22:28:51 PlexAPI: ***
22:28:52 PlexAPI: poke Mac Pro 2014 (71080f98b9488e6ee73258be5d715c54fefa5e07) at https://10-0-1-2.302bd2f441214547aa96043548d20217.plex.direct:32400
22:28:52 PlexAPI: poke Mac Pro 2014 (71080f98b9488e6ee73258be5d715c54fefa5e07) at https://192-168-1-20.302bd2f441214547aa96043548d20217.plex.direct:32400
22:28:52 PlexAPI: response Mac Pro 2014 (71080f98b9488e6ee73258be5d715c54fefa5e07) at https://10-0-1-2.302bd2f441214547aa96043548d20217.plex.direct:32400
22:28:52 PlexAPI: Servers (local, plex.tv, MyPlex): 2`
```

Starting at "22:28:50 WebServer: serving /js/application.js", this is not what I normally see in PlexConnect while it's running.

I also don't know why it would have TWO servers running, as I only have one. And the 10.0.1.2 network interface on the Mac Pro should not be involved at all, yet somehow PlexConnect seems to be getting a response from 10.0.1.2:32400, which is the dynamic IP address assigned to the Mac Pro in the _other_ network, not the one that the Apple TV is on, and not the IP address (192.168.1.20) that is specified in Settings.cfg.

Does anyone have any idea what might be wrong here?

I have the latest available version of PlexConnect running on my Mac Pro. I am not aware of any other updates that I might have made in recent days that might explain all these problems all of a sudden.

Thanks in advance.

Pierre

**Comment by betalogue** [comment]
This morning, I not only restore PMS back to 1.0.0 (from backup) but also PlexConnect to the last version I had that was working (before the PMS 1.1.3 update, for which I also updated PlexConnect) and… now things are working. It remains to be seen whether they continue to work, but for now I'll stick with these older versions of PMS and PlexConnect. Still, if there is interest in trying to figure out what went wrong, I am willing to experiment (always with these backups to fall back on).

**Comment by betalogue** [comment]
Feedback from @plex suggests that the problem has to do with the new "security" features in PMS 1.1: https://forums.plex.tv/discussion/comment/1244304/#Comment_1244304

However, I tried adding the Apple TV's address (192.168.1.3) to Settings > Server > Network > List of IP addresses and networks that are allowed without auth, and it still didn't work. 

Back to PMS 1.0 / PlexConnect 0.5-dev-110516 again.

**Comment by ConorMulhern** [comment]
I think the title of this issue is misleading, I'm using PMS on an iMac, PlexConnect on a Raspberry Pi3, neither of which are using multiple NICs (Wi-Fi is disabled on both) and I'm now getting the `Trailers is unavailable. Try again later` error when I try to access my Plex library on a PMS 1.1 server via the Trailers app on an AppleTV 3. 

Everything was working okay prior to installing PMS 1.1. My `PlexConnect.log` shows that the AppleTV is successfully communicating with PlexConnect, but even with `High` logging level it's not logging any errors when I launch the Trailers app.

Here you can see the Netflix app starting on my AppleTV (.237), and PlexConnect responding (running on .240), but my Plex library never loads, and I can find no error messages;

``` bash
20:32:45 DNSServer: ***forward request
20:32:45 DNSServer: -> DNS response from higher level
20:32:46 DNSServer: DNS request received!
20:32:46 DNSServer: Source: ('192.168.1.237', 52633)
20:32:46 DNSServer: Domain: nmtracking.netflix.com
20:32:46 DNSServer: ***forward request
20:32:46 DNSServer: -> DNS response from higher level
20:32:48 DNSServer: DNS request received!
20:32:48 DNSServer: Source: ('192.168.1.237', 60171)
20:32:48 DNSServer: Domain: cdn-0.nflximg.com
20:32:48 DNSServer: ***forward request
20:32:49 DNSServer: -> DNS response from higher level
20:33:05 DNSServer: DNS request received!
20:33:05 DNSServer: Source: ('192.168.1.237', 50028)
20:33:05 DNSServer: Domain: trailers.apple.com
20:33:05 DNSServer: ***intercept request
20:33:05 DNSServer: -> DNS response: 192.168.1.240
```

I added my local network to PMS's list of networks/devices not requiring authentication, but I'm still getting the `Trailers is unavailable` error.

> @betalogue  I tried allowing individual IP address but I was still getting login prompts on other devices, I had to add the subnet – 192.168.1.0/24 – to allow unauthenticated access to PMS fom other devices.

I've looked at the PMS logs and I'm not seeing authentication denied messages (but in theory it should now allow unauthenticated access from any device on the subnet).

**Comment by ConorMulhern** [comment]
@finkdiff `Secure connections` was already set to "Prefered". I also tried "Disabled", but I'm still getting `Trailers is unavailable`.

As PlexConnect handles the connection and data transform between ATV and PMC, is there a way to monitor or log its communication to the PMS ?

**Comment by betalogue** [comment]
Hi Conor, 

Thanks for the feedback. Hopefully these exchanges will lead to a solution. It's quite clear to me that the cause of the problem is the introduction of the new "security" features in PMS 1.1. Now the question is how to get them to work with PlexConnect reliably on our devices.

I only used the original title/subject line ("PlexConnect no longer working with dual Ethernet interface") because I was speculating about it being a possible factor in the problem. I suspect that not everyone using PlexConnect is having these problems, otherwise there would be more activity in this forum (right?). So I tend to think that the problem is caused by the PMS 1.1 upgrade, but also involves other factors that are specific to some users only. Since I saw messages in Terminal about PlexAPI "poking" my Mac Pro at both 192.168.1.20 and 10.0.1.2, getting a response from 10.0.1.2, and reporting **2** servers instead of one (although the PlexConnect UI only lists *1*), I speculated that the additional factor here might be that my Mac Pro has two different network interfaces running at the same time, and that this causes confusion for Plex. I might be wrong, but I think it's still too early to tell.

I will try again with "192.168.1.0/24" in Settings > Server > Network > List of IP addresses and networks that are allowed without auth, instead of individual IP addresses, when I get the chance, but your experience seems to suggest that this does not fix the problem.

My other issue (before doing more testing) is also that, once things go wrong (i.e. once I start getting no response from the server via Trailers), the whole ability of the Apple TV to get online (including to the iTunes Store for movies and TV shows) is affected, and not just the "Trailers" app used by PlexConnect. And getting things to work again after that is not trivial. I have found that I have to BOTH uninstall PMS 1.1 and reinstall PMS 1.0 AND uninstall PlexConnect 0.5-dev-110616 and reinstall PlexConnect 0.5-dev-110516, and then also possibly power-cycle the Apple TV itself and the router at 198.168.1.1 in order to get things going again. So there's something rather obscure going wrong in the network itself once things go awry.

I should also note that I have never got the "Trailers is unavailable" error message myself, only "Accessing Trailers…" with the wheel looping endlessly. But maybe I just don't wait long enough and eventually it times out and gives "Trailers is unavailable". I don't know. Or maybe we are experiencing two different variations of the same problem introduced by PMS 1.1. (Don't you love it when new features introduced in the name of "security" do not change anything significant to your security, as far as you can tell, but actually break basic functionality for you? I find that it's becoming a pattern in this day and age.)

Finally, I should also note that, during my many attempts in the past few days, I HAVE been able to get things working with both PMS 1.1 and PlexConnect 0.5-dev-110616 AT SOME POINT and FOR A CERTAIN TIME. But not for any length of time longer than 24 hours. And that was before doing anything to Settings > Server > Network > List of IP addresses and networks that are allowed without auth. So I am not convinced that fiddling with that setting is going to fix the problem for good. If adding the IP address of the Apple TV to that list was required, how come I WAS able to get things to work at SOME point without adding it?

I don't think that's the solution. It might be involved somehow, but it might also not be the only thing that needs to be adjusted.

Obviously I'd like this problem to get solved, so that I can use the latest versions of PMS and PlexConnect, so I am definitely interested in testing things some more. I am very busy with work, though, so I might not have time to try everything right away (and in the meantime I'll keep falling back on the PMS 1.0/PlexConnect 0.5-dev-110516 combo that SEEMS to be working reliably -- knock on wood!).

I will also try posting something on the Apple TV / PlexConnect forum at plex.tv (https://forums.plex.tv/categories/appletv-plexconnect) when I get the chance. Maybe we can get more suggestions there. Feel free to post there first (and provide a link here) if you have the chance.

Thanks again.

**Comment by G-eos** [comment]
Same issue for me. Rebooting Atv sometimes helps. Still KO on 1.1.3, will try 1.1.4 ...

**Comment by gipasoft** [comment]
Same issue for me after installing PMS > 1.0.3 PlexConnect '0.5-dev-110616', here my plex connect log:
[PlexConnect.zip](https://github.com/iBaa/PlexConnect/files/478773/PlexConnect.zip)

Thank in advance for any suggestion!

**Comment by G-eos** [comment]
Does some one make some progress on this topic ?
Still not working well for me even if with latest version of plex 1.2.3.2914 :-(

**Comment by betalogue** [comment]
Haven't tried anything since my initial report. Still running 1.0.0 and 0.5-dev-110516 and things are working, so I am not going to touch anything until I get more information and time to experiment again.

**Comment by surroundedbytrees** [comment]
betalogue how has plexconnect been working...two ATV 3rd gen here and its been a nigtmare tryimg to get it to work consistantly....any idea where i might find an older version on PMS.?

Hate the idea of adding a roku just to get Plex

**Comment by betalogue** [comment]
Haven't tried again since November. Still running 1.0.0 and 0.5-dev-110516 and things are working, so I am not going to touch anything until I get more information and time to experiment again. To be honest as long as macOS updates don't break the older PMS/PlexConnect combo, I have no incentive to try again. I just ignore the message about a newer version being available.

**Comment by surroundedbytrees** [comment]
Al I can find on TimeMachine is Ver 1.0.2 and 110616...i might have a CarbonCopy some place.  If not any chance to get both items minus your certs etc ?

If I'm correct the 1.0.2 ver search on OMS via the ATV fails, and deleting items from the ATV crashes PMS...further any remote Users (Friends) get errors wen trying to view media via a browser (Chrome, Firefox Win10)....

**Comment by betalogue** [comment]
Send me an email via www.betalogue.com. Thanks.

**Comment by moodyblue** [comment]
You cannot have more than one NIC connected to the same LAN unless you use LACP. This is a PMS problem, not a PlexConnect problem, so please close this issue.

Issues should be reported here -> https://forums.plex.tv/categories/appletv-plexconnect

**Comment by betalogue** [comment]
Thanks for using all these acronyms. It's really helpful to everyone.

**Comment by moodyblue** [comment]
Google is your friend... Furthermore this is a developer blog, not a user forum... ;)

**Comment by betalogue** [comment]
OK, fine, but a search for LACP at https://forums.plex.tv/categories/appletv-plexconnect returns zero results, and a search for LACP at https://forums.plex.tv/categories/mac returns one minimally useful result, so…

The basic issue here is that, based on my own expérience, things DO WORK fine with PMS 1.0 and PlexConnect 0.5-dev-110516, with two Ethernet connections, and no LACP. (Yes, I Googled it.) Your response suggests that later versions of PMS have a problem with this setup, but the evidence suggests that PMS 1.0 does not.

You say, "You cannot have more than one NIC connected to the same LAN unless you use LACP." But the only thing that is connected to both LANs (10.0.1.x and 192.168.1.x) is the Mac Pro itself. I don't have two Ethernet plugs on the Mac Pro connected to the same LAN. One Ethernet plug is connected to the 192.168.1.x LAN and the other one is connected to the 10.0.1.x LAN. The connection to the 10.0.1.x LAN is listed as the FIRST network connection in System Preferences > Network, and the 192.169.1.x connection is listed as the SECOND one. The Apple TV is on the 192.168.1.x LAN. On the 192.168.1.x LAN, the Mac Pro has a static IP address (192.168.1.20), and so does the Apple TV (192.198.1.3).

PMS 1.0 and PlexConnect 0.5-dev-110516 run fine on that Mac Pro. As the original post indicates, PlexConnect is configured to use 192.168.1.20 as the IP address for PMS, and that's the IP address used on the Apple TV as the DNS server for the Trailers hack.

All this works fine with PMS 1.0 and PlexConnect 0.5-dev-110516, even though the Mac Pro running PMS 1.0 has another network connection to the 10.0.1.x LAN which is the top connection, and the Mac Pro uses no link aggregation (LACP).

So are you saying that PMS 1.0 worked fine with no LACP, but later versions of PMS, for some reason, now **require** LACP on the Mac running PMS, in order to somehow combine the two Ethernet connections to two different networks into one? Is this documented/explained anywhere?

I have no reason to experiment with LACP other than this, and PMS 1.0 works fine, so I am sure you can understand that I'm somewhat wary of experimenting…

**Comment by moodyblue** [comment]
I am no expert on LACP. But you can test very easily by disconnecting one of the ethernet cables form your Mac, and define the disconnected one as DHCP. 

The fact is, when PMS is started, it picks the first NIC that it finds active, and only communicates through that one. It is documented / reported numerous times in the Plex forums. There are users that posted a requirement so that PMS could bind to a certain NIC so that the choice is not so random as it appears to be.

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
