### ISSUE TITLE
Media Center Master Scanner does not work on TV Shows for AtV2 or 3 using PLex Connect..

### ISSUE THREAD

**Issue by KapsUs** [iBaa/PlexConnect#446]
If we use Media Center Master as the TV scanner under Plex Agents, the Plex Connect does not show the TV Shows on the Apple TV 2 or 3 using Plex Connect app under Trailers.

To Fix this on the XMLConverter.py line 341 we need to update to following

```
    if cmd.find('Series') **or cmd.find('Media')** != -1: dir = 'TVShow'
```

I don't have access to update the code but if someone can then it will work with the Media Center Master Scanner Agents as well :)

**Comment by moodyblue** [comment]
Tried to download this plugin to test, but looks like link is broken in http://www.mediacentermaster.com/index_test.php

Does this request still makes sense ?
