### ISSUE TITLE
Can access flex on ATV 2

### ISSUE THREAD

**Issue by lilamadelief** [iBaa/PlexConnect#447]
Hi 

I am not super computer savvy but I had to restart my ATV2 and reset it and since then I am unable to access my flex server see terminal log below 

18:21:27 PlexConnect: ***
18:21:27 PlexConnect: PlexConnect
18:21:27 PlexConnect: Press CTRL-C to shut down.
18:21:27 PlexConnect: ***
18:21:27 PlexConnect: started: 18:21:27
18:21:27 PlexConnect: Version: 0.5-dev-110616
18:21:27 PlexConnect: Python: 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
18:21:27 PlexConnect: Host OS: darwin
18:21:27 PlexConnect: PILBackgrounds: Is PIL installed? False
18:21:27 PlexConnect: IP_self: 192.168.1.36
18:21:27 DNSServer: started: 18:21:27
18:21:27 DNSServer: ***
18:21:27 DNSServer: DNSServer: Serving DNS on XXX.XXX.X.XX port 53.
18:21:27 DNSServer: intercept: ['trailers.apple.com'] => 192.168.1.36
18:21:27 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
18:21:27 DNSServer: forward other to higher level DNS: 8.8.8.8
18:21:27 DNSServer: ***
18:21:27 WebServer: started: 18:21:27
18:21:27 WebServer: ***
18:21:27 WebServer: WebServer: Serving HTTP on XXX.XXX.X.XX port 80.
18:21:27 WebServer: ***
18:21:27 WebServer: started: 18:21:27
18:21:27 WebServer: ***
18:21:27 WebServer: WebServer: Serving HTTPS on XXX.XXX.X.XX port 443.
18:21:27 WebServer: ***
18:21:30 WebServer: serving /js/application.js
18:21:30 WebServer: serving .xml: /
18:21:30 PlexAPI: ***
18:21:30 PlexAPI: PlexGDM - looking up Plex Media Server
18:21:30 PlexAPI: ***
18:21:31 PlexAPI: GDM: Servers discovered: 1
18:21:31 PlexAPI: Servers (local, plex.tv, MyPlex): 2
18:21:32 WebServer: serving .xml: /PlexConnect.xml
18:21:32 WebServer: serving /js/utils.js
18:21:32 WebServer: serving /js/handlePlexConnectNavbar.js
18:21:32 WebServer: serving .xml: /library/sections
18:21:32 PlexAPI: No Response from Plex Media Server
18:21:32 PlexAPI: We failed to reach a server. Reason: Unauthorized
18:21:32 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/PlexAPI.py", line 432, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized

18:21:32 WebServer: serving /js/utils.js
18:21:33 WebServer: serving /js/sectionHoldSelect.js

I have the correct DNS set-up on the ATV and the right certificate and it use to work perfectly. 
Note that I use a mac mini as server 

Thank you in advance for your help

**Comment by mt3** [comment]
Same error here. I believe I also recently updated pip packages or Python dependencies (via Homebrew).

**Comment by CyberGhost84** [comment]
Your Plex Media Server and PlexConnect need to be signed in.

PMS : Settings - General - Sign In
PlexConnect : Settings - MyPlex Sign In

Hope that helps

**Comment by mt3** [comment]
Logged out. Reset password. Logged in. Worked.

**Comment by wouter-asterisk** [comment]
This is what i want, this is exactly what i done (more than one), but still i get this error. 
https://www.youtube.com/watch?annotation_id=annotation_2964442527&feature=iv&src_vid=FrXx0mrTNRk&v=kz_iPjpht7M

Then you say:
1 PMS : Settings - General - Sign In
2 PlexConnect : Settings - MyPlex Sign In

But i dont see 1: https://www.dropbox.com/s/8vfhs5aa3ictypi/Untitled-1.png?dl=0
and second; its is a script, python thing.... i dont follow the instruction for sign in? Sign in into windows? Cause all i do is run plexconnect.py just like the video above...

**Comment by CyberGhost84** [comment]
1. u need to go to the Server Tab not the Web Tab.

2. on the atv open plexconnect, go to settings and sign into myPlex

**Comment by wouter-asterisk** [comment]
i am playing it true trailers (atv3) and i was already signed in into server tab
.....

**Comment by CyberGhost84** [comment]
Is your Plex Media Server also signed in?

**Comment by wouter-asterisk** [comment]
You mean like this: https://www.dropbox.com/s/dbdg40bfi074yei/2.png?dl=0

**Comment by CyberGhost84** [comment]
Yes there u need to sign into your myplex account and publish your server.

**Comment by wouter-asterisk** [comment]
thats already done

**Comment by CyberGhost84** [comment]
Sry but on the picture above your server isnt publisht to the network?

**Comment by wouter-asterisk** [comment]
it isnt published on the web, thats correct

**Comment by gipasoft** [comment]
I have same issue in attechement my plex connect log and the plex screenshot.
I am sing into myplex account and my server is published on the web!
[PlexConnect.zip](https://github.com/iBaa/PlexConnect/files/479000/PlexConnect.zip)
![plex access](https://cloud.githubusercontent.com/assets/1884550/18619292/f2e9f100-7df8-11e6-8dbe-007b26a34bd3.PNG)
![plex remoteaccess](https://cloud.githubusercontent.com/assets/1884550/18619294/f8887424-7df8-11e6-8cc7-8d02a2ecf3fb.PNG)

**Comment by ConorMulhern** [comment]
@CyberGhost84 

I'm having the same issue issue with "Tailers is unavailable. Try again later" issue when trying to use the the AppleTV Trailers app to access Plex via PlexConnect.

I'm signed into my Plex account on my Plex server, and I have added my local network to the list of "networks that are allowed without auth". 

In your earlier post you mentioned;

> on the atv open plexconnect, go to settings and sign into myPlex

And this is where I get lost. There's no PlexConnect app on the AppleTV, and the Trailers app doesn't have a settings menu, where are signing into myPlex on the Appletv? Are you setting this in the PlexConnect's `Settings.cfg` file?

**Comment by cb83** [comment]
I was able to solve this issue by entering the IP address of my Plex Media Server under the setting for: **"List of IP addresses and networks that are allowed without auth"** which can be found under Settings > Server > Network

16:00:59 PlexAPI: No Response from Plex Media Server
16:00:59 PlexAPI: We failed to reach a server. Reason: Unauthorized

The "Unauthorized" message tipped me off, so on a hunch I thought that entering the IP address of the server itself would work, since PlexConnect is calling the PMS on the same machine. Not 100% sure if this is the best solution, but it seems to be functioning fine, now!

I have an AppleTV 3 
Running PMS 1.1.4.2757

**Comment by gipasoft** [comment]
thanks @cb83 I have solved the issue entering the Plex Media Server IP under the settings for:  "**List of IP addresses and networks that are allowed without auth**"

**Comment by lilamadelief** [comment]
worked for me as well added the Ip and now I the message is gone. However when I try to play a movie, I get an error occured loading this content. Also I don't see the metadata anymore.

**Comment by lilamadelief** [comment]
Well just ignore my message. I added the IP of the ATV and the one of the PMS and all works.

**Comment by cb83** [comment]
I actually had the same issue with the movie not playing when I entered only the IP address of the PMS. So I changed it and just gave unauth access to anything on my local network by using the ip address + submask: 192.168.1.0/24 

Now it works like a charm.
