### ISSUE TITLE
New python url for aTVJailbreak

### ISSUE THREAD

**Issue by wahlmanj** [iBaa/PlexConnect#450]
https://github.com/iBaa/PlexConnect/blob/master/support/aTV_jailbreak/README.txt

Line 6 etc, needs updated instructions:

https://github.com/wahlmanj/atvjailbreak/commit/96db8641d4a5483a5d5031682cdcbd2e2f21b284

**Comment by sourpetchkid** [comment]
Have found new copy of Python for tvOS and iOS [here](https://github.com/pybee/Python-Apple-support).

**Comment by moodyblue** [comment]
@wahlmanj Done. Thanks.
