### ISSUE TITLE
How do I completely uninstall / remove plexconnect and undo any changes it has made under OS X ?

### ISSUE THREAD

**Issue by p4madeus** [iBaa/PlexConnect#452]
I used plexconnect briefly... it worked... great, but I no longer use it and want to completely remove / de-install it from my system and undo any other configuration changes it may have made. How does one accomplish this?

**Comment by sourpetchkid** [comment]
There is an uninstall file in `support/OSX` Or in `support/Win`. Run it in terminal or cmd.exe. Should remove if you have it installed as a DAEMON service. If it is not installed as a DAEMON, you can just delete the original files.
