### ISSUE TITLE
Dolby Digital not working on newer aTV firmware

### ISSUE THREAD

**Issue by marr** [iBaa/PlexConnect#458]
I am getting PCM playback as of a couple months ago. There is a forum post on the fix here:

http://forums.plex.tv/discussion/comment/1283332/#Comment_1283332

I will make a PR, its a simple fix!

**Comment by dnisbet** [comment]
This seems to have broken output on DTS soundtracks with the latest Plex server version 1.5.3.3580. Switching back to 'iOS' does seem to restore output, albeit in stereo.
