### ISSUE TITLE
Plex Cloud Beta - Video not playing

### ISSUE THREAD

**Issue by megahambone** [iBaa/PlexConnect#462]
Playing with plexconnect against the Plex cloud beta, I'm finding that everything works except video playback. I can get the sections, details and art shows up, but when I click play, I get an error about being unable to play the video. I would have assumed that myplex code would have worked as-is, but it seems something is different. Is there any logs or info I can provide to get this looked at?

**Comment by roidy** [comment]
>Is there any logs or info I can provide to get this looked at?

https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue

**Comment by megahambone** [comment]
will do tonight.

**Comment by megahambone** [comment]
Alright, here goes:

ATV Model/Firmware: ATV 3, Firmware, 7.2.2 (8015)
DNS Server set on the ATV: 10.208.15.1 (local DNS w/ forwarding setup to box on different subnet - has worked for every other plex server, local and remote, I'm confident it's not the issue)
Local IP Address of the device that PlexConnect is installed on: 10.208.16.1 
Device and Operating System (both plex and plexconnect): Computer, Debian Proxmox 4.2.6-1-pve #1 SMP Sat Dec 19 15:42:50 CET 2015 x86_64 GNU/Linux
Plex Media Server version: Plex Cloud Beta
Local IP of plex: N/A - Plex cloud is the one having issues:
PlexConnect Version: Downloaded Feb 11, 2017 from Github.
Settings.cfg:
[PlexConnect]
enable_plexgdm = True
ip_pms = 10.208.16.1
port_pms = 32400
enable_dnsserver = False
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = video-api-secure.wsj.com
port_webserver = 90
enable_webserver_ssl = True
port_ssl = 91
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = High
logpath = .

Media File details:http://pastebin.com/zPShahM8

Detailed Description: Everything works fine for plex local and remote servers, but I can not get any plexconnect instances to load media from the plex cloud beta, whether or not it's transcode, auto, or direct play (included log has transcode) - I can connect, list sections, list media, get the pre-play screen, but whenever I play the video, I get the message "An error occurred loading this content. Try again later"

Plexconnect.log: http://pastebin.com/ffxRrcSG

I'm PRETTY sure that the issue is that plex cloud reports the ip address as 127.0.0.1 in the xml file, but would prefer some confirmation. I'll try along those lines and report back if I have success.

**Comment by megahambone** [comment]
I'm going to see if I can't resolve it myself, will open another issue if I can't.
