### ISSUE TITLE
PlexAPI.py ignores settings as user may understand it

### ISSUE THREAD

**Issue by miwalter** [iBaa/PlexConnect#463]
Hi,
very good project, folks. Thanks very much!
In PlexAPI.py the detection function chooses the fastest server, that is getting back from the Plexserver. The Plexserver caches a couple of IPs - these may not be the same which the user tries to override with setting "pms_ip" (I did experience it...).
I would prefer if the function does what I would expect by setting this option. I forked the source and hardcoded my PMS-IP - I had the problem, that an IP from a (docker)container got back from the Plexserver and it was (nearly) always the fastest. So my setting was ignored.
Bye,
Mirko

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
