### ISSUE TITLE
Configuring DNS

### ISSUE THREAD

**Issue by andycarver101** [iBaa/PlexConnect#466]
I am attempting to run macOS server DNS instead of Plex Connect as I need certain apple services. Could you list all of entries so I can attempt to configure DNS via the server instead?

**Comment by sourpetchkid** [comment]
Loopback the following domains to `127.0.0.1`

loopback to 127.0.0.1...
  mesu.apple.com
  appldnld.apple.com
  appldnld.apple.com.edgesuite.net
"""

Then direct `trailers.apple.com` To your IP address of the computer with macOS Server on it.

**Comment by andycarver101** [comment]
Great work I just need to clarify the line is it the entire section of code that requires removal?

And have you known the macOS DNS server to work with Plex connect more specifically the caching server.

**Comment by andycarver101** [comment]
I'm about to roll this out. Can i just change 'enable_dnsserver') =='True' to 'False'?

Also I have my DNS server forwarding requests for things it can't look up. If I loop back to localhost will it try and resolve to the forwarding server? I have port 80 and 443 open to outbound but my NAT points 443 to the server and 80 is blocked. Is this a problem?

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
