### ISSUE TITLE
No playback with dolby digital disabled after latest commit (ATV3)

### ISSUE THREAD

**Issue by CatFisce** [iBaa/PlexConnect#476]
After the latest commit 6e38e8d video won't play unless dolby digital is set to auto. Another user posted a similar issue on plex forums 2 days ago (http://forums.plex.tv/discussion/267371/will-not-play-any-transcoded-material#latest). Reverting to e9a37a9 fixes it or by setting dolby digital to auto.

**Comment by ewturner** [comment]
I'm seeing this issue, but I think the commit listed here to revert is incorrect. Reverting 82e880ee8d7c94ccf11f4a0afaa1926970385ed4 and 845322d486e066b6f9f62a4e4747a7e2f343e0e0, which are both related to "AC3 5.1," solved the problem for me. I also didn't have any luck with the suggest Dolby Digital setting workaround.

**Comment by moodyblue** [comment]
@ewturner what happens when you activate DD with the latest PlexConnect ? My ATV plays fine if DD is enabled or auto. If DD is disabled the video freezes.

**Comment by itzeddie** [comment]
I experienced the same issue, rolling back both mentioned by @ewturner fixed sound for me also. FYI @moodyblue with DD set to ON I got no sound at all.

**Comment by moodyblue** [comment]
Please test with https://github.com/moodyblue/PlexConnect.git

If successfull I will ask roidy to commit to master.

**Comment by camrun91** [comment]
I tried the dolby digital thing and it did not seem to fix it. I will try testing with the other branch today and see if it works.

**Comment by camrun91** [comment]
the moody blue fork worked for me.

**Comment by moodyblue** [comment]
My fork has been merged with iBaa's.

**Comment by moodyblue** [comment]
Please close your issue. It has been solved with the latest commit.
