### ISSUE TITLE
Only playing shared library

### ISSUE THREAD

**Issue by Jabigb** [iBaa/PlexConnect#478]
I've just tried installing plexconnect for the first time, and cant get any of my libraries to play. They open up normally, but pause on playback. However my shared libraries play fine. Any ideas why this is? Thanks

**Comment by moodyblue** [comment]
Please test with https://github.com/moodyblue/PlexConnect.git

If successfull I will ask roidy to commit to master

**Comment by Jabigb** [comment]
Awesome it worked, Thanks

**Comment by moodyblue** [comment]
My fork has been merged with iBaa's.

**Comment by moodyblue** [comment]
Please close your issue. It has been solved withthe latest commit.
