### ISSUE TITLE
Failed to connect on 443

### ISSUE THREAD

**Issue by haxcop** [iBaa/PlexConnect#479]
Hi guys,
I just recently update to the latest plexconnect version and now i'm getting this error

`Failed to connect to HTTPS on 10.0.1.2 port 443: [SSL] PEM lib (_ssl.c:2718)`

I checked the used ports and 443 is not in use locally. 
Any ideas that can help me out?

OS Windows 7

Thanks!

**Comment by YoannZ** [comment]
Is your port open?

**Comment by moodyblue** [comment]
Maybe an expired cert ? Please report issues here -> https://forums.plex.tv/categories/appletv-plexconnect

**Comment by haxcop** [comment]
Yes the port is not being used. @YoannZ

**Comment by haxcop** [comment]
Fixed: the Cert was being created corrupted in somehow/// 
On windows 7 if the script fails to run in port 443 check the trailer.pem file and delete all erroneous characters, open the key file and copy the code and then paste it into the trailers file after ends the current code.
this should solve the issue.

**Comment by haxcop** [comment]
Another Solution to this issue is:
Verify you have Python2.7.8 running for this. I installed and used without any issues. 
https://forums.plex.tv/discussion/134109/failed-to-connect-to-https-on-xxx-xxx-x-xx-port-443-ssl-pem-lib-ssl-2525
