### ISSUE TITLE
Clock not displaying properly

### ISSUE THREAD

**Issue by krugster** [iBaa/PlexConnect#482]
Hello team, I just upgraded to the latest commits and noticed that the on screen clock is not displaying properly.  The main clock is cut off in the center of the screen, and the "Ends at..." is misaligned at the bottom.

See the attachment[
![2017-04-30 20 51 56](https://cloud.githubusercontent.com/assets/299362/25567517/44f5fdd8-2de7-11e7-9a45-00f28d2319c1.jpg)
](url)

**Comment by krugster** [comment]
Sorry it's upside down...

**Comment by moodyblue** [comment]
Please report issues here -> https://forums.plex.tv/categories/appletv-plexconnect

**Comment by krugster** [comment]
https://forums.plex.tv/discussion/269683/clock-not-displaying-properly/p1?new=1

**Comment by krugster** [comment]
Worked around by changing position of clock to Right and then back to Center
