### ISSUE TITLE
Old version stopped working - installed fresh and getting error 10053?

### ISSUE THREAD

**Issue by gleep52** [iBaa/PlexConnect#487]
We've been using an old version of plexconnect for a long time, year or more.  We've never had to update it - and I enjoyed the large icons instead of the new short scroll list - but I want it working more than anything.  Since our old version stopped, I reinstalled from a fresh copy and used my old certs to make things easier... After tweaking the config file back to my old settings, I'm getting a ton of information in the log file, and it just keeps going and going until finally it says: 

> 
> 13:35:41 XMLConverter: ====== aTV-XML finished ======
>13:35:41 Settings: getsetting allow_gzip_atv=False
>13:35:41 WebServer: File Not Found:
>Traceback (most recent call last):
>  File "C:\Program Files (x86)\PlexConnect\WebServer.py", line 230, in do_GET
>    self.sendResponse(XML, 'text/xml', True)
>  File "C:\Program Files (x86)\PlexConnect\WebServer.py", line 92, in sendResponse
>    self.end_headers()
>  File "C:\Python27\lib\BaseHTTPServer.py", line 423, in end_headers
>    self.wfile.write("\r\n")
>  File "C:\Python27\lib\socket.py", line 328, in write
>    self.flush()
>  File "C:\Python27\lib\socket.py", line 307, in flush
>    self._sock.sendall(view[write_offset:write_offset+buffer_size])
>error: [Errno 10053] An established connection was aborted by the software in your host machine
>

Here is my settings.cfg file:

> [PlexConnect]
> enable_plexgdm = False
> ip_pms = 192.168.1.5
> port_pms = 32400
> enable_dnsserver = True
> port_dnsserver = 53
> ip_dnsmaster = 8.8.8.8
> prevent_atv_update = True
> enable_plexconnect_autodetect = True
> ip_plexconnect = 192.168.1.5
> hosttointercept = trailers.apple.com
> port_webserver = 80
> enable_webserver_ssl = True
> port_ssl = 443
> certfile = ./assets/certificates/trailers.pem
> allow_gzip_atv = False
> allow_gzip_pmslocal = False
> allow_gzip_pmsremote = True
> loglevel = High
> logpath = .
> 

I'm not sure which file is not found, and I'm only getting this out of the blue.  I'm not sure when it quit working, we haven't been using Plex on our old ATV3 in a month or more I guess - but if someone has some magic to getting this working - I'd be much appreciated.

[PlexConnect-error.txt](https://github.com/iBaa/PlexConnect/files/1033731/PlexConnect-error.txt)

**Comment by gleep52** [comment]
I don't see the comment here - but Cyb3rGh05t posted and said to add the ip address of our plex connect device to our auto auth list.  I did so, but still get the same error as this after a long time of processing all the stuff in the attached .txt file.  I tried adding my entire subnet just to be safe of DHCP changes, etc... 

> 20:35:03 XMLConverter: ====== aTV-XML finished ======
> 20:35:03 Settings: getsetting allow_gzip_atv=False
> 20:35:03 WebServer: File Not Found:
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\PlexConnect\WebServer.py", line 230, in do_GET
>     self.sendResponse(XML, 'text/xml', True)
>   File "C:\Program Files (x86)\PlexConnect\WebServer.py", line 92, in sendResponse
>     self.end_headers()
>   File "C:\Python27\lib\BaseHTTPServer.py", line 423, in end_headers
>     self.wfile.write("\r\n")
>   File "C:\Python27\lib\socket.py", line 328, in write
>     self.flush()
>   File "C:\Python27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10053] An established connection was aborted by the software in your host machine

Does anyone else have any ideas?

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
