### ISSUE TITLE
Subtitles Issue with pms 1.7.5 and atv3

### ISSUE THREAD

**Issue by tvreged** [iBaa/PlexConnect#490]
Hi, I have a fairly new issue with showing subtitles in atv3. Ever since I updated pms to 1.7.5 it won't show most subtitles on atv3. It also glitches to a random part of the file when skipping forward. Only when I choose no subtitles in the pre-play screen, the media plays fine.

Here is my most recent log:

```
01:02:42 PlexConnect: started: 01:02:42
01:02:42 PlexConnect: Version: 0.5-dev-230417
01:02:42 PlexConnect: Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
01:02:42 PlexConnect: Host OS: win32
01:02:42 PlexConnect: PILBackgrounds: Is PIL installed? False
01:02:42 PlexConnect: IP_self: 192.168.0.100
01:02:42 DNSServer: started: 01:02:42
01:02:42 DNSServer: ***
01:02:42 DNSServer: DNSServer: Serving DNS on 192.168.0.100 port 53.
01:02:42 DNSServer: ***
01:02:42 WebServer: started: 01:02:42
01:02:42 WebServer: ***
01:02:42 WebServer: WebServer: Serving HTTP on 192.168.0.100 port 80.
01:02:42 WebServer: ***
01:02:42 WebServer: started: 01:02:42
01:02:42 WebServer: ***
01:02:42 WebServer: WebServer: Serving HTTPS on 192.168.0.100 port 443.
01:02:42 WebServer: ***
01:02:54 PlexAPI: ***
01:02:54 PlexAPI: poke plex.tv - request Plex Media Server list
01:02:54 PlexAPI: ***
01:02:55 PlexAPI: poke CosmosSE (45f2b8f5d672838358ac16d7c321ded6a7e0650c) at http://192.168.0.100:32400
01:02:55 PlexAPI: poke CosmosSE (45f2b8f5d672838358ac16d7c321ded6a7e0650c) at http://53.146.155.225:15727
01:02:55 PlexAPI: response CosmosSE (45f2b8f5d672838358ac16d7c321ded6a7e0650c) at http://192.168.0.100:32400
01:02:55 PlexAPI: Servers (local, plex.tv, MyPlex): 2
01:02:56 PlexAPI: No Response from Plex Media Server
01:02:56 PlexAPI: We failed to reach a server. Reason: [Errno 10061] No connection could be made because the target machine actively refused it
01:02:56 PlexAPI: Traceback:
Traceback (most recent call last):
  File "C:\PlexConnect-master\PlexAPI.py", line 432, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>

```
Please help,
Thanks!

**Comment by nadavcoh** [comment]
Hi,
I'm running PMS 1.7.5.4035 and haven't encountered any issues with subtitles on ATV3, so this might be a configuration issue.
When you try to play a file with subtitles enabled, do you get some sort of error message on ATV, or does the video play without subtitles?
It seems that the log you posted is from a session that could not connect to PMS. Could you please post one where you actually encountered the issue? Also please attach your PlexConnect.log file with `loglevel` set to `High` (you can have a look [here](https://github.com/iBaa/PlexConnect/wiki/How-to-report-an-issue) if you don't know how to do this).

**Comment by tvreged** [comment]
Hi,
I've tried entering the trailers app again, but it's now stuck on "accessing trailers".

This is the log file from a few minutes ago:

[PlexConnect.txt](https://github.com/iBaa/PlexConnect/files/1133169/PlexConnect.txt)

I hope it shows what's wrong.
Thanks!

**Comment by nicoonline** [comment]
Same issue here
No subtitle since pms 1.7.5

**Comment by nicoonline** [comment]
Hello,
ANY UPDATES ?

**Comment by mvfcva** [comment]
Hello
Same here since PMS 1.7.5
Looks like XMLConverter cannot read codecs from PMS, and everything goes ATVNative - False and then transcoded (even files that are ATV compatible and should go directplay)

**Comment by tvreged** [comment]
Updated PMS to 1.8.1, working fine!

**Comment by nicoonline** [comment]
I did the upgrade but not working for me
Still no subtitles

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
