### ISSUE TITLE
ATV2 No Internet Connection

### ISSUE THREAD

**Issue by dadipsetdon** [iBaa/PlexConnect#492]
I installed PlexConnect a few months ago, and it was working great.  I got a new router after that, but set static IP's for my PMS and my ATV2 the same as before. However, when my PMS isn't on (it's just my Mac, which I don't leave on all the time), my ATV2 doesn't get WiFi connection. It sees the WiFi network, but I can't access apps (like Netflix). It just shows two icons instead of all of them.  I tried turning on my Mac and re-running the script, and then it magically worked, but after restarting the ATV, same problem.  

Does this have to do with how I set up my DNS? I have an ASUS router (Linux-based).   Or does my PMS always need to be on in order for the ATV to connect?

**Comment by Cyb3rGh05t** [comment]
If you changed the DNS of the apple tv then the plexconnect script needs to run all time you wanna connect to the internet. If you do not run the script then you need to the DNS back to automatic instead of manual on the apple tv

**Comment by dadipsetdon** [comment]
Great thanks for clearing that up!
