### ISSUE TITLE
Two different networks. Remote server Plex

### ISSUE THREAD

**Issue by frozenxis** [iBaa/PlexConnect#494]
Hi.

I have the following situation:

**House 1** : (external ip: 1.2.3.4)
1. router(ip:192.168.100.1) with port forwarding (53->53, 80->880, 443->4443, 32400->32400)
2. ubuntu(ip: 192.168.100.188) headless server(Version 15.10) with Plex (Version 3.14.1) & plexconnect (Version: 0.5-dev-230417)
3. plexconnect goes on 880 and 4443 because i have Apache running on same machine

**House 2** : (external ip: 5.6.7.8)
1. router(ip:192.168.1.1)
2. apple tv 3(ip:192.168.1.13) with dns: 1.2.3.4 and certificate installed from 1.2.3.4/trailers.cer (success) because http://trailers.apple.com/trailers.cer doesn't work

> 00:25:34 DNSServer: DNS request received!
> 00:25:34 DNSServer: Source: ('5.6.7.8', 53482)
> 00:25:34 DNSServer: Domain: trailers.apple.com
> 00:25:34 DNSServer: ***intercept request
> 00:25:34 DNSServer: -> DNS response: 192.168.100.188

Apple TV apps like netflix and youtube work ok and i can see them in the log, but Trailers is going "Trailers is unavailable" Every. Single. Time.

Is there something wrong in my setup?

```
[PlexConnect]
enable_plexgdm = False
ip_pms = 192.168.100.188
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = False
ip_plexconnect = 192.168.100.188
hosttointercept = trailers.apple.com
port_webserver = 880
enable_webserver_ssl = True
port_ssl = 4443
certfile = ./assets/certificates/trailers.pem
loglevel = High
logpath = .
```

**Comment by frozenxis** [comment]
i tried shutting down apache and starting Plex on 80 and 443, remade the router forwarding... still doesn't work

> 15:00:00 WebServer: WebServer: Serving HTTP on 192.168.100.188 port 80.
> 15:00:00 WebServer: ***
> 15:00:00 WebServer: started: 15:00:00
> 15:00:00 WebServer: ***
> 15:00:00 WebServer: WebServer: Serving HTTPS on 192.168.100.188 port 443.
> 15:00:00 WebServer: ***
> 15:00:49 WebServer: serving *.cer: /trailers.cer  // downloaded from appletv using 1.2.3.4/trailers.cer
> 15:01:02 DNSServer: DNS request received!
> 15:01:02 DNSServer: Source: ('5.6.7.8', 53868)
> 15:01:02 DNSServer: Domain: trailers.apple.com
> 15:01:02 DNSServer: ***intercept request
> 15:01:02 DNSServer: -> DNS response: 192.168.100.188

**Comment by frozenxis** [comment]
still not able to figure it out. anyone?

**Comment by jswetzen** [comment]
Maybe you’ve already figured it out, but try changing `ip_plexconnect` to 1.2.3.4. Right now the DNS says it’s handing out an internal address for trailers.apple.com, and that won’t be available in house 2. The external one is what you want. And keep Apache turned off, because Apple TV needs to use those ports to access Plex.

**Comment by jswetzen** [comment]
By the way, I’ve got almost the same setup, except that PlexConnect and Apple TV are both in house 2. That way you can keep Apache in house 1, and you don’t have to expose the DNS server publicly (which is a *really* bad idea).

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
