### ISSUE TITLE
Allow host name in ip_pms, not just IP

### ISSUE THREAD

**Issue by jswetzen** [iBaa/PlexConnect#502]
I’ve got a remote plex server that I want to connect to, but the IP isn’t completely static. Instead I have dynamic DNS set up and would like PlexConnect to point to the hostname. It works fine if I just use the current IP, but the configuration doesn’t allow a hostname but defaults to the local IP instead. I think there should be a fairly simple fix, no?

**Comment by Fish2** [comment]
@jswetzen I have allowed this in my fork but needs more testing to see if it is stable https://github.com/Fish2/PlexConnect

**Comment by moodyblue** [comment]
I don't understand the need for this request. Why don't you login to plex.tv in the ATV and enable remote connections in PMS ? Or do you use an old PMS version that does not support remote connections ? In that case a private VPN might be an alternative.

**Comment by jswetzen** [comment]
So can I just set ip_pms to anything and find my server in the app? That sounds neat, I’ll have to try that!

**Comment by moodyblue** [comment]
Closing. This type of discussions are better handled in the forum.
