### ISSUE TITLE
After setting up 10 times and triple checking everything: still getting "trailers is unavailable"

### ISSUE THREAD

**Issue by gerbenvandijk** [iBaa/PlexConnect#503]
Long time PlexConnect user here, was allways using osx, but recently moved my PMS to a windows machine.
Have done the setup exactly as described in the wiki (multiple times by now, resetting the atv each time), have carefully made sure all my settings are correct and  have looked at the logs (nothing seems wrong there). Also had no issues installing the certificate on the apple tv, but all of the above is still to no avail; the trailers app is still showing "trailers in unavailable". Hoping if anymore can make more sense of this then I can as I'm not sure what else to try.

ATV model and version: ATV3, version 7.2.2
DNS server on the ATV: 192.168.178.35
Local IP of the device that plexConnect is installed on: 192.168.178.35
OS that plexConnect is installed on: Windows 10, latest version, all updates installed
PMS server version: 1.9.6.4429
IP of PMS server: 192.168.178.35
PlexConnect version number: downloaded from this GIT repo on 10/11/2017 (date of writing)

Attached are the settings.cfg file and PlexConnect.log.

Thanks a lot in advance!

[Settings.cfg.txt](https://github.com/iBaa/PlexConnect/files/1461014/Settings.cfg.txt)

[PlexConnect.log](https://github.com/iBaa/PlexConnect/files/1461013/PlexConnect.log)

**Comment by izznogooood** [comment]
Windows has a default webserver running on port 80, you need to disable it.

**Comment by Drewbie1974** [comment]
The log shows that PlexConnect starts on post 80 and 443 so it’s not that something else is using the port.

Is the correct ceryificate file in the plexconnect location?  I would also suggest you ask in the forum as plexconnect is not actively developed and support has always been in the forum and the core users are still there to help

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
