### ISSUE TITLE
PlexConnect support has ended

### ISSUE THREAD

**Issue by moodyblue** [iBaa/PlexConnect#504]
Therefore it's useless to post bugs or requests in this github repo. There is an active community trying to maintain the product alive in https://forums.plex.tv/categories/appletv-plexconnect

**Comment by jswetzen** [comment]
Is anyone else maintaining a fork that the community can collaborate on? Or is it possible to add some more people with access to this repo to maintain it here? @iBaa?

**Comment by moodyblue** [comment]
Only @iBaa can add more authors to this repo. I've asked him to add me but he never replied. The latest changes were applied by @roidy upon my request, but I don't know how long this will be possible.

Forking a new repo is easy, the problem is to give focus to it. Google gives focus to this repo, and so do many "easy installers" (docker, Synology, OSX).

Besides the "what repo to use" question, IMHO there are other important questions to consider if a team decides to maintain he product:
1. @iBaa had a "legion" of testers, how many would we have now ? PlexConnect runs in many many platforms, depends on Python 2.7, and may require special parametrization in Apache, Nginx, or whatever other web app is installed on the same machine contending for ports 80, 53 and 443
2. I don't know the "internals" of the product. Neither @roidy. Is there anybody out there that is willing to do it ? Making changes on a non-documented product, without access to the developer, well, it can be done, but it's very risky
That's why I've refrained from making changes myself. My activity has been limited to changes to assure that PlexConnect works with recent PMS versions.

Of course I will be glad to contribute to a more ambitious project.

**Comment by jswetzen** [comment]
I have a lot of spare time on my hands right now, but only for a few weeks. I could fork and make the most urgent changes, but I wouldn’t be able to update it regularly. I’m a developer and could easily review pull request for code quality and function though, so if people could find it, accepting fixes from the community would not be an issue.

Another point worth considering is that this project is coming to an end. It’s usefulness is only going to diminish as old Apple TVs are thrown away. That may be why @iBaa isn’t giving it attention anymore and it also makes it harder to gain momentum for a fork.

Continuing with this repo would really be best, and I would be happy to review and approve pull requests. @iBaa: As I’ve said I’m a professional developer and can show credentials both from open source projects and employment.

**Comment by moodyblue** [comment]
@jswetzen I've created a channel in Slack so that we can talk. Pls join

https://join.slack.com/t/plexconnect2/shared_invite/enQtMjkzMzkyNjI4MjI4LWFlOTRjNzE4YTY5NjQ2ZTZmM2RjYzczM2NmN2UzZDY2ZDVjNjg0NThkMWYwZTQ4MDE3NTg4YTMxZWViM2IyODc
