### ISSUE TITLE
Photo Play Incorrect Image Size

### ISSUE THREAD

**Issue by evangutierrez** [iBaa/PlexConnect#511]
I'm trying to view some 1920x1080 slides (PNGs and JPGs) through my library but the are underscanned/resized and seem letterboxes. Any thoughts on how to change this? I've searched the settings both on my computer server and on my Apple TV (3rd Generation)

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
