### ISSUE TITLE
Channels are broken

### ISSUE THREAD

**Issue by moodyblue** [iBaa/PlexConnect#516]
Comedy Central (and other channles) work Ok in iPad and PlexWeb, but not in PlexConnect.

In PlexConnect I can navigate through various screens, but when I try to stream any content it says that it's not available, Any clues ?

**Comment by moodyblue** [comment]
Solved in Feb/28 commit.

**Comment by Fish2** [comment]
@moodyblue what commit was it for reference i can't find any related to this in master

**Comment by moodyblue** [comment]
To be honest I'm not sure which one. I've applied several pending pull
requests and then tested, the most likely to have solved it was the
taglines one.

2018-03-01 13:31 GMT+00:00 Fish2 <notifications@github.com>:

**Comment by Fish2** [comment]
Tag line would not of fix it that only information that can be displayed

**Comment by moodyblue** [comment]
Then maybe one of these
![imagem](https://user-images.githubusercontent.com/6073615/36869395-935dd382-1d93-11e8-9538-16724d750946.png)

**Comment by Fish2** [comment]
could be i might do a bit of testing to find out im think the video url commit. As when i was changing to https i was check that the https is the same repose as http so i would of seen a error then
