### ISSUE TITLE
Setting to change language

### ISSUE THREAD

**Issue by Calico90** [iBaa/PlexConnect#523]
Hi,
I noticed PlexConnect supports several languages. I assume it not uses the same language as the OS or the Plex server. It could be nice if there would be an setting in Plex connect to change this manually for PlexConnect, ignoring the system or Plex server language.

**Comment by moodyblue** [comment]
Help and suggestion requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
