### ISSUE TITLE
Latest APTV3 V. 7.2.2 (8015)

### ISSUE THREAD

**Issue by haxcop** [iBaa/PlexConnect#529]
Hi Guys I have been force recently to update my atv and now seems not not be working the plexconnect on trailers. have any of you sort this out?
Thanks in advance

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect

**Comment by haxcop** [comment]
@moodyblue Got it thanks for the advise
