### ISSUE TITLE
Feature request for skipping the Seasons page for one-season shows

### ISSUE THREAD

**Issue by ElleshaHackett** [iBaa/PlexConnect#531]
Feature request for PlexConnect to skip the "Seasons" page when a Show has only one season. So go from Shows directly to Episodes page of the only available season. Instead of from Shows to Seasons to Episodes.

This is also an awesome option in Plex Web.

**Comment by roidy** [comment]
Pretty sure PlexConnect already has this option:-

Settings->TV Shows->Flatten Season
