### ISSUE TITLE
Trailers Icon & Text are not being Intercepted or Changed into the Plex Icon & Text

### ISSUE THREAD

**Issue by RypeDub420** [iBaa/PlexConnect#532]
I still see the Apples Trailers icon and text.

If this project isn't being actively updated anymore, which files can I check to modify for testing and potentially fixing?

I'm pretty sure I'm using the pre 2013 Apple TV on Software Version 7.2.2.

**Comment by Fish2** [comment]
just to check have you followed the wiki https://github.com/iBaa/PlexConnect/wiki/Changing-the-Trailer-app-icon and also to note the text can't be changed only the icon

**Comment by moodyblue** [comment]
Help requests in the forum, please

https://forums.plex.tv/discussion/299580/how-do-you-change-the-trailers-icon-w-o-openplex-the-original-thread-was-deleted
