### ISSUE TITLE
[bug] FLAC doesn't show playtime

### ISSUE THREAD

**Issue by ElleshaHackett** [iBaa/PlexConnect#536]
When playing FLAC files it shows the current time but the end time is `00:00`. Tested on version 0.7-dev020318.

**Comment by Calico90** [comment]
@moodyblue seems that it was previously reported already at 30 Nov 2014 here https://github.com/iBaa/PlexConnect/issues/298.

**Comment by ElleshaHackett** [comment]
This is still an issue. Can we fix this somehow?
