### ISSUE TITLE
Stacked files not working

### ISSUE THREAD

**Issue by dino0401** [iBaa/PlexConnect#539]
My Plexconnect(ATV3) doesn't play stacked files well. I've read this support stacked files since version 0.4. I'm using latest 0.7-dev but when I play stacked files, it just rewinds to beginning of first file. I also tested version 0.6 and 0.5-dev but failed. When I play stacked files with WEB or android app, it works well.

PMS and Plexconnect are installed on Synology NAS(DSM 5.2).
Plex Media Server Version: 1.13.4.5251

Any idea?

**Comment by moodyblue** [comment]
There are problems with stacked file support in PlexConnect. But I don't know how to fix them. One possible alternative is to merge files in a single one.

In case you know how to fix PlexConnect to handle stacked files correctly pls let me know. I would be happy to apply your changes to the main code.

**Comment by moodyblue** [comment]
Dup of #217
