### ISSUE TITLE
PlexConnect Suddently stopped Working HELP!?

### ISSUE THREAD

**Issue by cucurus123** [iBaa/PlexConnect#544]
Hello everyone!!
I Apologize for this Long Message.

(NOTE: If Im looking for help here is because I did ask for help at the Official PLEX Forum but didn't work)

My Name is Carlos, Im Writting you seeking help from someone experienced,

I own an Apple TV 3G, with iOS 7.2.2 Out of the Box. and my PLEX Media Server is Located in my Windows 10 PC

I got PlexConnect a few weeks after getting my device and It was working just fine, (this was like 6 months ago)

A couple days ago, everything just stopped working out of nowhere.

I tried several things since I know about systems, and stuff like that,
I started with the basics, Restart my Device, Refresh my wi-fi connection, Tested my conectivity, by setting up the DNS to Automatic Again. and It was able to connect to YouTube etc...

Then I went to my PC and looked at the CMD window from Plexconnect,py there I notice that my PC was not comunicating with my ATV all I was seeing was this (NOTE: I obviously changed back my DNS to Manual after the Test)

Oct 14,2018 01:26:05 PlexConnect: ***
Oct 14,2018 01:26:05 PlexConnect: PlexConnect
Oct 14,2018 01:26:05 PlexConnect: Press CTRL-C to shut down.
Oct 14,2018 01:26:05 PlexConnect: ***
Oct 14,2018 01:26:05 PlexConnect: Started
Oct 14,2018 01:26:05 PlexConnect: Version: 0.5-dev-161017
Oct 14,2018 01:26:05 PlexConnect: Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
Oct 14,2018 01:26:05 PlexConnect: Host OS: win32
Oct 14,2018 01:26:05 PlexConnect: PILBackgrounds: Is PIL installed? False
Oct 14,2018 01:26:05 PlexConnect: IP_self: xxx.xxx.x.xxx
Oct 14,2018 01:26:05 DNSServer: Started
Oct 14,2018 01:26:05 DNSServer: ***
Oct 14,2018 01:26:05 DNSServer: DNSServer: Serving DNS on xxx.xxx.x.xxx port 53.
Oct 14,2018 01:26:05 DNSServer: intercept: ['trailers.apple.com'] => xxx.xxx.x.xxx
Oct 14,2018 01:26:05 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
Oct 14,2018 01:26:05 DNSServer: forward other to higher level DNS: 8.8.8.8
Oct 14,2018 01:26:05 DNSServer: ***
Oct 14,2018 01:26:05 WebServer: Started
Oct 14,2018 01:26:05 WebServer: ***
Oct 14,2018 01:26:05 WebServer: WebServer: Serving HTTP on xxx.xxx.x.xxx port 80.
Oct 14,2018 01:26:05 WebServer: ***
Oct 14,2018 01:26:05 WebServer: Started
Oct 14,2018 01:26:06 WebServer: ***
Oct 14,2018 01:26:06 WebServer: WebServer: Serving HTTPS on xxx.xxx.x.xxx port 443.
Oct 14,2018 01:26:06 WebServer: ***

Long story short. My DNS was set to Manual, with my IP Address, I have not updated ANYTHING since I Installed PlexConnect (Except my PMS which I always have been updating with no further problems)

After that I noticed that the “Trailers Profile” was missing, I was trying to Reinstall the Certificate (http://trailers.apple.com/trailers.cer) but I was getting the Error 109 every single attempt.

I Restored my ATV to Factory Settings, and did everithing again. with same results. I even tried to put my IP Address instead of trailers.apple.com (example http://123.456.0.xxx/trailers.cer ) but it keeps loading with no results

Now I have Deleted Python and PlexConnect-master folder, and I did a “fresh” Install. (I even did a Registry Clean Up after the Uninstall)
As you can see I was previously Running Python 2.7.14 and PlexConnect 0.5-dev-161017

Now Im facing another Problem, I Installed Python 2.7 and PlexConnect v0.5 and Every time I run Plexconnect.py the CMD window Closes inmediately. Here is when I start to google for help.

I followed some postings from the Official Plex Forum, someone said that PlexConnect.py Creates a log file when you open the file, unfortunately there was no log file so I decided to Manually open the .py file and this is what I get

C:\PlexConnect>PlexConnect.py
01:00:53 PlexConnect: ***
01:00:53 PlexConnect: PlexConnect
01:00:53 PlexConnect: Press CTRL-C to shut down.
01:00:53 PlexConnect: ***
01:00:53 PlexConnect: started: 01:00:53
01:00:53 PlexConnect: Version: 0.5
01:00:53 PlexConnect: Python: 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
01:00:53 PlexConnect: Host OS: win32
01:00:53 PlexConnect: PILBackgrounds: Is PIL installed? False
01:00:53 PlexConnect: IP_self: xxx.xxx.xxx.xxx
01:00:53 DNSServer: started: 01:00:53
01:00:53 DNSServer: ***
01:00:53 DNSServer: DNSServer: Serving DNS on xxx.xxx.x.xxx port 53.
01:00:53 DNSServer: intercept: ['trailers.apple.com'] => xxx.xxx.x.xxx
01:00:53 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
01:00:53 DNSServer: forward other to higher level DNS: 8.8.8.8
01:00:53 DNSServer: ***
01:00:53 PlexConnect: Shutting down.
01:00:58 DNSServer: Shutting down.
01:00:58 PlexConnect: shutdown
01:00:58 PlexConnect: shutdown

As I mentioned before I was Running Windows 10 I Used PowerShell and from this window I get something different

PS C:\PlexConnect> CMD.EXE /C PlexConnect.py
00:22:31 PlexConnect: ***
00:22:31 PlexConnect: PlexConnect
00:22:31 PlexConnect: Press CTRL-C to shut down.
00:22:31 PlexConnect: ***
00:22:31 Settings: add setting enable_plexgdm=True
00:22:31 Settings: add setting ip_pms=192.168.178.10
00:22:31 Settings: add setting port_pms=32400
00:22:31 Settings: add setting enable_dnsserver=True
00:22:31 Settings: add setting port_dnsserver=53
00:22:31 Settings: add setting ip_dnsmaster=8.8.8.8
00:22:31 Settings: add setting prevent_atv_update=True
00:22:31 Settings: add setting enable_plexconnect_autodetect=True
00:22:31 Settings: add setting ip_plexconnect=0.0.0.0
00:22:31 Settings: add setting hosttointercept=trailers.apple.com
00:22:31 Settings: add setting port_webserver=80
00:22:31 Settings: add setting enable_webserver_ssl=True
00:22:31 Settings: add setting port_ssl=443
00:22:31 Settings: add setting certfile=./assets/certificates/trailers.pem
00:22:31 Settings: add setting loglevel=Normal
00:22:31 Settings: add setting logpath=.
00:22:31 PlexConnect: started: 00:22:31
00:22:31 PlexConnect: Version: 0.5
00:22:31 PlexConnect: Python: 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
00:22:31 PlexConnect: Host OS: win32
00:22:31 PlexConnect: PILBackgrounds: Is PIL installed? False
00:22:31 PlexConnect: IP_self: xxx.xxx.x.xxx
00:22:32 DNSServer: started: 00:22:32
00:22:32 DNSServer: ***
00:22:32 DNSServer: DNSServer: Serving DNS on xxx.xxx.x.xxx port 53.
00:22:32 DNSServer: intercept: ['trailers.apple.com'] => xxx.xxx.x.xxx
00:22:32 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
00:22:32 DNSServer: forward other to higher level DNS: 8.8.8.8
00:22:32 DNSServer: ***
00:22:32 WebServer: started: 00:22:32
00:22:32 WebServer: Failed to connect to HTTP on XXX.XXX.X.XXX port 80: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions
00:22:32 PlexConnect: WebServer not alive. Shutting down.
00:22:32 PlexConnect: Shutting down.
00:22:37 DNSServer: Shutting down.
00:22:37 PlexConnect: shutdown
00:22:37 PlexConnect: shutdown
PS C:\PlexConnect>

I Googled the error 10013 and it is related to Ports and it seems that something can be using my port 80, I looked in the CMD but NOTHING is Using my Port 80. I ran the `netstat -ano` command.
I am also running PlexConnect.py as Adiministrator,  and the Whole Folder where plexconnect is located has All Permisions Granted.

I updated to PlexConnect v0.6 hoping that it may fix my problem but it did not

Honestly I dont know what else to try

**Comment by moodyblue** [comment]
Answered in the forum.
