### ISSUE TITLE
Can't connect to plex server

### ISSUE THREAD

**Issue by Sapphica** [iBaa/PlexConnect#547]
Everything has been working great for months, but today plexconnect can't seem to talk to my plex server. I get this error..

 File "C:\Python27\lib\urllib2.py", line 1148, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>

**Comment by moodyblue** [comment]
Please request support in the Plex forum https://forums.plex.tv/

**Comment by Sapphica** [comment]
thx for the help =D
