### ISSUE TITLE
PlexConnect not working in Mojave OS

### ISSUE THREAD

**Issue by endesse** [iBaa/PlexConnect#549]
After installing Mojave on my Mac I was rendered unable to run PlexConnect again. Maybe because it now has Python 3.7.1 or something else but it keeps throwing this error at me on startup:

Traceback (most recent call last):
  File "/Applications/PlexConnect-master/PlexConnect.py", line 19, in <module>
    import DNSServer, WebServer
  File "/Applications/PlexConnect-master/DNSServer.py", line 116
    print "ID {0:04x}".format((ord(paket[0])<<8)+ord(paket[1]))
                     ^
SyntaxError: invalid syntax

**Comment by moodyblue** [comment]
Install Python 2.7.15 https://www.python.org/downloads/release/python-2715/
