### ISSUE TITLE
Apple tv 3 resets itself after playing a while

### ISSUE THREAD

**Issue by mzigaib** [iBaa/PlexConnect#551]
After playing a while my apple tv it's kind of reseting itself, any tips?

**Comment by carlsteinhilber** [comment]
Ask in the forums, rather than here.
But it sounds like it's more an issue with your ATV than with plexconnect, so asking in the ATV forums would probably be your best bet. Sounds like your ATV is overheating, or has issues with it's power supply or mb.

**Comment by mzigaib** [comment]
That just happens with plexconnect with the others services I have no problem, I've already checked there and I couldn't find any answer on this matter. It seems that maybe there's something to do with buffering because it resets after more or less the same time playing but it it just my speculation. I was hoping that anyone else with the same problem have already come up with a solution.

**Comment by moodyblue** [comment]
Probably you are trying to play with a bitrate higher than 20Mbps.

Pls initiate one topic in the forums where help can be provided. I will maintain in github only the issues that require code changes, after validating that there is an issue in the forums.

**Comment by mzigaib** [comment]
Change the the player option to 'transcode' did the trick, I'll give further updates if I discover something new.
Thanks for the assistance.

**Comment by moodyblue** [comment]
What PlexConnect version are you using ? If this is what I think, it should be fixed on V0.6

**Comment by mzigaib** [comment]
I am using:
Mar 22,2019 21:20:20 PlexConnect: Version: 0.6-250218

**Comment by mzigaib** [comment]
The only thing is that now I am seeing more degradation on the image in certain parts mostly when thre are a lot of details and movement, I'll try to increase the bit rate now it is in 8.0.
