### ISSUE TITLE
Completely uninstall and clean up PlexConnect?

### ISSUE THREAD

**Issue by Mr-Doge** [iBaa/PlexConnect#552]
Hey guys, If I wanted to completely uninstall plexconnect and putting everything to previous state, what about that? I know there are uninstall scripts, and they remove the server! What about the Apple TV? Do I simply just default the DNS setting? Will the trailer work afterwards?

**Comment by moodyblue** [comment]
https://github.com/iBaa/PlexConnect/blob/master/README.md#support
