### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by peflanag** [iBaa/PlexConnect#555]
Hi Guys, 

I have moved plex to a new iMac running Catalina. Trying to ibstall plex connect again and when I run this command

sudo "/Applications/PlexConnect-master/PlexConnect.py"

I get the following error:

sudo "/Applications/PlexConnect-master/PlexConnect.py"
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/PlexConnect.py", line 19, in <module>
    import DNSServer, WebServer
  File "/Applications/PlexConnect-master/DNSServer.py", line 116
    print "ID {0:04x}".format((ord(paket[0])<<8)+ord(paket[1]))
                     ^
SyntaxError: invalid syntax

Any ideas?

Cheers

**Comment by moodyblue** [comment]
Can you pls try with the `before-dvr` branch ?

**Comment by peflanag** [comment]
I might have missed something but what does that mean?

**Comment by moodyblue** [comment]
![imagem](https://user-images.githubusercontent.com/6073615/69189234-e4427200-0b15-11ea-9fe2-8b6da75e7a97.png)

After selecting the `before-dvr` branch click on download

**Comment by peflanag** [comment]
Ah ok! Cool cheers. I’ll try that!

**Comment by peflanag** [comment]
Unfortunately that doesnt seemed to have worked either

sudo /Applications/PlexConnect-before-dvr/PlexConnect.py 
Traceback (most recent call last):
  File "/Applications/PlexConnect-before-dvr/PlexConnect.py", line 19, in <module>
    import DNSServer, WebServer
  File "/Applications/PlexConnect-before-dvr/DNSServer.py", line 116
    print "ID {0:04x}".format((ord(paket[0])<<8)+ord(paket[1]))
                     ^
SyntaxError: invalid syntax

**Comment by moodyblue** [comment]
What is your python version ?

**Comment by moodyblue** [comment]
Also, it's preferrable to put questions in the forum, you will reach a wider audience, and chances to get help are higher.

**Comment by moodyblue** [comment]
No evidence of this being a PlexConnect issue, Seems to be a user issue, therefore support is provided in the forum https://forums.plex.tv/tags/c/third-party/apps-tools/plexconnect
