### ISSUE TITLE
aTV 3 jb - create ur own button does not work

### ISSUE THREAD

**Issue by sasagr** [iBaa/PlexConnect#562]
I installed it today on the Apple TV 3 jailbroken and it seems to be working as Plex connect locally installed on the Apple TV and launched with the trailer button. 
However the OPTION B - create own PlexConnect button does not work. 
I get a “add site” button following and verification error. 
It seems the same error was already present on the Apple TV 2 with fw 6.x while working with the 5.3.

**Comment by wahlmanj** [comment]
Addsite is blocking it and I'm not sure how yet. I do not see it working on trailers as you say unless you are doing the normal plexconnect DNS hack back to your PlexConnect host. We have looked into this FAR here if you want to take a look but until addsite can be downgraded or unlocked (very doubtful of this) we are probably SOL. But hooray the aTV 3 is jailbroken so maybe there is hope.

https://forums.plex.tv/t/installing-a-new-app-on-appletv-without-hijacking-trailers/43716

**Comment by sasagr** [comment]
I must say that yes it seemed very unstable especially when I tried to install NitoTV ... but if I just install PlexConnect it works fine (no crashes so far).
I confirm that the local installation of PlexConnect with python and all the rest works very well.
I just followed the option A of https://github.com/iBaa/PlexConnect/blob/master/support/aTV_jailbreak/README.txt
with redirecting the trailer app back to aTV itself, replacing the DNSServer. So I m free to use the DNS setting as I like, as matter of fact I m using my smartdns options.

It would be "nicer" to have its own plexconnect button, as I have in the older atv2, but I guess I have to leave with what I achieved so far, that is already a bigger improvement from having to host plexconnect somewhere else.

**Comment by moodyblue** [comment]
Is there a ATV3 jb ? Where ? Can I have the link pls ?

**Comment by sasagr** [comment]
https://etasonatv.tihmstar.net

pls note it works with the AppleTV3,2 version only
So if you have the older model of Apple TV 3... you have to wait.
You can follow @tihmstar on twitter for news and support.

**Comment by moodyblue** [comment]
Thanks.

**Comment by moodyblue** [comment]
What about http://www.snow3rd.org/ ? Have you tested it ?

**Comment by sasagr** [comment]
no and I don't trust it. It has been there since at least 2 years and nobody talks about it in the important forums.
Just look at what and how they wrote this:
"Apple TV iOS should be below iOS 5.0.X."

**Comment by moodyblue** [comment]
Did you try to load the button with the process for a non-jb atv after (or before) the jb process ?

**Comment by sasagr** [comment]
I m not sure I understood your question.
Anyway... if this answer it, I jb the atv and followed the readme file
https://github.com/iBaa/PlexConnect/blob/master/support/aTV_jailbreak/README.txt
Option A works
Option B does not work
The answer is here https://github.com/iBaa/PlexConnect/issues/562#issuecomment-578995926

**Comment by moodyblue** [comment]
My ATV3 was not jb'ed and had the PlexConnect button. I have jb'ed the ATV3 and the PlexConnect button survived.

**Comment by sasagr** [comment]
That could be an idea though it will still keep the name of the previous button (ex.. trailers). Just have to find a guide on how to do it. I really forgot it. If you have a reliable one pls pass it to me. 
Hope not going out of topic :)

**Comment by moodyblue** [comment]
It's in the wiki https://github.com/iBaa/PlexConnect/wiki/Changing-the-Trailer-app-icon

**Comment by wahlmanj** [comment]
You can have a regular icon changed such as IMovie that has a new plexconnect icon which still points back to your plexconnect server.

OR

You can have an addsite added icon on a jailbroken Apple TV2 (iOS 5.3 or lower) which hosts plexconnect directly on the Apple TV itself.

**Comment by moodyblue** [comment]
> Does option A work on the JB aTV3 on iOS 7.4?
Yes, but python version is very old and fanart is not supported. Also I don't like the idea of generating logs in the ATV, better defaul logs to Off

**Comment by sasagr** [comment]
Interesting. Maybe since my atv3 is jb I can try to avoid a full data resetting and maybe run a uicache command?? and let the atv get the plexconnect icon from its local resident plexconnect folder. Will try

**Comment by wahlmanj** [comment]
I use this mainly when traveling.

**Comment by moodyblue** [comment]
> Locally yes the preferred method is still another PlexConnect host with pillow installed.

Why ?

**Comment by sasagr** [comment]
I have to find the guide to use iMovie then.

**Comment by wahlmanj** [comment]
When I am home why wouldn't I use fanart? When not at home (remote) and traveling light without my typical PlexConnect host why wouldn't I not use fanart since I don't care since I am not home and not about to bust out another device just for fanart?

**Comment by moodyblue** [comment]
I could give you a ton of motives to get rid of a service computer for PlexConnect:

1) Many users also use YouTube, Netflix and other apps. With a PlexConnect host these services are dependent on its availability
2) PlexConnect requires python 2.7.x which may not be easy to find, and be compatible, with PlexConnect
3) Installers for Synology, QNAP and MacOS are often impacted by new releases of these systems

My only problem of advising the PlexConnect community to adopt jb is because people (like you) that have jb'd ATV2s reported instability, and also, from what is reported in this thread, the jailbreak process is not yet mature

**Comment by wahlmanj** [comment]
Got it on IMovie:

www.icloud.com

**Comment by moodyblue** [comment]
python 2.7.6-3 is the latest we can install in the ATV3 ?

**Comment by wahlmanj** [comment]
As far as I’m aware, yes.

**Comment by sasagr** [comment]
uicache method did not work but eventually I don't care so much. I m fine with iMovie icon.
I followed the steps of https://github.com/iBaa/PlexConnect/issues/562#issuecomment-579482361  and all worked.
Now I m going to work on my other apple tv 3,1 :)

**Comment by sasagr** [comment]
apple tv 3,1 also perfectly working with plexconnect. Thanks...
one more thing... Is it possible to install PIL/Pillow and get the fanart?

**Comment by wahlmanj** [comment]
Nope.

**Comment by moodyblue** [comment]
Can you pls help me review [this wiki entry](https://github.com/iBaa/PlexConnect/wiki/Install-Guide-AppleTV-3) ?

**Comment by sasagr** [comment]
if it can help these are my notes:

apt-get update
apt-get upgrade
apt-get install cydia
(not sure if necessary but I preferred to install the following as well)
apt-get install libxml2-lib
apt-get install sqlite3
 
apt-get install python

download "https://github.com/linusyang/python-for-ios/releases/download/v2.7.6-3/python_2.7.6-3_iphoneos-arm.deb"

dpkg -i python_2.7.6-3_iphoneos-arm.deb

apt-get install git

reboot

cd /Applications

git clone git://github.com/iBaa/PlexConnect.git


- make sure you have good certs in /PlexConnect/assets/certificates
  if not, generate and add them...

In OSX/Windows terminal:
openssl req -new -nodes -newkey rsa:2048 -out ~/Desktop/trailers.pem -keyout ~/Desktop/trailers.key -x509 -days 7300 -subj "/C=US/CN=www.icloud.com"

openssl x509 -in ~/Desktop/trailers.pem -outform der -out ~/Desktop/trailers.cer && cat ~/Desktop/trailers.key >> ~/Desktop/trailers.pem

this is for iMovies -subj "/C=US/CN=www.icloud.com"
this is for Trailers -subj "/C=US/CN=trailers.apple.com"

- SFTP PlexConnect/support/aTV_jailbreak/Settings_Trailers.cfg to PlexConnect/Settings.cfg
  overwrite the later if already there
  this brings new defaults for PlexConnect@aTV, like disabling DNSServer

/etc/hosts
- add content of PlexConnect/support/aTV_jailbreak/hosts_addon_PlexConnect to /etc/hosts
  this redirects the trailer app back to aTV itself, replacing the DNSServer
change the line with trailers to this if you want iMovies 
127.0.0.1 	www.icloud.com

/etc/hosts
- optional: add PlexConnect/support/aTV_jailbreak/hosts_addon_preventATVUpdate
  this prevents aTV update

be sure you have installed the profile
http://trailers.apple.com/trailers.cer
or
127.0.0.1/trailers.cer

**Comment by moodyblue** [comment]
Thanks for your notes. They helped a lot. I'm making some changes to make life easier to others.

**Comment by moodyblue** [comment]
I've tried to generate certs in the ATV3 as follows:
```
cd /Applications/PlexConnect/assets/certificates/
openssl req -new -nodes -newkey rsa:2048 -out iMovie.pem -keyout iMovie.key -x509 -days 7300 -subj "/C=US/CN=www.icloud.com" -config /etc/ssl/openssl.cnf
openssl x509 -in iMovie.pem -outform der -out iMovie.cer
cat iMovie.key >> iMovie.pem
```
Certs are generated but they do not work. If I use windows to generate the certs they are Ok. Is there a way to generate certs in the ATV3 ?
