### ISSUE TITLE
USB certificate installation is still possible but link / instructions are dead

### ISSUE THREAD

**Issue by dstockton** [iBaa/PlexConnect#564]
The link...
```
[USB / iPhone Configuration Utility] (https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Certificate-via-USB)
```
... is dead. However, this method still works but just needs a little updating. I used the official [Apple Configurator 2] (https://apps.apple.com/us/app/apple-configurator-2/id1037126344?mt=12) app.

I followed this process on an ATV3 (rev A) which I didn't have the remote for...

1. Install Apple Configurator 2 & open it
1. Create a "New Profile"
1. Choose "Certificates"; then "Configure"
1. Browse to your trailers.cer file
1. Save the profile
1. Connect the ATV via USB
1. An icon for the ATV will appear; right click it and choose "Add Profile"
1. Browse to the profile saved in step 5
1. Apply everything and disconnect from USB

**Comment by dstockton** [comment]
To anyone searching for a way of installing the PlexConnect certificate when you don't have an official AppleTV remote control; you can use this method.

**Comment by moodyblue** [comment]
Thanks. I will create a new wiki page. This utility seems to be specific for Mac, is there a windows equivalent ?

**Comment by moodyblue** [comment]
Do you know if there is a method to generate certificates in the ATV3 ?

**Comment by moodyblue** [comment]
wiki page rebuilt, can you pls review it ?

**Comment by dstockton** [comment]
Wow! Great response time! :-)
Honestly, I don’t know anything about this utility and this is my first time trying PlexConnect - I just don’t have a remote for my ATV3 so just used a bit of logical thinking and tried the tool on my Mac. You can still download the old iPhone configuration utility for Windows which from what I saw on reddit still works. I just haven’t seen anyone ever mention this procedure using USB & current OSX app so wanted to share it for others that might try searching.
Thanks

**Comment by dstockton** [comment]
Reviewed - https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Certificate-via-USB LGTM 👍

**Comment by moodyblue** [comment]
Thanks a lot. I will now close this issue.
