### ISSUE TITLE
question - intercept apple tv

### ISSUE THREAD

**Issue by chichid** [iBaa/PlexConnect#567]
Is it possible to intercept the new Apple TV app? That would be neat!

**Comment by moodyblue** [comment]
These are the apps that can be intercepted

https://github.com/iBaa/PlexConnect/wiki/Intercepting-another-App

**Comment by chichid** [comment]
What's technically different between those apps and the new TV Icon, or the Movies Icon?

**Comment by carlsteinhilber** [comment]
They way they call for content. The apps that can be intercepted essentially make simple http requests and accept simple http responses (ie - that can then be intercepted and served by plexconnect's DNS server). Other apps like the Apple TV do not.
