### ISSUE TITLE
New v0.7 Release (Jan. 2020) breaks connection to Plugins/Channels 

### ISSUE THREAD

**Issue by mcsestak** [iBaa/PlexConnect#568]
I have WebTools installed and I have manually installed the Fox News plugin for Plex.  

Once I updated to v0.7, Plex Media Server could no longer access any of my plugins.  If I go to Channels, it simply says: "There is no content available."

As a test, I downgraded back to v0.6.  Immediately my FoxNews plugin reappeared.

**Comment by moodyblue** [comment]
Plug-in support is no longer available in recent PMS versions. What PMS version are you using ?

Pls note that sticking with old PMS versions may imply that you have to use old PlexConnect versions, I have no way to test recent PlexConnect versions with old PMS versions.

**Comment by mcsestak** [comment]
I am using the latest version of PMS - Version 1.18.7.2457.  But I've had to downgrade to PlexConnect v0.6 to get the plugins to appear.

Manually installing a plugin still works with PMS, as described here:
https://support.plex.tv/articles/201187656-how-do-i-manually-install-a-plugin/

**Comment by moodyblue** [comment]
@SheaSmith I've tracked this down to PlexAPI.py line 574, when you implemented Live TV & DVR.

Can you pls fix it ?

**Comment by moodyblue** [comment]
Fixed in the latest master. Can you pls test ?

**Comment by mcsestak** [comment]
Updated PlexConnect to version **0.7-240120** - manual plugins do not appear under Channels.
Downgraded PlexConnect back to version **0.6-250218** - manual plugins appear under Channels.

![v 6](https://user-images.githubusercontent.com/12754295/78680264-e6348400-78b0-11ea-81d8-d4d717059db0.png)
![v 7](https://user-images.githubusercontent.com/12754295/78680265-e6348400-78b0-11ea-865b-4504f7aae4a3.png)

**Comment by moodyblue** [comment]
Can you please install https://github.com/iBaa/PlexConnect.git instead of V0.7 ?

**Comment by mcsestak** [comment]
Yes!  That worked for me.  Plugins now appear with 7.1 build.

Thank you!  Great work!

**Comment by moodyblue** [comment]
Good. My area is geo blocked to Fox News, I can see the menus but not the contents.

But I still have to change the code, other plug-ins, such as FMoviesPlus, LetMeWatchThis, etc are not shown in the 0.7.1 menu, but are ok in 0.6 so probably I will need another test

**Comment by moodyblue** [comment]
Can you pls download again (same link) and test ? Thanks

**Comment by mcsestak** [comment]
OK - I copied over the build from the same link, but it seems the build
number is still the same?  Build-060420?

In any case, it still works fine!
