### ISSUE TITLE
Plex Icon on ATV3 - Not an issue

### ISSUE THREAD

**Issue by franconovel** [iBaa/PlexConnect#569]
This is for update ATV3 Icon change guide:

If ATV3 is already jailbroken you can change the icon of iMovie with Plex icon, you need to replace:
/private/var/mobile/Library/Caches/AppleTV/MainMenu/iMovieNewAuth@1080.png

**Comment by moodyblue** [comment]
Thanks.

In my ATV3 the file is named `iMovieNewAuth@720.png` so I guess that I will have to replace both files.

**Comment by franconovel** [comment]
Glad to help, you should try, i doesn't have any @720 files on that folder, only @1080, my atv 3 model is A1469, reboot is needed for icon to show up after replace.

**Comment by moodyblue** [comment]
WiKi has been updated, thank you very much for your suggestion.
