### ISSUE TITLE
PLEXCONNECT COMPATIBILITY WITH PMS QNAP

### ISSUE THREAD

**Issue by oxlordi96** [iBaa/PlexConnect#571]
Hi, I'm having some issues with plexconnect and PMS stored on a QNAP . I've updated to 1.16.6.1592 but the ATV3 (or the PlexConnect script) won't find any PMS available! I've set the IP on PMS and logged into the account on the ATV too, but still not working!
Can you help me somehow? Thank you.
Matteo

**Comment by moodyblue** [comment]
User support is provided in forums only

https://forums.plex.tv/tags/c/third-party/apps-tools/53/plexconnect

**Comment by oxlordi96** [comment]
@moodyblue but the last update of PLEXCONNECT is working with the last updates of PMS?

**Comment by moodyblue** [comment]
Yes
