### ISSUE TITLE
Help with VPN and Ubuntu Server

### ISSUE THREAD

**Issue by wes1993** [iBaa/PlexConnect#572]
Hello,
I'm trying to set up PlexConnect in my Ubuntu Server 18.04 LTS.
I have do everything but when i start the server seems that take the VPN ip and not the LAN ip.
How can i solve this problem?
Thanks a Lot
Stefano

**Comment by sreknob** [comment]
Try specifying the IP address of the local adapter in the settings file
See here for details --> https://github.com/iBaa/PlexConnect/wiki/Settings-for-advanced-use-and-troubleshooting#webserver

```
enable_plexconnect_autodetect = False
ip_plexconnect = 0.0.0.0
```

**Comment by wes1993** [comment]
Thanks a lot for your reply.
Is correct in this way?
IP_self: enable_plexconnect_autodetect = False, ip_plexconnect = 192.168.0.102 - manual override for VPN usage 
Inside the Settings.py

Thanks a Lot
Stefano

**Comment by wes1993** [comment]
Thanks a Lot fro your reply.
I have do the edit but won't work...
The apple TV can connect to the server but when i try to run Trailers the log says Trailers not available now, try later.
Some log:

`Mar 27,2020 14:14:49 DNSServer: DNS request received!
Mar 27,2020 14:14:49 DNSServer: Source: ('192.168.0.103', 61732)
Mar 27,2020 14:14:49 DNSServer: Domain: e17437.dscb.akamaiedge.net
Mar 27,2020 14:14:49 DNSServer: ***forward request
Mar 27,2020 14:14:49 DNSServer: -> DNS response from higher level
Mar 27,2020 14:14:49 DNSServer: DNS request received!
Mar 27,2020 14:14:49 DNSServer: Source: ('192.168.0.103', 54449)
Mar 27,2020 14:14:49 DNSServer: Domain: play.itunes.apple.com
Mar 27,2020 14:14:49 DNSServer: ***forward request
Mar 27,2020 14:14:49 DNSServer: -> DNS response from higher level
Mar 27,2020 14:14:50 DNSServer: DNS request received!
Mar 27,2020 14:14:50 DNSServer: Source: ('192.168.0.103', 53829)
Mar 27,2020 14:14:50 DNSServer: Domain: init-p01md.apple.com
Mar 27,2020 14:14:50 DNSServer: ***forward request
Mar 27,2020 14:14:50 DNSServer: -> DNS response from higher level
Mar 27,2020 14:14:50 DNSServer: DNS request received!
Mar 27,2020 14:14:50 DNSServer: Source: ('192.168.0.103', 60629)
Mar 27,2020 14:14:50 DNSServer: Domain: s.mzstatic.com
Mar 27,2020 14:14:50 DNSServer: ***forward request
Mar 27,2020 14:14:50 DNSServer: -> DNS response from higher level
Mar 27,2020 14:14:52 DNSServer: DNS request received!
Mar 27,2020 14:14:52 DNSServer: Source: ('192.168.0.103', 55833)
Mar 27,2020 14:14:52 DNSServer: Domain: sync.itunes.apple.com
Mar 27,2020 14:14:52 DNSServer: ***forward request
Mar 27,2020 14:14:52 DNSServer: -> DNS response from higher level
**Mar 27,2020 14:18:35 WebServer: serving .xml: /
Mar 27,2020 14:20:33 WebServer: serving *.cer: /trailers.cer
Mar 27,2020 14:22:00 DNSServer: DNS request received!
Mar 27,2020 14:22:00 DNSServer: Source: ('192.168.0.103', 62281)
Mar 27,2020 14:22:00 DNSServer: Domain: trailers.apple.com
Mar 27,2020 14:22:00 DNSServer: ***intercept request
Mar 27,2020 14:22:00 DNSServer: -> DNS response: 0.0.0.0**
`
Thanks a lot for all your help
STefano

**Comment by wes1993** [comment]
Thanks a Lot
I have solved!! :-D
