### ISSUE TITLE
ATV3 7.4 issue

### ISSUE THREAD

**Issue by xk42** [iBaa/PlexConnect#575]
Managed to run through all the steps and I see iMovie Theatre with the Plex icon. My issue is that whenever I open up iMovie Theatre, it says it is unavailable. I can curl my PMS from atv3. I've not touched the certificates because I allow no authentication from my plexconnect atv3 ip.

Running ATV3 7.4 on A1427

```
Apr 20,2020 11:27:07 PlexConnect: Started
Apr 20,2020 11:27:07 PlexConnect: Version: 0.7.1-080420
Apr 20,2020 11:27:07 PlexConnect: Python: 2.7.6 (linusyang, Feb  3 2014, 10:14:39)
[GCC 4.2.1 Compatible Apple Clang 3.0 (tags/Apple/clang-211.11)]
Apr 20,2020 11:27:07 PlexConnect: Host OS: darwin
Apr 20,2020 11:27:07 PlexConnect: PILBackgrounds: Is PIL installed? False
Apr 20,2020 11:27:07 PlexConnect: IP_PMS: 192.168.1.4
Apr 20,2020 11:27:07 PlexConnect: IP_self (from settings): 127.0.0.1
Apr 20,2020 11:27:07 WebServer: Started
Apr 20,2020 11:27:07 WebServer: ***
Apr 20,2020 11:27:07 WebServer: WebServer: Serving HTTP on 127.0.0.1 port 80.
Apr 20,2020 11:27:07 WebServer: ***
Apr 20,2020 11:27:07 WebServer: Started
Apr 20,2020 11:27:07 WebServer: ***
Apr 20,2020 11:27:07 WebServer: WebServer: Serving HTTPS on 127.0.0.1 port 443.
Apr 20,2020 11:27:07 WebServer: ***

```

Here's the curl output. I've truncated it.

```
Apple-TV:/Applications/PlexConnect root# curl 192.168.1.4:32400
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="26" allowCameraUpload="1" allowChannelAccess="1" allowMediaDeletion="1" allowSharing="1" allowSync="0" allowTuners="0" backgroundProcessing="1" certificate="1" companionProxy="
```

**Comment by moodyblue** [comment]
> I've not touched the certificates because I allow no authentication from my plexconnect atv3 ip.
That's the reason. The certificates loaded in the ATV3 must be the same as stored in `/Applications/PlexConnect/assets/certificates`

**Comment by xk42** [comment]
Ah right. Thanks it now works. I thought we didn't need to touch the certificates because it says this in the guide.

>Then it's time to install certificates and use PlexConnect. It is highly recommended that you login PlexConnect to https://plex.tv to benefit from secure connections, Plex Pass, and be able to access remote Plex servers. If not you have to authorize the ip used by the ATV3 to access Plex Media Server as explained here.

**Comment by xk42** [comment]
I got it to work by setting the profile to http://localhost/iMovie.cer

**Comment by moodyblue** [comment]
Wiki has been clarified, thanks.
