### ISSUE TITLE
Is MyPlex auth fully client side on the ATV?

### ISSUE THREAD

**Issue by hcuk94** [iBaa/PlexConnect#576]
I'm running PlexConnect remotely (data centre - I have pre-existing capacity) as I would like to be able to use it across multiple homes (mine, family, etc).
I'm doing the DNS record locally at each site - so I've turned off DNS on the PlexConnect host (and its firewalled out anyway) - I am well aware that a public resolver is not a good idea :-)
I'm running the web server on 80 and 443 though, but with not all sites having static internet IPs, I'm leaving this open to internet. I've disabled plexgdm and am using MyPlex auth on the Apple TVs to connect - the PlexConnect IP does **not** have unauthenticated access to Plex.

My main question; is the MyPlex auth fully client-side? In other words is there any risk that a random person off the internet could use my server IP and connect through to my Plex Server? 
I'm comfortable with the risk that someone could use my PlexConnect, but as long as they would have to auth with their own Plex account and therefore only see their own server; I am comfortable with this.

**Comment by moodyblue** [comment]
> My main question; is the MyPlex auth fully client-side? In other words is there any risk that a random person off the internet could use my server IP and connect through to my Plex Server?

https://blog.filippo.io/how-plex-is-doing-https-for-all-its-users/ If you have more questions about it feel free to ask in the Plex forum

> I'm comfortable with the risk that someone could use my PlexConnect, but as long as they would have to auth with their own Plex account and therefore only see their own server; I am comfortable with this.

Your credentials are kept in `ATVSettings.cfg`. If you jailbreak the ATV this file is stored in the ATV, so if the ATV is lost you need to change your credentials. If the ATV is not jb'd than you need to edit `ATVSettings.cfg` and remove the section where the lost ATV is defined.

**Comment by hcuk94** [comment]
Excellent thanks, that answers my question! Just wanted to make sure logging in on one ATV isn't going to allow any ATV to use that account. Cheers.
