### ISSUE TITLE
Plexconnect works with VPN, but all other ATV apps don't.

### ISSUE THREAD

**Issue by shabshabshabado** [iBaa/PlexConnect#577]
Plexconnect correctly works on ATV 3rd Gen - everything in Plex/trailers app works perfectly.

But all of the other apps (Netlix, AppleTV+, Amazon Prime, Youtube) fail to connect to the internet.
I have checked all the settings in the ATV several times.

I have split tunneling setup in my VPN (PIA) on my server to by default **allow** all traffic to bypass the VPN. I only have specific apps set to go through the VPN, so I'm not sure why plexconnect is having issues passing other traffic through.  

Is it a DNS issue?

**Comment by moodyblue** [comment]
User questions in the Plex forum, please.

https://forums.plex.tv/tags/c/third-party/apps-tools/53/plexconnect
