### ISSUE TITLE
ATV 3 no Thumbnails, Error when attempting to play media files 

### ISSUE THREAD

**Issue by AGJHelmet** [iBaa/PlexConnect#578]
I have seen a few people in the past on here that have had this same issue. At the time of this post I am running the latest commit of plexconnect. My ATV3 will connect to the server, and I can go through my movies. Although, I can't see any thumbnails or picture metadata. When I attempt to play a movie I receive the "An error occurred loading content" error. 

Apple-TV-Version: 7.2.2
PlexConnect: Version: 0.7.1-080420
PlexConnect: Python: 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]

Running windows 10

**Comment by moodyblue** [comment]
Please report your problem in the forum https://forums.plex.tv/tags/c/third-party/apps-tools/53/plexconnect attaching the `PlexConnect.log` file
