### ISSUE TITLE
OpenSSL version requirement ?

### ISSUE THREAD

**Issue by phis5533** [iBaa/PlexConnect#580]
Hello,

I try to install PlexConnect on an old iMac with OS X 10.6.8.
The server starts with no issues, but when I try to connect in my ATV2, I got the message " Trailers is unavailable. Try again later."

```
Jun 09,2020 10:59:46 DNSServer: Domain: se-edge.itunes.apple.com
Jun 09,2020 10:59:46 DNSServer: ***forward request
Jun 09,2020 10:59:47 DNSServer: -> DNS response from higher level
Jun 09,2020 11:00:23 DNSServer: DNS request received!
Jun 09,2020 11:00:23 DNSServer: Source: ('192.168.86.58', 51637)
Jun 09,2020 11:00:23 DNSServer: Domain: trailers.apple.com
Jun 09,2020 11:00:23 DNSServer: ***intercept request
Jun 09,2020 11:00:23 DNSServer: -> DNS response: 192.168.86.56
```
With my other modern Mac it works fine.
I think the problem can come from OpenSSL version, which is "OpenSSL 0.9.8y 5 Feb 2013".
In the modern Mac it is "LibreSSL 2.8.3"
Can you tell me if there is prerequisites for this component please ? 
Thank you

**Comment by moodyblue** [comment]
This issue is being handled in the Plex forum

https://forums.plex.tv/t/atv2-macos-10-6-8-plexconnect-0-7-1/604915
