### ISSUE TITLE
PlexConnect daemon

### ISSUE THREAD

**Issue by kwpcreative72** [iBaa/PlexConnect#581]
I'm running Mac OS Catalina. I installed the autostart daemon, but PlexConnect doesn't launch at startup. I also found a script to turn PlexConnect on and off, but it failed to work for me. Any suggestions besides opening terminal every time?

Thanks.

**Comment by moodyblue** [comment]
I would suggest to post this question in plex forum where chances to get an answer are higher

https://forums.plex.tv/tags/c/third-party/apps-tools/53/plexconnect
