### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by ENjOY88** [iBaa/PlexConnect#586]
With 0.7.1 channels don’t show in the title bar but if I drop back to 0.6 they do and work fine. I use HDHR.Viewer2 bundle as a work around for HDHomeRun into ATV2&3. It works great in 0.6 and always has.

**Comment by moodyblue** [comment]
Do you have channels enabled in settings -> general appearance ? PlexConnect 0.7.x hides channel views by default.

**Comment by ENjOY88** [comment]
moodyblue you are a genuis!! i had never even looked in there!! Stupid mistake on my part. Thanks again now i am up and running on current 0.7.4. My final challenge is to get the ATV2 to take the plex icon. Ill keep tryin a few things.

Thanks again!
