### ISSUE TITLE
File not found while trying to create a certificate

### ISSUE THREAD

**Issue by Crackpot370** [iBaa/PlexConnect#588]
I went to https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Windows to figure out how to create a certificate.

I downloaded & installed everything. Seemed to go fine until I went to https://github.com/iBaa/PlexConnect/wiki/Install-Guide-Windows-Certificates to follow the steps to create the certificate.

After entering:
    C:\OpenSSL-Win32\bin\openssl.exe req -new -nodes -newkey rsa:2048 -out C:\trailers.pem -keyout C:\trailers.key -x509 -days 7300 -subj "/C=US/CN=trailers.apple.com" -config C:\OpenSSL-Win32\bin\openssl.cfg

I got:
    Can't open C:\OpenSSL-Win32\bin\openssl.cfg for reading, No such file or directory
    6632:error:02001002:system library:fopen:No such file or directory:crypto\bio\bss_file.c:69:fopen<'C:\OpenSSL-Win32\bin\openssl.cfg','r'>
    6632:error:2006D080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:76:

Apparently there is no openssl.cfg in the Win32OpenSSL_Light-1_1_1h.msi I used.
I know the installation guide said to use Win32OpenSSL_Light-1_0_2q.exe, but that doesn't exist on that page anymore so I had to use Win32OpenSSL_Light-1_1_1h.msi instead.
Is there some place I can get that file?

Not sure at all what to do with the 6632 error. :+1: 

Any help would be really appreciated.

**Comment by moodyblue** [comment]
Try this

`C:\OpenSSL-Win64\bin\openssl.exe req -new -nodes -newkey rsa:2048 -out C:\trailers.pem -keyout C:\trailers.key -x509 -days 7300 -subj "/C=US/CN=trailers.apple.com" -config "C:\Program Files\Common Files\SSL\openssl.cnf"`

**Comment by moodyblue** [comment]
Closed due to inactivity
