### ISSUE TITLE
Improve Wiki

### ISSUE THREAD

**Issue by mrbeast87** [iBaa/PlexConnect#592]
Sorry if I'm posting this in the wrong place, please move it to the correct one or tell me where I should post this kind of suggestion.

I just installed PlexConnect and it is working with my Apple TV, thank you so much for this useful little tool!

I lost a bit of time, however, because I was having this error:

> We failed to reach a server. Reason: Unauthorized

By searching around I found that I could add my Apple TV IP to PMS list of IP addresses that are allowed without auth. However, that didn't work either.

Only later I found that I should simply log in with my Plex account in Apple TV "Trailers" (Plex) application. After that, everything was working.

I think the wiki could benefit from having this information (add a step saying that you need to either log in or add the IP address). Let me know if you agree or if you want me to make that page.

Thanks!

**Comment by moodyblue** [comment]
Thanks very much for bringing this to my atention. Can you pls post the link to the wiki pages that need to be changed ?

**Comment by moodyblue** [comment]
I've made some changes in the wiki, pls let me know if now it's ok.

**Comment by mrbeast87** [comment]
Looks great! Thank you 👍
