### ISSUE TITLE
OS specific directory/file separator?

### ISSUE THREAD

**Issue by iBaa** [iBaa/PlexConnect#594]
https://github.com/iBaa/PlexConnect/blob/7992269af8dd3c9f5e9cd7637f24192d8332d1a4/ATVSettings.py#L122

This “/“ should be +sep+... shouldn‘t it?

**Comment by moodyblue** [comment]
Back in business ? I'm really happy to see you around. If you think that change makes sense go ahead and do it, I can test it afterwards.

**Comment by moodyblue** [comment]
Applied your fix. Thanks.
