### ISSUE TITLE
Error when I select 

### ISSUE THREAD

**Issue by Jelly-Flinger** [iBaa/PlexConnect#595]
Apologies if this is a known issue or covered elsewhere. I did try and search around but I suspect I have messed up somewhere.

FYI used plexconnect for years. Its an awesome bit of code and super reliable. Many thanks!

I have a couple of movie libraries in plex. Recently one of the libraries stopped working after a lot of messing around I traced the issue back to a plex setting "Plex Movie" vs "Plex Movie (Legacy)"  . 

I am running Version: 0.7-dev-151218 , Python: 2.7.15.  I tried 0.72 (because I see the note "Support Plex Movie libraries in PMS 1.20+"). I still seemed to have the same problems though and could not see any of the artwork.  I reverted back to my existing install and after messing around fixed the issue.

In manage libraries if I 

- edit any movie library 
- go to advanced 
- in the Agent drop down I see "Plex Movie (Legacy)" 
- switch to "Plex Movie" 
- when I attempt to access the library via an apple tv the error below is generated 

Took me a lot of messing but when I changed another movie library to "Plex Movie (Legacy)"  I got the same error and when I changed both to "Plex Movie (Legacy)"  the error cleared and both libraries became accessible via apple tv. I am all good for now but I guess if Plex dumps the legacy option in future I am back to square one.

Traceback (most recent call last):
  File "C:\Program Files (x86)\PlexConnect-master\WebServer.py", line 244, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "C:\Program Files (x86)\PlexConnect-master\XMLConverter.py", line 390, in XML_PMS2aTV
    aTVTree = etree.parse(sys.path[0]+'/assets/templates/'+XMLtemplate)
  File "<string>", line 62, in parse
  File "<string>", line 26, in parse
IOError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\PlexConnect-master/assets/templates/Plex/Movie.xml'

**Comment by moodyblue** [comment]
0.7-dev-151218 is too old, try the latest release instead (where this problem is solved)

**Comment by moodyblue** [comment]
Strange... 0.7.2 works for me

**Comment by moodyblue** [comment]
Closed due to inactivity
