### ISSUE TITLE
plexconnect script doesnt start at start up

### ISSUE THREAD

**Issue by Hawk321** [iBaa/PlexConnect#596]
![Screenshot_10](https://user-images.githubusercontent.com/26680543/120181086-dd1d1980-c20c-11eb-82e1-d5274b08cfe4.png)
![Screenshot_1](https://user-images.githubusercontent.com/26680543/120181088-ddb5b000-c20c-11eb-9233-7a8559bcb0e1.png)

As seen in the pictures above the script can't find Python and therefore it can startup. I can't change the app alias so I am stuck.

**Comment by moodyblue** [comment]
I think you need to add your python installation to the PATH, but as I'm not a windows user I can't confirm. Better resubmit your question in the Plex forum

https://forums.plex.tv/tags/c/third-party/apps-tools/53/plexconnect
