### ISSUE TITLE
Thumbnails & Cover Art Missing

### ISSUE THREAD

**Issue by kittonian** [iBaa/PlexConnect#597]
With PMS running on Big Sur (OS X) and PlexConnect running on the same machine, as of PMS 1.23.2.4625 PlexConnect is no longer showing any thumbnail images. This is not related to PIL/Pillow not being recognized because as long as Pillow 6.2.2 is installed on Python 2.7.16 Pillow is properly recognized by PlexConnect and FanArt can be enabled and will show properly.

Previous versions of both PlexConnect and PMS have had no issues showing all thumbnails and cover art.

This issue seems to be directly related to PlexConnect accessing the thumbnail images, cover art, etc. from this new version of PMS.

**Comment by warnesj** [comment]
Yeah I have the same cover art issue with PMS v1.23.2.4656 running on a QNAP NAS too.

**Comment by moodyblue** [comment]
As a temporary workaround do not login to plex.tv

**Comment by warnesj** [comment]
I applied the update and works on my Apple TV 3 with PMS v1.23.2.4656 running on a QNAP NAS.
