### ISSUE TITLE
ATV 2 Trailers Icon

### ISSUE THREAD

**Issue by ENjOY88** [iBaa/PlexConnect#604]
I cannot get the ATV2 trailers icon to change. Prior to the latest changes from apple, i used iMovie and successfully changed the icon using OpenPlex. I also have an ATV3, trailers changes no problem using OpenPlex or iBaa Master, so i feel that my procedure is correct. I noticed in the ATV2 storeFront the icon URL on the ATV2 is "file:///Applications/AppleTV.app/movie-trailers@720.png" seems different to the other apps that have http urls. Could this be what im battling?

Many thanks.

**Comment by moodyblue** [comment]
It's no longer possible to use storeFront after iOS 5.3, you should use exactly the same process as in ATV3.
