### ISSUE TITLE
Not able to select a version when multiple versions are available

### ISSUE THREAD

**Issue by mrbeast87** [iBaa/PlexConnect#609]
I use a raspberry pi as a plex server. Since it doesn't have a lot of power, when it has to transcode, a lot of times it hangs on the media playback.

But Plex allows to make Optimized Versions, so that the server can perform the transcoding before the media is played, instead of while the media is being played.

The problem is that PlexConnect does not allow to select a version. It always plays the original file.

We need to be able to select the media, or even automatically select for the version optimized for TV (since apple tv will always be connected to a TV).

**Comment by carlsteinhilber** [comment]
In my experience, I don't think you should be optimizing for TV, but for iOS... since the Apple TV is essentially an iOS device.

Then the PMS will automatically deliver the proper, pre-transcoded version.

**Comment by mrbeast87** [comment]
Thanks for your suggestion, I will definitely try it out. But my external disk just died, so it might take me a couple of days to get everything into place.

**Comment by moodyblue** [comment]
Not an issue. Discussions should take place in the Plex forum.
