### ISSUE TITLE
Had it with PlexConnect

### ISSUE THREAD

**Issue by UKenGB** [iBaa/PlexConnect#612]
It's dead. Forget it. Move on.

I thought there were still those who thought it worthwhile, but no-one responds and it doesn't work anymore.

I put a lot of time into figuring it out and with the hope that I could improve it once conversant with its operation and methodology. But there's NO-ONE who can explain and help with its inner workings. Despite this, I set up the 3 x AppleTV 3s to run PlexConnect and they worked. All of them. It was then just a process of studying the code to be able to make improvements (like PMS listing compilations separately which means PlexConnect doesn't see them). Unfortunately having got all 3 AppleTV 3s working, I had leave them for a few months while having to do other stuff.

So today, I wanted to listen to music at one of the locations with a PlexConnected AppleTV 3. Several hours later and I still cannot figure why NONE of them can find the Plex Server and hence NOTHING is available. When I set them up, all worked fine. They could find the server, log in and access all the expected libraries. Some months later and I have changed NOTHING, but PlexConnect is no longer usable. I may have updated PMS, but that still doesn't explain why what worked no longer does.

I have come to the conclusion that it's all too flakey and that no-one cares. So that's it. I'm dismantling all the PlexConnect stuff on my server and will sell the AppleTV3s. It was a great idea, but discarded by the original developers and for unknown reasons now is utterly useless. Means I wasted a  LOT of time on it, so I suggest others should move on and don't waste their own time. Just get an AppleTV4. Plex does work on those.Very well in fact. But PlexConnect? Nah. Don't waste your time.

**Comment by m-t-space** [comment]
It's certainly a frustrating experience at times, other times it's brilliant.
I recently had it stop working and fixed it by going into the appleTV settings, doing a hard restart, and re-adding the certificate. It took about 5 minutes. Try that!

**Comment by UKenGB** [comment]
I had all this trouble previously, got it sorted and all 3 ATVs running again. Then for no apparent reason, none can find the PMS. If I put the effort in to sort it, I have no confidence it wouldn't simply re-occur later. In fact I am convinced it would.

It is such a shame as PlexConnect was a fine piece of work. Just needed a bit of tweaking to keep it functioning correctly with the latest Plex (which it does not). A great idea and extremely well executed I thought. A great way to keep using an ATV3. But I realised I had no time to mess with all that and an ATV4 'just works' and is completely consistent with the other ATVs around the house. So it's sad, but time to say goodbye to the ATV3s and PlexConnect. It was good knowing you. :-)

**Comment by UKenGB** [comment]
One more point. I JailBroke my ATV3s and was able to add PlexConnect as an additional app, with its correct icon and name. No -co-opting some other app. This was the perfect solution I thought. Even the AppleTV+ app was up to date and working just like on the ATV4. Amazon Prime worked (a little differently, but provided access to to my account).

Then Apple released a system update, without which the AppleTV+ app won't load. However, updating failed - probably due to the JB. In any case, although NOW is still an included app, it doesn't actually work as NOWTV (Sky) has discontinued that service. No amount of tweaking will get that working.

So not only is PlexConnect becoming a problem, but the ATV3 was failing in many other respects. How long before Prime discontinue their support for this old device. Will Apple update AGAIN so the AppleTV+ app stops working?

So it all seems to be falling apart and I decided it was time to move on and just get more ATV4s.

**Comment by b1tman1ac** [comment]
I'm sorry for your experience. I've had my issues but I've managed to work through them. Mind you I'm running an old Apple TV 2 that Apple never cares to update. Almost 10 years on and this project is still working for me. That's more then I can say for some projects. Thank you guys!!!

**Comment by moodyblue** [comment]
Probably fix applied today solved the issue.
