### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

### ISSUE THREAD

**Issue by sojab0on** [iBaa/PlexConnect#614]
Hi when i start the plexconnect.py file with sudo ./PlexConnect.py it spits back 

odroid@odroid:/usr/local/lib/PlexConnect$ sudo ./PlexConnect.py
Traceback (most recent call last):
  File "/usr/local/lib/PlexConnect/./PlexConnect.py", line 20, in <module>
    import DNSServer, WebServer
  File "/usr/local/lib/PlexConnect/DNSServer.py", line 116
    print "ID {0:04x}".format((ord(paket[0])<<8)+ord(paket[1]))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

its an arm 32bit system with a fully upgraded ubuntu 22.04.1 LTS image and a clean clone from the git by the given commands 

what can i do to fix this rest of the guide has been followed certificates and al are created and places where they should be

**Comment by carlsteinhilber** [comment]
PlexConnect has not been updated for several years, and is still Python 2.x-based. The print statement changes are one of the more visible updates you'll encounter when you try to run Python 2 code in Python 3, which leads me to believe that may be your issue (though it's tough to confirm).

Make sure you are launching PlexConnect in Python 2.

Try opening a command line and executing:
`python --version`
If it returns anything not "v,2.xxx", then you either do not have Python 2 installed, or it is not set as the default Python environment. You will have to Google how to install and force Python 2, that is beyond the scope of this issue tracker.
